/* Finds a salt for every generated question that would otherwise repeat a
   question in an earlier exam, and writes src/engine/salts.js.
   Run after changing any generator: node tools/dedupe.js */
'use strict';
const fs = require('fs'), path = require('path'), vm = require('vm');
const { expand, ROOT } = require('./load');
const order = require('./order.json').filter(f => !f.startsWith('src/ui/') && f !== 'src/engine/salts.js');
const files = [].concat.apply([], order.map(expand)).filter(f => fs.existsSync(f));
const src = files.map(f => fs.readFileSync(f, 'utf8')).join('\n;\n');
const SALTS = {};
function fresh() {
  const ctx = { console, Math, JSON, Date, SALTS };
  vm.createContext(ctx);
  vm.runInContext('var SALTS = this.SALTS;\n' + src + ';this.o={EXAMS,buildExamModule,examReady,_EXAM_CACHE};', ctx);
  return ctx.o;
}
let L = fresh();
const fp = it => it.stem + '||' + JSON.stringify(it.options) + (it.svg || '') + JSON.stringify(it.table || '') + (it.optionSvgs || []).join('');
const seen = new Set();
let changed = 0;
for (const ex of L.EXAMS) {
  for (const m of ['maths', 'thinking']) {
    if (!L.examReady(ex.id, m)) continue;
    for (let round = 0; round < 40; round++) {
      Object.keys(L._EXAM_CACHE).forEach(k => delete L._EXAM_CACHE[k]);
      const p = L.buildExamModule(ex.id, m);
      const clash = p.items.filter(it => it.slotKey && seen.has(fp(it)));
      // also clashes inside the same paper
      const local = new Set(); p.items.forEach(it => { const k = fp(it); if (local.has(k) && it.slotKey) clash.push(it); local.add(k); });
      if (!clash.length && p.audit && !p.audit.ok && round < 30) {
        // the answer key has a pattern: re-roll one generated question (chosen by the round number)
        const gen = p.items.filter(it => it.slotKey);
        clash.push(gen[(round * 7 + 3) % gen.length]);
      }
      if (!clash.length) { p.items.forEach(it => seen.add(fp(it))); break; }
      clash.forEach(it => { SALTS[it.slotKey] = (SALTS[it.slotKey] || 0) + 1; changed++; });
    }
  }
}
const out = '/* Generated by tools/dedupe.js — do not edit by hand. */\nconst SALTS = ' + JSON.stringify(SALTS) + ';\n';
fs.writeFileSync(path.join(ROOT, 'src/engine/salts.js'), out);
console.log(`salts.js written: ${Object.keys(SALTS).length} questions re-rolled (${changed} re-rolls)`);
