/* Hard Exam 1 — original content written for this site. Pitched well above the real test. */
'use strict';
defExam('H01', {
  reading: [
    readS1({ id: 'H01-s1', headnote: 'Two writers reflect on keeping a promise. Extract A is written in the style of a nineteenth-century novel; Extract B is from a contemporary essay.',
      glossary: [['scrupulous', 'extremely careful to do what is right'], ['candour', 'honesty and openness']],
      extracts: [
        { label: 'Extract A', paras: [
          'Mr Ashby had promised his late brother that he would see the boy educated, and he was a man who regarded a promise rather as other men regard a debt: not a thing to be discussed, still less renegotiated, but simply discharged. That the boy showed no aptitude for Latin, an open hostility to Greek and a talent chiefly for drawing horses in the margins of his grammar did not, in Mr Ashby’s view, alter the terms of the agreement in the least.',
          'It was his housekeeper, a woman of more sense than education, who first suggested that the late Mr Ashby might have meant something wider by the word. “He wanted the lad brought on, sir,” she said, setting down the tea. “Brought on to something. I don’t suppose he cared which.” Mr Ashby received this as he received most of her remarks, in silence; but the next week a drawing-master was engaged, and the Greek grammar went, without ceremony, into the bottom drawer of the bureau, where it remained for eleven years.',
          'He never acknowledged that he had changed his mind. He maintained to the end of his life that he had kept his promise exactly; and it is possible, on reflection, that he was right.',
        ] },
        { label: 'Extract B', paras: [
          'We tend to praise people who keep their word to the letter, and there is something admirable in that. But a promise is made at one moment and kept at another, and the world does not stand still in between. The friend who promised to help you move house on Saturday, and who arrives on Saturday despite having learned on Friday that her mother is in hospital, has kept her promise. Whether she has done the right thing is a different question.',
          'The harder and more honest course is to ask what the promise was for. A promise is a means of giving someone security about the future; to keep it in a way that defeats its purpose is to obey it while betraying it. This requires judgement, which is uncomfortable, and candour, which is rarer still. It is easier to say “I did what I said I would” than “I did what you would have wanted, and here is why it differs from what I said.”',
        ] },
      ],
      questions: [
        Q('In Extract A, what does the comparison of a promise to “a debt” suggest about Mr Ashby?', ['He was in financial difficulty.', 'He saw a promise as an obligation to be fulfilled without question.', 'He expected to be paid for keeping promises.', 'He disliked making promises.'], 1,
          'A debt is “not a thing to be discussed … but simply discharged”: for him, a promise was an obligation to fulfil exactly. Disliking promises is the nearest rival, but his attitude is about how firmly he keeps them, not reluctance to make them.',
          ['the comparison is about obligation, not money troubles', null, 'he expects nothing in return', 'his attitude concerns keeping promises firmly, not avoiding them']),
        Q('The description of the boy’s abilities in the first paragraph is mainly', ['an admiring account of his talents.', 'gently comic, showing how unsuited he was to classical study.', 'a criticism of Mr Ashby’s teaching.', 'evidence that the boy was lazy.'], 1,
          'No aptitude for Latin, “open hostility” to Greek and a talent for drawing horses in the margins: the effect is gently comic. Evidence of laziness is the nearest rival, but drawing horses shows a real talent, simply a different one.',
          ['the tone is amused, not admiring', null, 'Mr Ashby is not teaching him himself', 'drawing shows talent, not idleness']),
        Q('What does the housekeeper suggest about the late brother’s wishes?', ['He wanted the boy to learn Greek above all.', 'He wanted the boy to develop in whatever direction suited him.', 'He did not care about the boy.', 'He wanted the boy to become a housekeeper.'], 1,
          '“Brought on to something. I don’t suppose he cared which”: the aim was the boy’s development, not a particular subject. Not caring about the boy is the nearest rival, but “I don’t suppose he cared which” refers to the subject, not the boy.',
          ['she suggests the opposite', null, '“which” refers to the subject, not the boy', 'nothing suggests this']),
        Q('How does Mr Ashby respond to the housekeeper’s suggestion?', ['He argues with her but eventually agrees.', 'He says nothing but quietly acts on it.', 'He dismisses her from service.', 'He tells her she is wrong and keeps the Greek lessons.'], 1,
          'He receives it “in silence”, yet the next week engages a drawing-master. Telling her she is wrong is the nearest rival, but the Greek grammar goes into the drawer.',
          ['he does not argue', null, 'she is not dismissed', 'the Greek grammar is put away']),
        Q('What is the effect of the detail that the Greek grammar stayed in the drawer “for eleven years”?', ['It shows that Greek was forgotten completely, quietly confirming the change of plan.', 'It shows that Mr Ashby planned to return to Greek.', 'It shows the drawer was rarely opened by the housekeeper.', 'It shows the book was valuable.'], 0,
          'The long, untouched years show the decision was final, even though it was never announced. That Mr Ashby planned to return to Greek is the nearest rival, but eleven years of disuse suggests the opposite.',
          [null, 'eleven untouched years suggest the opposite', 'the detail is about the plan, not housekeeping', 'value is not suggested']),
        Q('Why might the narrator of Extract A think Mr Ashby “was right” that he had kept his promise exactly?', ['Because the boy eventually learned Greek.', 'Because he fulfilled what his brother truly intended, even if not the literal terms he first assumed.', 'Because the housekeeper agreed with him.', 'Because promises cannot be broken.'], 1,
          'If the brother wanted the boy “brought on to something”, educating him in drawing honoured that wish. The boy eventually learning Greek is the nearest rival, but the grammar stayed in the drawer.',
          ['the Greek grammar stayed in the drawer', null, 'the housekeeper’s view is not the narrator’s reason', 'the narrator does not claim this']),
        Q('What is the main point of the friend example in Extract B?', ['Keeping a promise exactly is always right.', 'Keeping a promise to the letter is not necessarily the right thing to do.', 'Friends should not ask for help moving house.', 'Hospitals should allow more visitors.'], 1,
          'She keeps her word, but “Whether she has done the right thing is a different question”. Keeping a promise exactly always being right is the very view the example challenges.',
          ['this is the view the example challenges', null, 'the example is not about asking for help', 'hospital rules are not discussed']),
        Q('Which statement best describes how the two extracts relate?', ['Extract B states an idea that Extract A shows through a story.', 'Extract A disagrees with the argument made in Extract B.', 'Both extracts argue that promises should never be changed.', 'Extract B is a summary of the events in Extract A.'], 0,
          'B argues that keeping a promise means honouring its purpose; A shows Mr Ashby doing exactly that without admitting it. That A disagrees with B is the nearest rival, but A’s outcome supports B’s idea.',
          [null, 'A’s outcome supports B’s idea', 'both suggest promises can be kept in spirit', 'B does not mention these events']),
      ] }),

    readS2({ id: 'H01-s2', title: 'Wayfinding in the Pacific',
      text: 'Long before European navigators crossed the Pacific, Polynesian voyagers settled islands scattered across an area larger than Asia, sailing double-hulled canoes over thousands of kilometres of open ocean without compasses or charts. For a long time some European scholars refused to believe these journeys had been …(1)…, arguing that the islands must have been settled by accident, by canoes blown off course.\n\nThat view has been largely …(2)…. Navigators steered by the rising and setting points of particular stars, which they memorised as a kind of compass laid out around the horizon. They read the long, steady swells generated by distant weather systems, which could be felt through the hull even when the sky was …(3)…. Birds that feed at sea but sleep on land, and the reflected colour of a lagoon on the underside of clouds, could reveal an island long before it rose above the horizon.\n\nThis knowledge was …(4)… orally, through chants and long apprenticeship, rather than in writing. When European contact disrupted traditional life, much of it was lost, and by the twentieth century only a handful of navigators in remote atolls still …(5)… it.\n\nIn 1976, a reconstructed voyaging canoe sailed from Hawaii to Tahiti, guided by a navigator from Micronesia using only traditional methods. The voyage was not merely a scientific experiment; it became a source of great cultural pride and …(6)… a revival of traditional navigation across the Pacific. Today a new generation of navigators has been trained, and canoes have circumnavigated the globe.\n\nThe story is a …(7)… against assuming that knowledge which is not written down must be primitive or unreliable. The methods were not guesswork; they were a sophisticated system, refined over centuries and tested by the most …(8)… of examiners: the open sea.',
      gaps: [
        [['deliberate', 'dangerous', 'frequent', 'recorded'], 0, 'The contrast is with canoes “blown off course”: scholars doubted the voyages were “deliberate”. Recorded is the nearest rival, but the dispute was about intent, not records.', [null, 'nobody doubted they were dangerous', 'the dispute was about intent, not frequency', 'the dispute was about intent, not records']],
        [['abandoned', 'confirmed', 'ignored', 'admired'], 0, 'The evidence that follows overturns the accident theory, so it has been “abandoned”. Confirmed is the opposite.', [null, 'the evidence overturns the view', 'the view was discussed and rejected, not ignored', 'nothing about the view is praised']],
        [['overcast', 'bright', 'empty', 'stormy'], 0, 'Swells could be felt “even when the sky was overcast” and the stars hidden. Stormy is the nearest rival, but the point is that stars were not visible, which cloud cover explains exactly.', [null, 'a bright sky would show the stars', 'an empty sky makes little sense', 'the point is hidden stars, which cloud explains exactly']],
        [['transmitted', 'invented', 'concealed', 'disputed'], 0, 'Knowledge passed on through chants and apprenticeship was “transmitted orally”. Concealed is the nearest rival, but apprenticeship is about passing knowledge on.', [null, 'it was handed down, not newly invented', 'apprenticeship passes knowledge on', 'nothing suggests dispute among navigators']],
        [['possessed', 'opposed', 'discovered', 'questioned'], 0, 'Only a handful of navigators still “possessed” the knowledge. Discovered is the nearest rival, but they had inherited it, not found it.', [null, 'they were its keepers, not its opponents', 'they had inherited it, not found it', 'they practised it rather than doubting it']],
        [['inspired', 'prevented', 'replaced', 'delayed'], 0, 'The voyage became a source of pride and “inspired a revival”. Prevented and delayed are the opposite of what happened.', [null, 'the revival happened', 'it started something new rather than replacing it', 'the revival followed quickly']],
        [['warning', 'reason', 'race', 'weapon'], 0, 'The story is “a warning against assuming” such knowledge is primitive. Reason is the nearest rival, but “a reason against assuming” is not natural, and warning fits the cautionary tone.', [null, '“a reason against assuming” is not the natural phrase', 'race makes no sense', 'weapon is too aggressive']],
        [['unforgiving', 'generous', 'patient', 'predictable'], 0, 'The open sea punishes any error: the most “unforgiving” examiner. Predictable is the nearest rival, but the ocean is the opposite of predictable.', [null, 'the sea is not generous to mistakes', 'patience does not fit the danger', 'the ocean is the opposite of predictable']],
      ] }),

    readS3({ id: 'H01-s3', headnote: 'In this poem the speaker reflects on an old photograph of a family who once lived in the speaker’s house.', title: 'Previous Owners',
      lines: [
        'The agent found it, wedged behind the skirting:',
        'six people squinting on our own front step',
        'in someone’s Sunday best, the brickwork new,',
        'the jacaranda only knee-high yet.',
        '',
        'I know the step. I sit there in the mornings.',
        'I do not know the woman with the hat',
        'who holds the baby slightly to one side',
        'as if to show the camera what it’s got.',
        '',
        'The tree has grown to shade the whole front garden.',
        'The baby, by my sums, is ninety-four,',
        'or dead, or somewhere sitting on a step',
        'not knowing that I’ve found her at my door.',
        '',
        'We think we own a house. We hold it only',
        'the way the step holds whoever sits a while:',
        'not long. It doesn’t ask our names. It takes',
        'the weight of each of us, and keeps the smile.',
      ],
      questions: [
        Q('What do the details “the brickwork new” and “the jacaranda only knee-high” suggest?', ['The photograph was taken when the house was newly built, long ago.', 'The family had just planted a garden at their new home.', 'The house had been badly built.', 'The family were about to move away.'], 0,
          'New brickwork and a tiny tree show the photo dates from when the house was new; the tree has since grown to shade the garden. The family having just planted the garden is the nearest rival, but the details are there to fix the time, not to describe the family’s gardening.',
          [null, 'the details fix the time rather than describing the family’s gardening', 'nothing suggests poor building', 'nothing suggests moving']),
        Q('What does the speaker suggest about the woman holding the baby “slightly to one side / as if to show the camera what it’s got”?', ['She is uncomfortable holding the baby.', 'She is proudly presenting the baby.', 'She wants to hide the baby.', 'She is about to hand the baby to someone.'], 1,
          'Turning the baby towards the camera “to show … what it’s got” suggests pride. Being uncomfortable is the nearest rival, but the gesture is a display, not awkwardness.',
          ['the gesture is a display, not awkwardness', null, 'she is showing the baby, not hiding it', 'nothing suggests handing it over']),
        Q('What is the tone of lines 10–12 (“The baby, by my sums, is ninety-four, / or dead, or somewhere sitting on a step”)?', ['Coldly indifferent.', 'Matter-of-fact, but quietly moving.', 'Angry and bitter.', 'Joyful and excited.'], 1,
          'The plain arithmetic and the blunt “or dead” are matter-of-fact, yet the image of the baby now old, unknowingly found, is moving. Coldly indifferent is the nearest rival, but the speaker clearly cares, imagining her life.',
          ['the speaker clearly cares about her', null, 'nothing is angry', 'the mood is reflective, not joyful']),
        Q('Which word best describes the speaker’s relationship with the people in the photograph?', ['They are relatives.', 'They are strangers connected only by the place.', 'They are former friends.', 'They are enemies.'], 1,
          'The speaker does not know them but shares the step: strangers linked by the house. Relatives is the nearest rival, but the speaker says “I do not know the woman with the hat”.',
          ['the speaker does not know them', null, 'nothing suggests friendship', 'nothing suggests conflict']),
        Q('What idea is expressed in the final stanza?', ['People should not sell their houses.', 'We do not truly own a house; we only occupy it briefly, as many others have.', 'Old houses are better than new ones.', 'The speaker plans to find the woman.'], 1,
          '“We think we own a house. We hold it only … not long”: ownership is temporary, and the house outlasts each family. Not selling houses is the nearest rival, but the stanza reflects on ownership rather than giving advice.',
          ['the stanza reflects rather than advises', null, 'no comparison of old and new houses is made', 'no plan is mentioned']),
        Q('What does “and keeps the smile” (the final line) most likely mean?', ['The step keeps a record of the people who sat on it, as the photograph has.', 'The step is painted with a smile.', 'The speaker is smiling.', 'The family were unhappy.'], 0,
          'The step holds each person briefly but “keeps the smile”, as this photograph kept the family’s moment on it. The speaker smiling is the nearest rival, but the line is about the step.',
          [null, 'the line is figurative, not literal', 'the line is about the step', 'the photograph shows them smiling']),
      ] }),

    readS4({ id: 'H01-s4', title: 'Remembering, and remembering again',
      paras: [
        'It is natural to imagine memory as a kind of recording: an event happens, the brain stores a copy, and remembering means playing the copy back. ...(1)...',
        'In a series of experiments, researchers have shown that when a memory is recalled, it becomes briefly unstable before being stored again. ...(2)... During that window, the memory can be strengthened, weakened or altered, and the version that is stored afterwards may differ from the one that was recalled.',
        'This helps to explain some puzzling observations. ...(3)... Eyewitnesses who are questioned repeatedly about an event, especially with leading questions, can become more confident while becoming less accurate.',
        'It would be wrong, though, to conclude that memory is simply unreliable. ...(4)... A system that updates memories each time they are used allows us to keep them relevant, folding in new information about the world rather than preserving every detail of an outdated past.',
        'The findings have raised hopes in medicine. ...(5)... Early studies suggest that recalling a traumatic memory in a safe setting, at the moment when it is unstable, may reduce the distress it causes when it is stored again.',
        '...(6)... They suggest that the past we carry with us is not a fixed archive but something we keep rewriting, a little, every time we visit it.',
      ],
      sentences: [
        'Much of the evidence of the last few decades suggests that this picture is misleading.',
        'This process, sometimes called reconsolidation, seems to take some hours.',
        'Vivid memories that people are certain about, for example, are sometimes demonstrably wrong.',
        'The same flexibility may be useful.',
        'If memories can be changed when recalled, it may be possible to soften painful ones.',
        'Beyond the laboratory, these findings have an unsettling implication.',
        'Some people can remember what they ate for breakfast on every day of their lives.',
      ],
      answers: [0, 1, 2, 3, 4, 5],
      explains: [
        'The paragraph sets up the common picture of memory as a recording; the gap challenges it, which the next paragraph supports with experiments.',
        'Recalled memories become “briefly unstable”; the gap names the process and its duration, which “that window” then refers back to.',
        '“Puzzling observations” is followed by eyewitnesses becoming more confident but less accurate; the gap gives the first puzzle, confident memories that are wrong.',
        '“It would be wrong … to conclude that memory is simply unreliable” is answered by the flexibility being useful, which the next sentence explains.',
        '“Raised hopes in medicine” is explained by the possibility of softening painful memories, which the early studies then test.',
        'The final paragraph’s “They suggest …” needs a subject: these findings and their unsettling implication. The sentence about remembering every breakfast is the extra one; it is unrelated to reconsolidation.',
      ] }),

    readS5({ id: 'H01-s5', headnote: 'Four writers consider silence.',
      extracts: [
        { title: 'Extract A', paras: ['In music, a rest is not an absence. A composer writes it as precisely as any note, and a performer who rushes through it ruins the phrase as surely as one who plays a wrong pitch. Some of the most powerful moments in the repertoire are the silences just before a final chord, when the whole hall seems to hold its breath and the sound that follows is shaped by the expectation the silence has built.'] },
        { title: 'Extract B', paras: ['For most of human history, true quiet was ordinary: at night, away from towns, the loudest sounds were wind and animals. Today it is scarce. Researchers who map natural soundscapes report that few places on the continent are free of engine noise for more than a quarter of an hour. Some argue that quiet should be treated as a natural resource, protected as we protect clean water.'] },
        { title: 'Extract C', paras: ['After my father’s stroke, he could understand everything but say almost nothing. I learned to sit with him for an hour without speaking, which at first felt like failing him. It took me months to realise that he was not waiting for me to fill the silence. He was content in it, and the conversations I thought we had lost were happening in another way, through the hand he would put over mine when the news came on.'] },
        { title: 'Extract D', paras: ['Silence is often praised as wisdom, but it can just as easily be a failure of courage. The colleague who says nothing while a bad decision is made, the witness who looks away, the friend who does not mention what everyone can see: their silence is not neutral. It takes a side, usually the side of whoever benefits from nobody speaking.'] },
      ],
      items: [
        ['argues that silence is not always a virtue?', 'D', 'D says silence can be a failure of courage. C describes silence that turned out to be good, the opposite view.'],
        ['describes silence as something that must be performed with skill?', 'A', 'A says a rest must be played as precisely as any note. C describes learning to be silent, but not as a skill of performance.'],
        ['suggests that quiet should be protected?', 'B', 'B reports the argument that quiet should be protected like clean water. D discusses silence but wants people to speak.'],
        ['describes a change in the writer’s understanding of a silence?', 'C', 'The writer at first felt silence was failing their father, then saw he was content in it. D states a view but describes no change.'],
        ['claims that keeping quiet can favour some people over others?', 'D', 'D says silence takes the side of whoever benefits from nobody speaking. B mentions noise affecting places, not people benefiting.'],
        ['describes how a silence can make what follows more powerful?', 'A', 'The silence before a final chord shapes the sound that follows. C describes a silence, but nothing follows from it in that way.'],
        ['gives evidence that a kind of silence has become rare?', 'B', 'B reports that few places are free of engine noise for more than fifteen minutes. A treats silence as deliberate, not rare.'],
        ['describes communication that happens without words?', 'C', 'The father’s hand over the writer’s says what words cannot. A describes music, not communication between people.'],
        ['compares silence to a natural resource?', 'B', 'B says quiet could be protected as we protect clean water. D compares silence to a choice, not a resource.'],
        ['describes a mistake that is as serious as playing a wrong note?', 'A', 'Rushing a rest ruins the phrase “as surely as” a wrong pitch. D describes failures of courage, not mistakes in performance.'],
      ] }),
  ],

  thinking: [
    TS('strengthen', 'A researcher argues that the decline of a frog species in a national park is caused by a fungus, not by the drought that has affected the park.',
      'Which one of these statements, if true, most strengthens the researcher’s argument?',
      ['The frogs have declined equally in the park’s permanently wet gullies, which the drought did not affect, and in the dry areas.', 'The fungus has been found in other countries.', 'The drought has been the worst in fifty years.', 'Frogs are sensitive to changes in their environment.'], 0,
      'If frogs declined just as much where the drought had no effect, the drought cannot explain the decline, leaving the fungus as the likely cause. The fungus being found in other countries is the nearest rival, but it does not separate fungus from drought in this park.',
      [null, 'this does not separate fungus from drought here', 'this makes drought a stronger rival explanation', 'this fits either explanation']),
    TS('weaken', 'A city claims that its new bicycle lanes have improved residents’ health, because the number of people cycling to work has doubled since the lanes were built, and rates of heart disease have fallen.',
      'Which one of these statements, if true, most weakens the city’s claim?',
      ['Heart disease rates fell by the same amount over the same period in nearby cities that built no bicycle lanes.', 'Cycling is good exercise.', 'Some residents still drive to work.', 'The lanes were expensive to build.'], 0,
      'If heart disease fell just as much in cities without lanes, something else, common to all of them, probably explains the fall. Some residents still driving is the nearest rival, but it does not undermine the link between the lanes and health.',
      [null, 'this supports the claim', 'this does not undermine the link', 'cost does not affect the health claim']),
    WR('In a tournament, each of six teams plays every other team once. A win scores 3 points, a draw 1 point each, and a loss 0. At the end, no two teams have the same number of points.\nNoor: “The team that came last cannot have more than 7 points.”\nFelix: “At least one game in the tournament must have been a draw.”',
      'Noor', 'Felix', true, false,
      'Noor is right: there are 15 games, worth at most 45 points in total. If the last team had 8 or more, the six different totals would be at least 8 + 9 + 10 + 11 + 12 + 13 = 63, which is impossible. Felix is wrong: with no draws, every total is a multiple of 3, and six different totals such as 0, 3, 6, 9, 12 and 15 add up to exactly 45, so a tournament with no draws is possible.'),
    TS('flaw', 'Leon argues: “In surveys, people who say they eat breakfast every day also report being happier. Therefore, to make people happier, the government should provide free breakfasts.”',
      'Which one of the following best identifies the flaw in Leon’s argument?',
      ['It assumes that eating breakfast causes happiness, when happier people may simply be more likely to eat breakfast, or both may result from something else.', 'It ignores the cost of providing free breakfasts.', 'Surveys can include people who are not telling the truth.', 'Some people do not like breakfast foods.'], 0,
      'A link between two things does not show which causes which; a third factor, such as a settled home life, might cause both. Ignoring the cost is the nearest rival: it is a weakness of the policy, but not the flaw in the reasoning from the survey.',
      [null, 'this is a weakness of the policy, not the reasoning flaw', 'this questions the data, not the reasoning', 'taste is irrelevant']),
    TS('assumption', 'A town planner argues: “Building a second bridge across the river will end the traffic jams in the town centre, because all the traffic will no longer have to use the one bridge.”',
      'Which one of the following is an assumption the planner’s argument depends on?',
      ['The new bridge will not simply attract extra traffic that fills both bridges.', 'Bridges are expensive to build.', 'The river is wide.', 'Most people in the town own cars.'], 0,
      'If a new bridge encourages more people to drive, both bridges may fill up and the jams return; the argument assumes this will not happen. Most people owning cars is the nearest rival, but the argument does not depend on it.',
      [null, 'cost is not part of the argument', 'width is irrelevant', 'the argument does not depend on car ownership']),
    TS('weaken', 'Over the past decade, the number of books borrowed from the town library has fallen by forty per cent. The council concludes that people in the town are reading much less than they used to.',
      'Which one of these statements, if true, most weakens the council’s conclusion?',
      ['Over the same decade, the library’s e-book loans, which are not included in the borrowing figures, have grown enormously.', 'The library has reduced its opening hours.', 'Book prices have risen.', 'Many people read newspapers online.'], 0,
      'If e-book loans have grown and are not counted, people may be reading as much as ever, just in a different form. Reduced opening hours is the nearest rival: it explains fewer loans, but people might then read less, so it does not undermine the conclusion as directly.',
      [null, 'this explains fewer loans but does not show reading has not fallen', 'higher prices would, if anything, push people towards libraries', 'newspapers are a different kind of reading']),
    WR('A box contains red, blue and green counters only. There are more red counters than blue counters, and more blue counters than green counters. There are 12 counters in total.\nIsabel: “There must be at least 5 red counters.”\nJonah: “There cannot be more than 3 green counters.”',
      'Isabel', 'Jonah', true, true,
      'Both are right. With red > blue > green and a total of 12: if red were 4 or fewer, blue would be at most 3 and green at most 2, totalling at most 9. So red is at least 5. If green were 4 or more, blue would be at least 5 and red at least 6, totalling at least 15. So green is at most 3.'),
    TS('strengthen', 'A historian argues that a medieval village was abandoned because of flooding rather than disease.',
      'Which one of these statements, if true, most strengthens the historian’s argument?',
      ['Layers of river silt cover the village’s final floors, and the village graveyard shows no rise in burials in its last years.', 'Many medieval villages were abandoned.', 'Diseases spread quickly in the Middle Ages.', 'The village was near a river.'], 0,
      'Silt over the last floors points to flooding, and no rise in burials argues against a deadly disease. The village being near a river is the nearest rival, but it shows only that flooding was possible.',
      [null, 'this is general, not about this village', 'this supports the rival explanation', 'this shows only that flooding was possible']),
    TS('flaw', 'A company argues: “Our survey asked customers who had renewed their subscriptions whether they were satisfied, and 95% said yes. So almost all our customers are satisfied.”',
      'Which one of the following best identifies the flaw?',
      ['It surveyed only customers who renewed, ignoring those who left, who are more likely to be dissatisfied.', 'Ninety-five per cent is not all customers.', 'Satisfied customers may still complain.', 'The survey might have been too long.'], 0,
      'Customers who renewed are those most likely to be satisfied; the ones who left are missing. That 95% is not all is the nearest rival, but the company only claims “almost all”.',
      [null, 'the company only claims “almost all”', 'this does not identify the flaw', 'survey length is not the flaw']),
    TS('conclusion', 'Every member of the orchestra plays at least one string instrument or one wind instrument. No member plays both a string and a wind instrument. Everyone who plays a wind instrument also plays in the marching band. Ellie is in the orchestra but not in the marching band.',
      'Which one of the following must be true?',
      ['Ellie plays a string instrument.', 'Ellie plays a wind instrument.', 'Ellie plays no instrument.', 'Everyone in the marching band plays a wind instrument.'], 0,
      'If Ellie played a wind instrument she would be in the marching band, which she is not. As an orchestra member she must play a string or wind instrument, so she plays a string instrument. The last option reverses the rule about the marching band.',
      [null, 'wind players are all in the marching band', 'every member plays something', 'this reverses the rule']),
    WR('A survey asked 100 students whether they liked maths and whether they liked science. 70 said they liked maths and 60 said they liked science.\nGrace: “At least 40 students must like both subjects.”\nOwen: “At most 60 students can like both subjects.”',
      'Grace', 'Owen', false, true,
      'Owen is right: no more than the 60 who like science can like both. Grace is wrong: 70 + 60 = 130 is only 30 more than the 100 students, so as few as 30 might like both.'),
    TS('weaken', 'Ana argues: “Students who learn a second language score higher on problem-solving tests. So learning a second language improves problem-solving.”',
      'Which one of these statements, if true, most weakens Ana’s argument?',
      ['In the schools studied, only students who already had high problem-solving scores were allowed to take language classes.', 'Learning a language takes many years.', 'Some languages are harder than others.', 'Problem-solving is important in many jobs.'], 0,
      'If only students with high scores were allowed into language classes, the higher scores came first and cannot be caused by the language. Some languages being harder is the nearest rival, but it does not touch the cause.',
      [null, 'time taken does not affect the cause', 'this does not touch the cause', 'this does not affect the argument']),
    TS('assumption', 'A critic writes: “This new novel will win the national prize. It is the longest, most ambitious book published this year.”',
      'Which one of the following is an assumption the critic has made?',
      ['The judges reward length and ambition above other qualities.', 'The novel has been well reviewed.', 'The author has won prizes before.', 'Many novels were published this year.'], 0,
      'The critic moves from “longest and most ambitious” to “will win”, which only works if those are the qualities the judges reward. Good reviews is the nearest rival, but the critic’s reasoning does not mention reviews.',
      [null, 'the reasoning does not mention reviews', 'past prizes are not part of the reasoning', 'the number of novels is not part of the reasoning']),
    TS('strengthen', 'An ecologist claims that removing feral cats from an island allowed a ground-nesting bird population to recover.',
      'Which one of these statements, if true, most strengthens the ecologist’s claim?',
      ['On a similar nearby island where cats were not removed, the same bird species continued to decline over the same period.', 'Feral cats are found on many islands.', 'The bird lays its eggs on the ground.', 'The island is a nature reserve.'], 0,
      'A similar island without cat removal, where the birds kept declining, shows the removal made the difference. The bird laying eggs on the ground is the nearest rival: it explains why cats would be a threat, but not that removal caused the recovery.',
      [null, 'this is general, not evidence', 'this explains the threat but not the recovery', 'reserve status does not show the cause']),
    WR('Five runners finished a race with no ties. Rosa finished ahead of Sam but behind Tia. Uma finished immediately behind Sam. Vic was not last.\nKaren: “Rosa must have finished second or third.”\nLeo: “Vic must have finished first.”',
      'Karen', 'Leo', true, false,
      'Karen is right. Tia, Rosa, Sam and Uma finish in that order, with Uma straight after Sam. Vic is not last, so Uma is last, and Vic is first, between Tia and Rosa, or between Rosa and Sam. In every case Rosa is second or third. Leo is wrong: Vic could be second or third.'),
    TS('flaw', 'A politician says: “My opponent has changed her position on the new highway twice in the past year. Someone who cannot make up her mind should not be trusted with decisions.”',
      'Which one of the following best identifies the flaw in the politician’s argument?',
      ['Changing a position may reflect good judgement in response to new information, not an inability to decide.', 'The politician may also have changed position.', 'Highways are expensive.', 'Voters may not care about the highway.'], 0,
      'The argument treats any change of mind as weakness, ignoring that new evidence can make changing one’s view the sensible thing to do. The politician also having changed position is the nearest rival: it would be hypocrisy, but it does not identify the flaw in the reasoning itself.',
      [null, 'this is about hypocrisy, not the reasoning flaw', 'cost is irrelevant', 'voters’ interest is irrelevant']),
  ],

  writing: {
    title: 'Two letters', genre: 'narrative',
    stimulus: ['A letter is written but never sent.', 'Years later, someone finds it.'],
    prompt: 'Write a story about the letter, told entirely from the point of view of the person who finds it. You must not quote the whole letter.',
    guidance: ['Decide who wrote the letter, who it was for, and why it was never sent — but let the reader piece this together.', 'Quote only a line or two of the letter; let the finder’s reactions do the rest.', 'Make the ending a decision the finder makes.'],
    rubricNotes: 'A strong response keeps strictly to the finder’s point of view, reveals the letter’s story through hints and reactions rather than explanation, and ends with a choice that grows out of what the finder has learned.',
  },
});
