/* Hard Exam 2 — original content written for this site. Pitched well above the real test. */
'use strict';
defExam('H02', {
  reading: [
    readS1({ id: 'H02-s1', headnote: 'Two writers consider failure. Extract A is from a memoir by a scientist; Extract B is from an essay about sport.',
      extracts: [
        { label: 'Extract A', paras: [
          'For three years my experiment did not work. I do not mean that it gave disappointing results; I mean that it gave no results at all, or results so contradictory that they amounted to the same thing. I rebuilt the apparatus twice. I checked every calculation until I could recite them in my sleep, and sometimes did.',
          'What I could not have explained to anyone outside the laboratory — and what I struggled to explain to myself — is that those three years were not wasted. By the time the experiment finally worked, I understood every way in which it could go wrong, because I had watched it go wrong in all of them. The successful result took an afternoon. It was the failures that had taught me how to recognise it.',
          'My supervisor, when I showed him, looked at the graph for a long time and then said only, “Good. Now do it again.” I was furious for about a week. He was, of course, right: a result that cannot be repeated is not a result but an anecdote.',
        ] },
        { label: 'Extract B', paras: [
          'Commentators like to say that great athletes are defined by how they respond to defeat, and there is truth in the cliché. But it hides a more uncomfortable fact: most athletes, most of the time, lose. In any race with eight finalists, seven go home without the gold. A career in sport is, statistically, a long apprenticeship in not winning.',
          'The athletes who last are not those who learn to love losing — nobody does — but those who learn to separate the result from the performance. A swimmer can swim the race of her life and finish fourth; another can win with a poor swim in a weak field. Judging yourself by the scoreboard alone is a recipe for either despair or complacency, and often for both in turn.',
        ] },
      ],
      questions: [
        Q('Why does the writer of Extract A distinguish between “disappointing results” and “no results at all”?', ['To show that the problem was more serious than ordinary disappointment.', 'To suggest the experiment was poorly designed.', 'To show that the writer was exaggerating.', 'To explain why the supervisor was angry.'], 0,
          'Disappointing results would at least be something; the writer had nothing usable, which is worse. Poor design is the nearest rival: it might be true, but the distinction is about the scale of the failure, not its cause.',
          [null, 'the distinction is about scale, not cause', 'the writer is being exact, not exaggerating', 'the supervisor is never angry']),
        Q('What is the effect of the phrase “and sometimes did” (end of the first paragraph)?', ['It adds a touch of humour and shows how consuming the work was.', 'It shows the writer was not sleeping at all.', 'It suggests the calculations were wrong.', 'It shows the writer was proud of the calculations.'], 0,
          'Reciting calculations in one’s sleep is a wry joke that shows the work filled every hour. Not sleeping at all is the nearest rival, but the joke depends on the writer sleeping.',
          [null, 'the joke depends on the writer sleeping', 'the writer checked them repeatedly', 'pride is not suggested']),
        Q('According to Extract A, why were the three years “not wasted”?', ['They produced several smaller results.', 'They taught the writer every way the experiment could fail, so success could be recognised.', 'They gave the writer time to write a book.', 'They impressed the supervisor.'], 1,
          'Watching it fail “in all of them” taught the writer how to recognise a true result. Impressing the supervisor is the nearest rival, but he responds only with “Now do it again.”',
          ['the writer says there were no results', null, 'no book is mentioned', 'the supervisor simply asks for a repeat']),
        Q('What does the supervisor’s response reveal?', ['He did not believe the result.', 'He valued a result only if it could be repeated.', 'He was not interested in the experiment.', 'He wanted the writer to change topics.'], 1,
          'The writer later sees he was right: “a result that cannot be repeated is not a result but an anecdote.” Not believing the result is the nearest rival, but he says “Good”: he wants confirmation, not rejection.',
          ['he says “Good”: he wants confirmation, not rejection', null, 'he studies the graph for a long time', 'he asks for the same experiment']),
        Q('What does the writer of Extract B mean by calling a sports career “a long apprenticeship in not winning”?', ['Athletes should train for longer.', 'Losing is the normal experience of most athletes, and they must learn to deal with it.', 'Athletes should stop competing if they do not win.', 'Coaches teach athletes how to lose.'], 1,
          'Since most athletes lose most of the time, a career is mostly spent learning to live with not winning. Coaches teaching athletes how to lose is the nearest rival, but the phrase is about experience, not instruction.',
          ['the length of training is not the point', null, 'the writer argues for the opposite', 'the phrase is about experience, not instruction']),
        Q('According to Extract B, what distinguishes the athletes who last?', ['They learn to enjoy losing.', 'They judge their performance separately from the result.', 'They only enter weak fields.', 'They ignore the scoreboard completely.'], 1,
          'Those who last “learn to separate the result from the performance”. Ignoring the scoreboard completely is the nearest rival, but the writer warns against judging by the scoreboard alone, not against looking at it at all.',
          ['the writer says nobody loves losing', null, 'winning a weak field is given as a poor guide', 'the warning is against the scoreboard alone']),
        Q('Why does the writer of Extract B say judging by the scoreboard leads to “despair or complacency, and often for both in turn”?', ['Because results go up and down regardless of performance, so feelings swing with them.', 'Because athletes are naturally moody.', 'Because coaches criticise losers.', 'Because scoreboards are often wrong.'], 0,
          'A great swim can come fourth and a poor swim can win, so feelings based only on results swing between despair and complacency. Scoreboards being wrong is the nearest rival, but the scoreboard is accurate; it just does not measure performance.',
          [null, 'the writer does not say athletes are moody', 'coaches are not mentioned', 'the scoreboard is accurate; it just measures the wrong thing']),
        Q('Which idea do both extracts share?', ['Failure can be valuable if it is understood correctly.', 'Science is harder than sport.', 'Supervisors and coaches are always right.', 'Winning is all that matters.'], 0,
          'A finds three failed years were what made success possible; B argues athletes must learn from losing without being defined by it. Supervisors and coaches always being right is the nearest rival, but B does not mention coaches.',
          [null, 'neither extract compares the two', 'B does not mention coaches', 'both extracts argue against this']),
      ] }),

    readS2({ id: 'H02-s2', title: 'The year without a summer',
      text: 'In April 1815, Mount Tambora, on an island in what is now Indonesia, erupted with a force that dwarfs any volcanic event in recorded history. The explosion was heard more than two thousand kilometres away, and the mountain lost over a kilometre of its height. Tens of thousands of people on the surrounding islands were killed, many not by the eruption itself but by the famine that …(1)….\n\nThe eruption’s effects reached far beyond the region. Enormous quantities of sulphur gas were …(2)… high into the atmosphere, where they formed a fine haze that spread around the globe and reflected some of the Sun’s energy back into space. The following year, 1816, became known in Europe and North America as “the year without a summer”.\n\nIn parts of New England, snow fell in June. In Europe, cold and persistent rain caused harvests to fail across much of the continent, and food prices rose so sharply that riots …(3)… out in several countries. Thousands of families, facing hunger, abandoned their farms and …(4)… in search of better land.\n\nAt the time, nobody connected the misery with a volcano on the other side of the world; the link was only established by scientists in the twentieth century. Yet the effects of the cold summer have been traced in surprising places. A group of writers, kept indoors by the …(5)… rain at a villa near Geneva, held a contest to write ghost stories, and one of them, Mary Shelley, began the novel that became Frankenstein. Some historians have suggested that the …(6)… sunsets of those years, coloured by the haze, are visible in paintings of the period.\n\nTambora is a reminder that the climate can change abruptly, and that societies with little food in …(7)… are the most vulnerable when it does. A similar eruption today would affect a world far more crowded, but far better able to …(8)… what is coming.',
      gaps: [
        [['followed', 'preceded', 'prevented', 'ended'], 0, 'Many died from the famine that “followed” the eruption. Preceded is the opposite: the famine came after.', [null, 'the famine came after the eruption', 'the famine was not prevented', 'the famine was caused, not ended']],
        [['hurled', 'buried', 'gathered', 'released'], 0, 'The force of the eruption “hurled” the gas high into the atmosphere. Released is the nearest rival, but it does not convey the violence needed to reach that height; “hurled” fits the sentence’s emphasis on force.', [null, 'gas cannot be buried high up', 'gathering does not describe an eruption', 'released does not convey the force needed to reach that height']],
        [['broke', 'carried', 'kept', 'died'], 0, 'Riots “broke out”. The other verbs do not form a phrase with “out” meaning to start suddenly.', [null, '“carried out” means performed', '“kept out” means excluded', '“died out” means faded away']],
        [['migrated', 'returned', 'rested', 'surrendered'], 0, 'Families who abandoned their farms “migrated in search of better land”. Returned is the nearest rival, but they were leaving, not going back.', [null, 'they were leaving, not going back', 'resting does not fit abandoning farms', 'surrendering makes no sense']],
        [['incessant', 'refreshing', 'occasional', 'gentle'], 0, 'Rain that kept the writers indoors was “incessant” — continual. Occasional is the opposite of what would keep people indoors.', [null, 'refreshing does not fit the misery described', 'occasional rain would not keep them indoors', 'gentle does not fit the persistent rain described']],
        [['vivid', 'dull', 'brief', 'ordinary'], 0, 'Haze in the atmosphere produced unusually “vivid” sunsets. Dull is the opposite of what would stand out in paintings.', [null, 'dull sunsets would not be noticed in paintings', 'length is not the point', 'ordinary sunsets would not be remarkable']],
        [['reserve', 'season', 'demand', 'motion'], 0, 'Societies with little food “in reserve” are most vulnerable. Season is the nearest rival, but “in season” describes freshness, not stored supplies.', [null, '“in season” is about freshness, not stores', '“in demand” is about wanting, not having', '“in motion” makes no sense']],
        [['anticipate', 'ignore', 'cause', 'remember'], 0, 'Today’s world is better able to “anticipate” — foresee and prepare for — a volcanic winter. Remember is the nearest rival, but you cannot remember what is coming.', [null, 'ignoring would not be an ability', 'we would not cause an eruption', 'you cannot remember what is coming']],
      ] }),

    readS3({ id: 'H02-s3', headnote: 'This poem is a sonnet about a pair of old garden gloves.', title: 'Gloves',
      lines: [
        'They hang beside the door, still shaped to hold',
        'the handle of a spade she used to use;',
        'the left thumb split, the right one patched with gold',
        'embroidery thread — she never liked to lose',
        '',
        'a thing that might be mended. In the fold',
        'of every finger, soil she couldn’t choose',
        'to wash away. They’re stiff now. They are cold.',
        'They keep the curve of what they can’t refuse:',
        '',
        'her grip, the shape of work. I could put them on.',
        'I’ve thought of it. I think they’d nearly fit.',
        'But then the shape would change, and she’d be gone',
        'a little further. So I leave them, lit',
        '',
        'by morning through the screen door, holding still',
        'the handle of a spade they never will.',
      ],
      questions: [
        Q('What do the gloves being “still shaped to hold / the handle of a spade” suggest?', ['They were made for a particular spade.', 'They have kept the shape of the work and the person who wore them.', 'They are too stiff to be useful.', 'Someone is about to use them.'], 1,
          'Worn for years, they have taken the shape of her grip, keeping a trace of her. Too stiff to be useful is the nearest rival, but the stiffness is mentioned later and the point here is what they remember.',
          ['they were shaped by use, not made that way', null, 'the point here is what they remember, not usefulness', 'nobody uses them']),
        Q('What does the gold embroidery thread used to patch the glove show about the woman?', ['She was wealthy.', 'She preferred to mend things rather than throw them away.', 'She was a professional tailor.', 'She disliked gardening.'], 1,
          'She “never liked to lose / a thing that might be mended”. Being wealthy is the nearest rival, because of the word “gold”, but it is only the colour of the thread.',
          ['“gold” is the colour of the thread, not wealth', null, 'nothing suggests a profession', 'she gardened enough to wear out gloves']),
        Q('What is the effect of the short sentences “They’re stiff now. They are cold.” (line 7)?', ['They create a pause that emphasises the loss of the person who wore them.', 'They describe the weather.', 'They show the speaker is in a hurry.', 'They explain why the gloves are hanging by the door.'], 0,
          'After the warm details of her mending and gardening, the blunt, short sentences stress that she is gone. Describing the weather is the nearest rival, but the coldness is about absence, not temperature.',
          [null, 'the coldness is about absence, not weather', 'the poem is slow and reflective', 'they do not explain where the gloves hang']),
        Q('What does “the curve of what they can’t refuse” (line 8) most likely refer to?', ['The shape of the woman’s grip and her habit of work.', 'The weather outside.', 'The speaker’s wish to throw them away.', 'The door they hang beside.'], 0,
          'The next line explains it: “her grip, the shape of work”. The door is the nearest rival, as the gloves hang beside it, but the curve is the shape inside the gloves.',
          [null, 'the weather is not the subject here', 'the speaker wants to keep them', 'the curve is the shape inside the gloves']),
        Q('Why does the speaker decide not to wear the gloves?', ['They are too small.', 'Wearing them would change their shape and lose the trace of the woman.', 'They are too dirty.', 'The speaker does not garden.'], 1,
          '“The shape would change, and she’d be gone / a little further.” Being too small is the nearest rival, but the speaker thinks “they’d nearly fit”.',
          ['the speaker thinks they would nearly fit', null, 'the soil is treasured, not a problem', 'gardening ability is not the reason']),
        Q('What is the effect of the final couplet?', ['It suggests the gloves will be used again soon.', 'It closes the poem on an image of the gloves holding an absence that will never be filled.', 'It shows the speaker has moved on.', 'It describes the spade in detail.'], 1,
          'The gloves hold “the handle of a spade they never will”: an image of permanent absence. Being used again soon is the opposite of “never will”.',
          ['the couplet says they never will', null, 'the speaker is still holding on', 'the spade itself is not described']),
      ] }),

    readS4({ id: 'H02-s4', title: 'The resistance problem',
      paras: [
        'When penicillin came into use in the 1940s, it seemed to end the threat of bacterial infection. Wounds and illnesses that had killed millions could suddenly be cured within days. ...(1)...',
        'Antibiotics work by attacking structures or processes that bacteria need to survive. ...(2)... By chance, a few may carry a genetic difference that lets them survive, and those few go on to multiply.',
        'Every use of an antibiotic therefore applies a kind of selection. ...(3)... Bacteria can also pass resistance genes directly to one another, even between different species, so that resistance can spread far faster than it would by inheritance alone.',
        'Human behaviour has made the problem worse. ...(4)... In many countries, too, large quantities of antibiotics have been given to farm animals, not to treat disease but to make them grow faster.',
        'The consequences are already serious. ...(5)... Some researchers warn that, without action, routine operations and minor injuries could once again become dangerous.',
        '...(6)... It requires using existing drugs only when they are truly needed, developing new ones, and improving hygiene so that fewer infections occur in the first place.',
      ],
      sentences: [
        'Within a few years, however, doctors were already reporting strains of bacteria that it could not kill.',
        'But in any large population of bacteria, the individuals are not all identical.',
        'Susceptible bacteria die, while resistant ones survive and become more common.',
        'Antibiotics are often prescribed for viral illnesses, against which they are useless, and patients sometimes stop taking them as soon as they feel better.',
        'Infections that were once easily treated now sometimes require drugs of last resort, and some respond to nothing at all.',
        'There is no single solution to the problem.',
        'Penicillin was discovered by accident in a laboratory.',
      ],
      answers: [0, 1, 2, 3, 4, 5],
      explains: [
        'After describing penicillin’s early success, the gap introduces the problem that the passage is about, beginning with “however”.',
        '“By chance, a few may carry a genetic difference” needs a sentence before it saying bacteria are not all identical.',
        '“A kind of selection” is explained by susceptible bacteria dying and resistant ones becoming more common.',
        '“Human behaviour has made the problem worse” is followed by misuse in medicine; “In many countries, too” then adds misuse in farming.',
        '“The consequences are already serious” is backed by infections needing last-resort drugs or responding to nothing.',
        'The final paragraph lists several measures, so it opens by saying there is no single solution. The sentence about penicillin’s accidental discovery is the extra one.',
      ] }),

    readS5({ id: 'H02-s5', headnote: 'Four writers discuss the idea of home.',
      extracts: [
        { title: 'Extract A', paras: ['I have lived in eleven houses in four countries, and I have stopped expecting any of them to feel like home on the day I move in. Home, for me, arrives later and by accident: the first time I find a light switch in the dark without looking, or hear the particular complaint of a floorboard and know which one it is. It is not a place but a set of habits a place allows.'] },
        { title: 'Extract B', paras: ['Housing has become so expensive in many cities that young adults now leave their parents’ homes much later than previous generations did. Some economists argue this is simply a sensible response to prices. Others worry about the effects of delaying independence, though the evidence on this is mixed, and in many cultures living with parents into adulthood has always been the norm.'] },
        { title: 'Extract C', paras: ['When people say “home is where the heart is”, they usually mean it kindly, but the phrase can be cruel. For a refugee, home may be a place that no longer exists, or one that they can never safely return to. To tell them that home is wherever they happen to be is to ask them to give up a loss they are entitled to feel.'] },
        { title: 'Extract D', paras: ['The house I grew up in was sold when I was twenty. I drove past it last year. Someone had painted the front door blue and cut down the lemon tree, and I was astonished by how angry I felt, as if they had no right to change what I had not lived in for decades. Then I laughed at myself, and drove on, and found I was still a little angry.'] },
      ],
      items: [
        ['describes home as something built up through small, familiar habits?', 'A', 'A says home is “a set of habits a place allows”, such as finding a switch without looking. D describes a childhood house, but as a memory, not habits.'],
        ['reports that experts disagree?', 'B', 'B says some economists see late home-leaving as sensible while others worry. C argues one view firmly.'],
        ['argues that a well-meant saying can be hurtful?', 'C', 'C says “home is where the heart is” can be cruel to refugees. A gives a personal definition of home without criticising any saying.'],
        ['describes a feeling the writer recognises as unreasonable but cannot quite shake?', 'D', 'The writer laughs at their own anger but is “still a little angry”. A describes changing expectations, but no lingering unreasonable feeling.'],
        ['suggests that what is normal differs between cultures?', 'B', 'B notes that living with parents into adulthood has always been the norm in many cultures. C mentions refugees, but not differences between cultures.'],
        ['mentions a place that may no longer exist?', 'C', 'C says a refugee’s home may be a place that no longer exists. D’s house still stands, though it has changed.'],
        ['describes changes made to a house by later owners?', 'D', 'The blue door and the lost lemon tree were changes made by new owners. A mentions eleven houses but not changes by others.'],
        ['claims that feeling at home comes only after time has passed?', 'A', 'A says home “arrives later and by accident”. B discusses timing, but of leaving home, not of feeling at home.'],
        ['defends a person’s right to grieve?', 'C', 'C says refugees are entitled to feel their loss. D describes the writer’s own feeling, but does not defend a right.'],
        ['notes that the evidence on a question is uncertain?', 'B', 'B says “the evidence on this is mixed”. C states its view without discussing evidence.'],
      ] }),
  ],

  thinking: [
    TS('strengthen', 'A school found that students who attended its optional morning maths club improved their results more than students who did not attend. The principal concludes that the club caused the improvement.',
      'Which one of these statements, if true, most strengthens the principal’s conclusion?',
      ['Places in the club were allocated by lottery among students who applied, and applicants who missed out improved no more than students who never applied.', 'The club is run by the school’s most experienced maths teacher.', 'Students who attend the club say they enjoy it.', 'The club meets three mornings a week.'], 0,
      'A lottery among applicants means the club and non-club groups were alike in motivation; if unlucky applicants did not improve, the club itself made the difference. The experienced teacher is the nearest rival: it suggests why the club might work, but it does not rule out keener students simply choosing to attend.',
      [null, 'this suggests why it might work but does not rule out self-selection', 'enjoyment does not show improvement was caused by the club', 'frequency does not show causation']),
    TS('weaken', 'A health campaign argues: “Since our advertisements began, the number of people who report exercising regularly has risen by thirty per cent. The campaign has made people more active.”',
      'Which one of these statements, if true, most weakens the argument?',
      ['Studies show that after such campaigns, people become more likely to say they exercise, even when devices that track activity show no change.', 'The advertisements were shown on television and online.', 'Regular exercise has many health benefits.', 'The campaign cost several million dollars.'], 0,
      'If people tend to over-report exercise after a campaign while measured activity stays the same, the rise in reports may not reflect any real change. The cost is the nearest rival, but cost does not tell us whether the campaign worked.',
      [null, 'where it was shown does not affect the argument', 'this does not affect whether the campaign worked', 'cost does not tell us whether it worked']),
    WR('A group of 30 students each chose exactly one sport: cricket, tennis or swimming. More students chose cricket than tennis, and more chose tennis than swimming. At least one student chose swimming.\nMaddie: “At least 11 students chose cricket.”\nRaj: “At most 9 students chose swimming.”',
      'Maddie', 'Raj', true, true,
      'Both are right. If cricket had 10 or fewer, tennis would be at most 9 and swimming at most 8, totalling at most 27, not 30. So cricket has at least 11. If swimming had 10 or more, tennis would be at least 11 and cricket at least 12, totalling at least 33. So swimming has at most 9.'),
    TS('flaw', 'An editorial argues: “Most successful business owners left school early. Clearly, staying at school does not help people succeed in business.”',
      'Which one of the following best identifies the flaw in the argument?',
      ['It considers only successful business owners, ignoring the many people who left school early and did not succeed.', 'It does not define “success”.', 'Some business owners went to university.', 'It does not say how early they left.'], 0,
      'Looking only at the successful ignores the much larger number who left early and failed; the pattern among winners says little about the effect of leaving. Not defining success is the nearest rival: it is a real weakness, but the central flaw is that the failures are left out.',
      [null, 'this is a weakness, but the central flaw is that the failures are left out', 'this does not identify the flaw', 'this does not identify the flaw']),
    TS('assumption', 'A scientist argues: “The bird species disappeared from the island at the same time that rats arrived on ships. So rats must have caused the birds’ extinction, and removing rats from other islands will protect similar birds.”',
      'Which one of the following is an assumption required by the second part of the argument?',
      ['The birds on other islands are threatened by rats in the same way as the extinct species was.', 'Rats arrived on the island on ships.', 'The extinct birds nested on the ground.', 'Rats are found on many islands.'], 0,
      'Removing rats elsewhere will only protect “similar birds” if rats threaten those birds in the same way. That rats arrived on ships is the nearest rival, but it is stated in the argument, not assumed.',
      [null, 'this is stated in the argument', 'nesting habits are not mentioned in the argument', 'this is not needed for the conclusion']),
    TS('weaken', 'A researcher found that children who own more books at home do better at reading. She recommended that the government give books to families with few books, to improve children’s reading.',
      'Which one of these statements, if true, most weakens the recommendation?',
      ['In families who were given books in a previous trial, the books were mostly left unread, and children’s reading did not improve.', 'Books are cheaper than they used to be.', 'Some children prefer reading on screens.', 'Libraries also lend books.'], 0,
      'If giving books did not improve reading in a trial, the link between owning books and reading may come from something else, such as parents who read. Libraries lending books is the nearest rival: it suggests an alternative source, but not that the plan would fail.',
      [null, 'cheaper books make the plan easier', 'this weakens the plan only a little', 'this does not show the plan would fail']),
    WR('In a code, every letter of a word is replaced by the letter that comes a fixed number of places later in the alphabet, wrapping round from Z to A. In this code, CAT becomes FDW.\nTessa: “In this code, ZOO becomes BQQ.”\nGabe: “If a coded word is HDW, the original word was EAT.”',
      'Tessa', 'Gabe', false, true,
      'Gabe is right: CAT becoming FDW shows every letter moves 3 places, and moving H, D and W back 3 places gives E, A and T. Tessa is wrong: moving Z, O and O forward 3 places gives CRR, not BQQ.'),
    TS('strengthen', 'A historian claims that a famous letter, supposedly written in 1850, is a forgery made many years later.',
      'Which one of these statements, if true, most strengthens the historian’s claim?',
      ['The letter is written on a type of paper that was first manufactured in 1890.', 'The letter’s handwriting is neat.', 'The letter was found in an attic.', 'The letter mentions events from the 1840s.'], 0,
      'Paper first made in 1890 cannot have been used in 1850, so the letter must have been written later. Mentioning events from the 1840s is the nearest rival, but a genuine letter of 1850 would do that too.',
      [null, 'neatness does not show forgery', 'where it was found does not show forgery', 'a genuine letter of 1850 would do this too']),
    TS('flaw', 'A councillor says: “Either we build the new car park, or the town centre will die. We cannot let the town centre die. So we must build the car park.”',
      'Which one of the following best identifies the flaw?',
      ['It presents only two options when there may be other ways to keep the town centre alive.', 'It does not say how much the car park would cost.', 'It assumes people like the town centre.', 'It does not say where the car park would be built.'], 0,
      'The argument offers a false choice between the car park and a dying centre, ignoring other possibilities such as better public transport. Not mentioning cost is the nearest rival: it is a gap in information, not the logical flaw.',
      [null, 'a missing cost is a gap, not the logical flaw', 'this is not the flaw', 'location is not the flaw']),
    TS('conclusion', 'At a school, every student who studies Japanese also studies music. Some students who study music do not study art. No student who studies art studies Japanese. Ming studies art.',
      'Which one of the following must be true?',
      ['Ming does not study Japanese.', 'Ming does not study music.', 'Ming studies music.', 'Every student who studies music studies Japanese.'], 0,
      'No art student studies Japanese, and Ming studies art, so Ming does not study Japanese. Whether Ming studies music cannot be worked out: some music students study art and some do not.',
      [null, 'this cannot be worked out', 'this cannot be worked out', 'this reverses the first rule']),
    WR('A bag contains 4 red, 3 blue and 2 green marbles. Marbles are taken out one at a time without looking and are not put back.\nUma: “To be certain of getting two marbles of the same colour, you must take out at least 4 marbles.”\nViktor: “Taking out 7 marbles is enough to be certain of getting a green one.”',
      'Uma', 'Viktor', true, false,
      'Uma is right: with three colours, the first three marbles could all be different, so the fourth is needed to be certain of a pair. Viktor is wrong: all 4 red and 3 blue marbles could come out first, so 7 marbles might contain no green.'),
    TS('weaken', 'An economist argues: “When the price of public transport was cut by half last year, the number of passengers rose by only five per cent. So price is not important to people deciding whether to use public transport.”',
      'Which one of these statements, if true, most weakens the economist’s argument?',
      ['During the same year, many bus routes were cut and services became much less frequent.', 'Public transport is cheaper than driving.', 'Some passengers travel every day.', 'The price cut was popular with voters.'], 0,
      'If services were cut at the same time, the price cut may have attracted many new passengers while worse services drove others away, hiding the effect of price. Public transport being cheaper than driving is the nearest rival, but it does not explain the small rise.',
      [null, 'this does not explain the small rise', 'regular passengers do not affect the argument', 'popularity does not affect the argument']),
    TS('assumption', 'A coach says: “Our team lost because our captain was injured. With her back next week, we will win.”',
      'Which one of the following is an assumption required by the coach’s conclusion?',
      ['Nothing else that contributed to the loss, such as a stronger opponent, will still be a problem next week.', 'The captain was injured during the game.', 'The team has won before.', 'The captain is the best player.'], 0,
      'Concluding that the team will win next week requires that no other cause of the loss remains, such as next week’s opponent also being strong. The captain being the best player is the nearest rival: it may be true, but the conclusion does not depend on it.',
      [null, 'when she was injured is irrelevant', 'past wins are not required', 'the conclusion does not depend on this']),
    TS('strengthen', 'A biologist claims that a species of lizard on an island has evolved longer legs over the past thirty years because new, taller plants have made climbing more common.',
      'Which one of these statements, if true, most strengthens the biologist’s claim?',
      ['On nearby islands where the taller plants did not spread, lizards of the same species have not developed longer legs.', 'Lizards can live for several years.', 'The island is warm all year.', 'Some lizards can change colour.'], 0,
      'If lizards without the taller plants did not change, the plants are linked to the longer legs. The island being warm is the nearest rival, but warmth does not distinguish the two groups.',
      [null, 'lifespan does not support the claim', 'warmth does not distinguish the groups', 'colour change is irrelevant']),
    WR('A clock gains exactly 2 minutes every hour. It is set to the correct time at 12:00 noon.\nHolly: “At 6:00 pm the correct time, the clock will show 6:12 pm.”\nSeth: “The clock will next show the correct time again after 12 days.”',
      'Holly', 'Seth', true, false,
      'Holly is right: in 6 hours the clock gains 6 × 2 = 12 minutes, so it shows 6:12 pm. Seth is wrong: the clock shows the correct time again once it has gained a full 12 hours (720 minutes), which takes 720 ÷ 2 = 360 hours, or 15 days.'),
    TS('flaw', 'A student says: “I studied for my history test while listening to music and got my best mark ever. Listening to music must improve my concentration.”',
      'Which one of the following best identifies the flaw?',
      ['A single result could have other explanations, such as the test being easier or the student studying for longer.', 'Some music is distracting.', 'The student may not like history.', 'Music can be expensive.'], 0,
      'One good result, with no comparison, cannot show that music caused it; the test or the study time may explain it. Some music being distracting is the nearest rival, but it is a general claim, not the flaw in this reasoning.',
      [null, 'this is a general claim, not the flaw', 'interest is irrelevant', 'cost is irrelevant']),
  ],

  writing: {
    title: 'Is it ever right to break a rule?', genre: 'discursive',
    stimulus: ['Rules exist to keep people safe and to make life fair.', 'Yet many of the people we admire most are remembered for breaking rules.'],
    prompt: 'Write a discussion of whether it is ever right to break a rule. Use examples from everyday life, history or stories, and reach your own conclusion.',
    guidance: ['Distinguish between different kinds of rules: laws, school rules, family rules, unwritten rules.', 'Consider who decides whether breaking a rule was right, and when.', 'Your conclusion should be a position you can defend, not simply “it depends”.'],
    rubricNotes: 'A strong response draws careful distinctions, uses varied and well-chosen examples, anticipates objections, and reaches a nuanced conclusion that follows from the discussion.',
  },
});
