/* Hard Exam 3 — original content written for this site. Pitched well above the real test. */
'use strict';
defExam('H03', {
  reading: [
    readS1({ id: 'H03-s1', headnote: 'Two writers consider gratitude. Extract A is written in the style of a nineteenth-century novel; Extract B is from a contemporary essay.',
      glossary: [['benefactor', 'a person who gives help, especially money'], ['magnanimous', 'generous in forgiving or giving']],
      extracts: [
        { label: 'Extract A', paras: [
          'When old Mr Pell died and left the whole of his modest fortune to his niece Harriet, the town was unanimous that she had been very lucky, and almost unanimous that she had not deserved it. She had visited him, it was true, every Thursday for nine years; but the town had decided long ago that these visits were a speculation, and nothing that had happened since persuaded it otherwise.',
          'Harriet herself said nothing to correct them. She bought no carriage and no new gowns; she continued to teach the infant class at the parish school; and on Thursdays, from habit or from something less easily named, she still walked the length of the High Street and stood for a minute outside the shuttered house before turning home.',
          'It was only when the will was read in full that a further clause was discovered. Mr Pell had directed that the money pass to Harriet “not as a reward, for she would not accept one, but as a debt repaid, for she gave me nine years of Thursday afternoons, and I was never able to tell her what they were worth.” The town read this, and was, for almost a week, rather quieter than usual.',
        ] },
        { label: 'Extract B', paras: [
          'We usually think of gratitude as a response — something we owe after receiving a gift. But this makes it sound like a bill, settled once and then forgotten, and it hides a stranger truth: the people who give us the most are often the ones least able to see what they have given.',
          'The teacher who once took us seriously, the neighbour who listened, the friend who simply turned up — these people rarely know the size of what they did, because to them it was only Tuesday. Gratitude, at its best, is an attempt to show them the shape of a gift they did not know they were giving. It is not repayment. It is a kind of news.',
        ] },
      ],
      questions: [
        Q('What is the effect of the contrast between “unanimous” and “almost unanimous” in the first sentence?', ['It shows that everyone agreed she was lucky, but a few people doubted she was undeserving.', 'It shows that nobody in town knew Harriet.', 'It shows the town was divided equally.', 'It shows that Harriet agreed with the town.'], 0,
          'The slight change shows complete agreement on her luck, but a small minority who did not think her undeserving. The town being divided equally is the nearest rival, but “almost unanimous” means only a few disagreed.',
          [null, 'they clearly have opinions about her', '“almost unanimous” means only a few disagreed', 'she says nothing to the town']),
        Q('What does the town believe about Harriet’s weekly visits?', ['They were made in the hope of inheriting money.', 'They were made out of pure kindness.', 'They were ordered by the parish.', 'They were too short to matter.'], 0,
          'The town had decided the visits were “a speculation” — an investment in a future reward. Pure kindness is the nearest rival, but that is what the will later suggests, not what the town believes.',
          [null, 'this is what the will suggests, not the town’s view', 'nothing suggests this', 'their length is not criticised']),
        Q('Which detail most strongly suggests that the town’s view of Harriet was wrong?', ['She continued to stand outside Mr Pell’s house on Thursdays after his death.', 'She inherited his fortune.', 'She taught the infant class.', 'She visited for nine years.'], 0,
          'Continuing the Thursday walk after his death, with nothing more to gain, suggests real attachment. Visiting for nine years is the nearest rival, but the town already interpreted those visits as a speculation.',
          [null, 'the inheritance is what the town resents', 'teaching does not relate to the visits', 'the town had already explained this away']),
        Q('What is suggested by the phrase “from habit or from something less easily named”?', ['Her continued visits may come from grief or affection that is hard to put into words.', 'She has forgotten that Mr Pell has died.', 'She is hoping to inherit the house too.', 'She is required to inspect the house.'], 0,
          '“Something less easily named” hints at love or grief. Forgetting he has died is the nearest rival, but she stands outside the “shuttered” house, knowing it is empty.',
          [null, 'she knows the house is shuttered', 'she has already inherited everything', 'nothing requires her to']),
        Q('Why does Mr Pell describe the money as “a debt repaid” rather than “a reward”?', ['He believed he owed her for the value of her company, which she would not have accepted payment for.', 'He had borrowed money from her.', 'He wanted to avoid taxes.', 'He thought she had not deserved it.'], 0,
          'He says she “would not accept” a reward, but he owed her for nine years of Thursdays. Having borrowed money is the nearest rival, but the “debt” is for her time and companionship.',
          [null, 'the “debt” is for her time and companionship', 'nothing suggests this', 'he believes she deserves it']),
        Q('What does the town being “rather quieter than usual” suggest?', ['The town is embarrassed after realising it misjudged Harriet.', 'The town is mourning Mr Pell.', 'The town is angry about the will.', 'The town has lost interest in Harriet.'], 0,
          'Having gossiped about her, the town is silenced by evidence of her genuine kindness. Mourning Mr Pell is the nearest rival, but the quiet follows the reading of the clause about Harriet.',
          [null, 'the quiet follows the clause about Harriet', 'nothing suggests anger', 'the quiet is a reaction, not indifference']),
        Q('In Extract B, what does the writer mean by saying that, to the giver, it “was only Tuesday”?', ['The givers thought their actions were ordinary and unremarkable.', 'The givers only helped on Tuesdays.', 'The givers were too busy to help.', 'The givers forgot who they had helped.'], 0,
          'To the giver, the act was a normal part of an ordinary day. Forgetting who they helped is the nearest rival, but the point is that they did not see the act as significant.',
          [null, 'Tuesday stands for any ordinary day', 'they did help', 'they did not see the act as significant']),
        Q('How does Extract A illustrate the idea in Extract B?', ['Mr Pell tries, through his will, to show Harriet the worth of a gift she gave without knowing its value.', 'Harriet repays Mr Pell’s gift by visiting his house.', 'The town shows gratitude to Harriet.', 'Mr Pell pays a bill he owes the town.'], 0,
          'B says gratitude is “news” telling givers the shape of a gift they did not know they gave — exactly what the will does. Harriet repaying a gift is the nearest rival, but in A it is Mr Pell who expresses gratitude.',
          [null, 'it is Mr Pell who expresses gratitude', 'the town shows no gratitude', 'the town is owed nothing']),
      ] }),

    readS2({ id: 'H03-s2', title: 'Life without the sun',
      text: 'Until 1977, almost every biologist assumed that all life on Earth depended, directly or indirectly, on sunlight. Plants capture the sun’s energy; animals eat plants, or eat animals that eat plants. The deep ocean floor, kilometres below the reach of any light, was thought to be a near-desert, …(1)… only by the slow fall of dead material from above.\n\nThat year, scientists exploring the Galápagos Rift in a small submersible found something that overturned this …(2)…. Around cracks in the sea floor where volcanically heated water gushed out, they found dense communities of life: giant tube worms, clams the size of dinner plates and crabs, all thriving in total darkness.\n\nThe water pouring from these hydrothermal vents is rich in dissolved chemicals, including hydrogen sulfide, which is poisonous to most animals. Certain bacteria, however, can use the energy stored in these chemicals to make food, a process called chemosynthesis. These bacteria form the base of the food web, …(3)… the role that plants play on land.\n\nThe giant tube worms are especially remarkable. As adults, they have no mouth and no gut. Instead, their bodies are packed with bacteria, which the worm supplies with chemicals and oxygen from the water and which, in …(4)…, supply the worm with food.\n\nThe discovery has had consequences far beyond the deep sea. Some scientists now believe life on Earth may have begun at such vents. And because similar chemical conditions may exist in oceans hidden beneath the ice of moons such as Europa and Enceladus, vents have made the search for life elsewhere in the solar system seem far less …(5)….\n\nThe vents themselves are …(6)…. A vent may be active for years or decades and then fall silent, and the community around it dies. How the animals’ larvae find a new vent, sometimes hundreds of kilometres away across the dark ocean floor, remains largely a …(7)….\n\nSome vent sites contain valuable metals, and there is growing commercial interest in mining them. Scientists warn that we risk …(8)… ecosystems we have barely begun to understand.',
      gaps: [
        [['sustained', 'flooded', 'destroyed', 'lit'], 0, 'The deep floor was thought to be “sustained only by the slow fall of dead material”. Lit is the opposite: it is beyond the reach of light.', [null, 'it is already under water', 'the material feeds it', 'it is beyond the reach of light']],
        [['assumption', 'submersible', 'rift', 'experiment'], 0, 'The discovery overturned the “assumption” that all life depends on sunlight. Experiment is the nearest rival, but no experiment was described — only a belief.', [null, 'the submersible did the discovering', 'the rift was where they found it', 'only a belief was described']],
        [['filling', 'reversing', 'refusing', 'copying exactly'], 0, 'Bacteria are “filling the role” that plants play on land. Copying exactly is the nearest rival, but they use a different process, so they are not exact copies.', [null, 'they play the same role, not the reverse', 'they do play the role', 'they use a different process']],
        [['return', 'contrast', 'particular', 'secret'], 0, '“In return” shows the exchange between worm and bacteria. In contrast is the nearest rival, but it would signal a difference, not an exchange.', [null, '“in contrast” signals a difference, not an exchange', '“in particular” does not show exchange', '“in secret” makes no sense']],
        [['far-fetched', 'important', 'expensive', 'urgent'], 0, 'Vents have made the search for life elsewhere seem “far less far-fetched” — more realistic. Important is the nearest rival, but “far less important” would contradict the point.', [null, '“far less important” contradicts the point', 'cost is not the point', 'urgency is not the point']],
        [['temporary', 'permanent', 'shallow', 'cold'], 0, 'Vents are “temporary”: they fall silent after years or decades. Permanent is the opposite.', [null, 'they fall silent', 'they are deep', 'the water is heated']],
        [['mystery', 'certainty', 'danger', 'tradition'], 0, 'How larvae find new vents “remains largely a mystery”. Certainty is the opposite.', [null, 'it is not understood', 'the sentence is about knowledge', 'tradition makes no sense']],
        [['destroying', 'discovering', 'protecting', 'measuring'], 0, 'Mining risks “destroying” ecosystems we barely understand. Discovering is the nearest rival, but scientists are warning of harm.', [null, 'scientists are warning of harm', 'protecting is the opposite of a risk', 'measuring is not a risk']],
      ] }),

    readS3({ id: 'H03-s3', headnote: 'This sonnet describes an old clockmaker at work.', title: 'The Clockmaker',
      lines: [
        'He keeps the hours of half the town in drawers:',
        'a kitchen clock that’s lost its tick, a watch',
        'that stopped the morning someone’s father died',
        'and has been kept, unwound, for forty years.',
        'He does not ask. He lifts the tiny wheels',
        'with tweezers, and he breathes the dust away,',
        'and listens, as a doctor listens, for',
        'the fault that is not always in the spring.',
        'Some things he mends. Some things he gives straight back',
        'and says, “There’s nothing wrong with this,” and means',
        'that time is not the clock’s to keep or lose.',
        'At six he locks the shop. Behind the door,',
        'two hundred clocks, all slightly out of step,',
        'tick on, and argue softly in the dark.',
      ],
      questions: [
        Q('What does “He keeps the hours of half the town in drawers” (line 1) suggest?', ['He holds many people’s clocks, and with them pieces of their lives and memories.', 'He controls what time the town wakes up.', 'He hides clocks he has stolen.', 'He is very disorganised.'], 0,
          'The clocks stand for their owners’ time and memories, such as the watch kept since a father’s death. Controlling the town’s time is the nearest rival, but the line is figurative.',
          [null, 'the line is figurative', 'nothing suggests theft', 'drawers suggest order']),
        Q('Why might the watch have been “kept, unwound, for forty years” (line 4)?', ['Its owner wanted to preserve the moment of a father’s death, refusing to let time move on.', 'Nobody knew how to wind it.', 'It was too valuable to use.', 'The clockmaker forgot about it.'], 0,
          'Leaving it stopped at that morning preserves the moment of loss. The clockmaker forgetting it is the nearest rival, but it has been kept by its owner, not by him.',
          [null, 'the choice to keep it unwound is deliberate', 'value is not suggested', 'its owner kept it']),
        Q('What does “He does not ask” (line 5) reveal about the clockmaker?', ['He respects the private stories behind the clocks.', 'He is rude to customers.', 'He already knows how to fix every clock.', 'He cannot speak.'], 0,
          'He does not pry into why a clock matters to its owner. Already knowing how to fix every clock is the nearest rival, but the line follows the private story of the father’s watch.',
          [null, 'his silence is respectful, not rude', 'the line follows a private story', 'he speaks in line 10']),
        Q('What does the comparison with “a doctor” in lines 7–8 suggest?', ['He diagnoses carefully, knowing a problem may not lie where expected.', 'He is also a doctor.', 'The clocks are alive.', 'He treats clocks roughly.'], 0,
          'Like a doctor, he listens for a hidden fault “not always in the spring”. The clocks being alive is the nearest rival, but the simile describes his manner, not their nature.',
          [null, 'it is a comparison', 'the simile describes his manner', 'he works delicately with tweezers']),
        Q('What does the clockmaker mean when he gives some clocks back saying “There’s nothing wrong with this” (lines 9–11)?', ['The owner’s real problem is not the clock; no repair can control the passing of time or undo loss.', 'He is too lazy to repair them.', 'The clocks are already working perfectly.', 'He wants the owners to buy new clocks.'], 0,
          'He “means / that time is not the clock’s to keep or lose”: the grief or loss lies beyond any repair. The clocks already working perfectly is the nearest rival, but the poem says his words mean something deeper than that.',
          [null, 'he is careful and thoughtful', 'the poem says his words mean something deeper', 'nothing suggests selling']),
        Q('What is the effect of the final image, in which the clocks “argue softly in the dark”?', ['It personifies the clocks, suggesting many separate lives and times that never quite agree.', 'It shows that the clocks are broken and noisy.', 'It shows the clockmaker has failed.', 'It shows that the shop is haunted.'], 0,
          'Two hundred clocks “slightly out of step” suggest many people’s different times, quietly disagreeing. The clocks being broken is the nearest rival, but they “tick on”.',
          [null, 'they “tick on”', 'nothing suggests failure', 'the image is gentle, not ghostly']),
      ] }),

    readS4({ id: 'H03-s4', title: 'The power of a sugar pill',
      paras: [
        'When doctors test a new medicine, they usually give some patients the real drug and others a placebo: a pill that looks identical but contains nothing active. ...(1)... Only if the drug does better than the placebo can it be said to work.',
        'Surprisingly, patients given a placebo often improve. ...(2)... This is known as the placebo effect, and it has been observed for conditions ranging from pain to nausea.',
        'Part of the explanation is expectation. ...(3)... Brain scans have shown that people who believe they have taken a painkiller can release the body’s own natural pain-relieving chemicals.',
        '...(4)... Placebos have little or no effect on the growth of tumours, for example, or on infections. They act mainly on what patients feel, rather than on the underlying disease.',
        'Even the appearance of the treatment matters. ...(5)... Injections, in some studies, have produced stronger effects than pills.',
        'The placebo effect raises difficult questions for doctors. ...(6)... Some researchers are now testing “open-label” placebos, in which patients are told they are taking an inactive pill — and some still report feeling better.',
      ],
      sentences: [
        'Neither the patients nor, usually, the doctors know who receives which.',
        'Some report less pain, better sleep or more energy, even though they have taken nothing that could cause the change.',
        'When we expect to feel better, the brain can produce real physical changes.',
        'Yet the placebo effect has clear limits.',
        'In one study, people rated two placebo pills as more effective than one, and brightly coloured capsules as stronger than plain white tablets.',
        'Is it honest to give a patient a treatment that is known to contain nothing?',
        'Most modern medicines are first tested on animals.',
      ],
      answers: [0, 1, 2, 3, 4, 5],
      explains: [
        'After describing the two groups, the gap adds that nobody knows who has which — important if the comparison is to be fair.',
        '“Patients … often improve” is expanded with examples, before the effect is named.',
        '“Part of the explanation is expectation” is followed by the general idea, then the brain-scan evidence.',
        'The paragraph lists what placebos cannot do, so it opens with “Yet the placebo effect has clear limits.”',
        '“Even the appearance matters” is followed by the pill study, then “Injections … have produced stronger effects”.',
        '“Difficult questions” is followed by the ethical question, which open-label placebos try to answer. The sentence about animal testing is the extra one.',
      ] }),

    readS5({ id: 'H03-s5', headnote: 'Four writers reflect on ambition.',
      extracts: [
        { title: 'Extract A', paras: ['Ambition gets a bad name because we notice it most when it goes wrong — in the politician who will say anything, or the executive who will cut any corner. But nearly everything worth having was built by someone who wanted more than they had. The question is not whether to be ambitious, but what for.'] },
        { title: 'Extract B', paras: ['At sixteen I wanted to be a concert pianist so badly that I practised six hours a day. At nineteen I realised I would never be good enough, and for a year I could not touch a piano. Now I teach children, and play for my own pleasure in the evenings, and I am happier at the instrument than I ever was when it was a ladder.'] },
        { title: 'Extract C', paras: ['Research on goal-setting suggests that people who set specific, difficult goals generally achieve more than those told simply to “do their best”. But the same research finds that very narrow goals can backfire: people may chase the target and neglect everything the target was meant to measure.'] },
        { title: 'Extract D', paras: ['My grandmother had no ambitions that anyone would have recognised. She did not want to be rich or famous or important. She wanted her garden to be good and her grandchildren to be kind, and she worked at both, every day, with a fierceness I have rarely seen in anyone who wanted the world.'] },
      ],
      items: [
        ['argues that the purpose of ambition matters more than ambition itself?', 'A', '“The question is not whether to be ambitious, but what for.” D shows a different kind of ambition but makes no general argument.'],
        ['describes recovering from the loss of a goal?', 'B', 'The writer gave up becoming a concert pianist, struggled, and found happiness teaching. D describes a goal pursued, not lost.'],
        ['refers to research findings about goals?', 'C', 'C cites research on goal-setting. A makes general claims without research.'],
        ['suggests that ambition can be quiet and modest yet intense?', 'D', 'The grandmother’s small goals were pursued “with a fierceness”. B describes intense ambition, but it was for fame, not modest.'],
        ['explains why ambition often seems negative?', 'A', '“We notice it most when it goes wrong.” C warns of narrow goals, but does not explain ambition’s reputation.'],
        ['uses an image suggesting that something was once treated as a means of rising?', 'B', 'The piano “was a ladder”. D describes goals but uses no such image.'],
        ['warns that focusing on a measure can distract from the real aim?', 'C', 'People “may chase the target and neglect everything the target was meant to measure”. A warns about bad purposes, not measures.'],
        ['contrasts a person’s goals with what society usually counts as ambition?', 'D', 'The grandmother’s ambitions were not ones “anyone would have recognised”. A discusses ambition’s reputation, but not a particular person’s goals.'],
        ['gives examples of ambition that has become harmful?', 'A', 'The politician who will say anything and the executive who will cut any corner. C warns of narrow goals but gives no examples of people.'],
        ['suggests that difficult targets can improve performance?', 'C', 'People with “specific, difficult goals” achieve more. B describes a difficult goal that the writer abandoned.'],
      ] }),
  ],

  thinking: [
    TS('strengthen', 'A historian argues that a medieval village was abandoned because its river changed course, not because of the plague that struck the region at the same time.',
      'Which one of these statements, if true, most strengthens the historian’s argument?',
      ['Nearby villages that the plague struck just as hard, but whose rivers did not move, were not abandoned.', 'The plague killed a large share of the region’s population.', 'Rivers often change course after floods.', 'The village’s church was built of stone.'], 0,
      'If villages equally hit by plague survived, plague alone cannot explain the abandonment, leaving the river as the likely cause. Rivers often changing course is the nearest rival, but it does not separate the two explanations for this village.',
      [null, 'this makes plague a stronger rival', 'this does not separate the two explanations', 'this is irrelevant']),
    TS('weaken', 'A company argues: “Our four-day working week has increased productivity, because the amount produced per hour worked has risen by 15 per cent.”',
      'Which one of these statements, if true, most weakens the company’s argument that the four-day week is the reason?',
      ['In the same period, the company installed new machinery that its engineers expected to raise output per hour by about 15 per cent.', 'Staff are happier with the four-day week.', 'Total output has stayed about the same.', 'Some other companies have tried a four-day week.'], 0,
      'The new machinery offers another explanation of exactly the right size. Total output staying the same is the nearest rival, but with fewer hours, steady output is consistent with higher productivity per hour.',
      [null, 'happiness supports the policy', 'steady output with fewer hours fits higher productivity', 'other companies are irrelevant']),
    WR('Five runners — P, Q, R, S and T — finished a race in different positions. P finished exactly two places ahead of Q. R finished immediately ahead of S. T was neither first nor last.\nAna: “T must have finished immediately behind P.”\nBen: “S cannot have finished second.”',
      'Ana', 'Ben', true, false,
      'Only two orders fit: P, T, Q, R, S and R, S, P, T, Q. In both, T is immediately behind P, so Ana is right. In the second order S finished second, so Ben is wrong.'),
    TS('flaw', 'A columnist writes: “Countries with more mobile phones per person have longer life expectancy. Therefore giving everyone a mobile phone would help people live longer.”',
      'Which one of the following best describes the flaw in the columnist’s reasoning?',
      ['Both may result from a country’s wealth, which brings better healthcare as well as more phones.', 'Mobile phones can be expensive.', 'Life expectancy is hard to measure.', 'Some people do not want mobile phones.'], 0,
      'A third factor, wealth, could explain both. Life expectancy being hard to measure is the nearest rival, but it does not identify the faulty step from correlation to cause.',
      [null, 'cost is not the flaw', 'this does not identify the faulty step', 'preference is irrelevant']),
    TS('assumption', 'A school argues: “Banning phones during lunch will make students more active, because they will have nothing to do but play games outside.”',
      'Which one of the following is an assumption the school has made?',
      ['Students who are not on their phones will choose active games rather than other inactive pastimes, such as sitting and talking.', 'Phones are expensive.', 'Exercise is healthy.', 'Students own phones.'], 0,
      'The claim that they will have “nothing to do but play” ignores other inactive choices. Students owning phones is the nearest rival: it is true but is a background fact, not the hidden step in the argument.',
      [null, 'cost is irrelevant', 'this is a value, not the hidden step', 'this is a background fact']),
    TS('weaken', 'A politician claims: “Crime in our city has fallen since we hired 200 more police officers, so more police means less crime.”',
      'Which one of these statements, if true, most weakens the politician’s claim?',
      ['Crime fell by a similar amount over the same period in comparable cities that did not hire more police.', 'Police officers receive good training.', 'Some crimes are not reported.', 'The officers patrol on foot.'], 0,
      'A similar fall elsewhere without extra police suggests another cause. Some crimes not being reported is the nearest rival, but this was true before and after, so it does not explain the change.',
      [null, 'training supports the claim', 'this does not explain the change', 'patrol method is irrelevant']),
    WR('A three-digit number has three different digits. Its digits add to 12, and it is divisible by 5.\nCara: “There are exactly 10 numbers like this.”\nDan: “The number must be greater than 150.”',
      'Cara', 'Dan', false, true,
      'There are 11 such numbers: 165, 345, 390, 435, 480, 570, 615, 705, 750, 840 and 930, so Cara is wrong. The smallest is 165, so Dan is right.'),
    TS('strengthen', 'An ecologist argues that removing foxes from an island will help a rare ground-nesting bird recover.',
      'Which one of these statements, if true, most strengthens the ecologist’s argument?',
      ['On a similar nearby island where foxes were removed ten years ago, the same bird’s numbers have tripled, while no other change was made.', 'Foxes are not native to the island.', 'The bird is protected by law.', 'Foxes eat many kinds of animals.'], 0,
      'A comparable case where only fox removal led to recovery supports the argument. Foxes not being native is the nearest rival, but it does not show removing them helps the bird.',
      [null, 'this does not show removal helps the bird', 'legal status is irrelevant', 'this is too general']),
    TS('conclusion', 'In a club, everyone who plays tennis also swims. Some swimmers cycle. Nobody who cycles plays tennis. Jo swims but does not cycle.',
      'Which one of the following must be true?',
      ['Some swimmers do not play tennis.', 'Jo plays tennis.', 'Jo does not play tennis.', 'Every swimmer plays tennis.'], 0,
      'Some swimmers cycle, and no cyclist plays tennis, so those swimmers do not play tennis. Jo is the trap: she swims and does not cycle, which is consistent with either playing tennis or not.',
      [null, 'this cannot be worked out about Jo', 'this cannot be worked out about Jo', 'swimmers who cycle do not play tennis']),
    TS('flaw', 'A student argues: “If I study hard, I will pass. I didn’t pass. So I didn’t study hard. And because I didn’t study hard, I must not care about school.”',
      'Which one of the following best describes the flaw in the student’s reasoning?',
      ['The second step assumes the only reason someone might not study hard is not caring about school.', 'The first step is invalid.', 'Studying hard is important.', 'Passing is not the only goal.'], 0,
      'If “study hard → pass” is true, the first step is valid. The second step wrongly assumes the only explanation for not studying is not caring — illness or other duties could explain it.',
      [null, 'if the premise is true, the first step is valid', 'this is a value', 'this does not identify the flaw']),
    WR('In a club of 30 members, 18 play chess, 15 play go, and 4 play neither.\nEva: “Exactly 7 members play both chess and go.”\nFinn: “At least 11 members play chess but not go.”',
      'Eva', 'Finn', true, true,
      'Both are right. 30 − 4 = 26 play at least one game. 18 + 15 = 33, so 33 − 26 = 7 play both. Then 18 − 7 = 11 play chess but not go — exactly 11, which is “at least 11”.'),
    TS('weaken', 'A school claims its new anti-bullying program works, because the number of bullying reports fell by half in its first year.',
      'Which one of these statements, if true, most weakens the school’s claim?',
      ['A student survey found that, in the same year, more students said they had been bullied but had been too afraid to report it.', 'The program includes workshops.', 'Teachers support the program.', 'Bullying is a serious problem.'], 0,
      'If students were bullied but did not report it, fewer reports may hide the same or more bullying. Teachers supporting the program is the nearest rival, but support is not evidence that it works.',
      [null, 'this describes the program', 'support is not evidence', 'this is a value']),
    TS('assumption', 'A café owner says: “If we raise the price of coffee by 50 cents, we will earn more money from coffee.”',
      'Which one of the following is an assumption the owner has made?',
      ['Sales will not fall so much that the higher price brings in less money overall.', 'Coffee is popular.', 'Costs will stay the same.', 'Other cafés charge more.'], 0,
      'Higher price brings more money only if enough customers still buy. Costs staying the same is the nearest rival, but the owner speaks of money earned from coffee, not profit.',
      [null, 'popularity is not the hidden step', 'the claim concerns money earned, not profit', 'competitors are not required']),
    TS('strengthen', 'A scientist claims that a certain chemical in a pesticide is harming bees’ ability to find their way back to the hive.',
      'Which one of these statements, if true, most strengthens the claim?',
      ['In an experiment, bees given tiny doses of the chemical were far more likely to fail to return to the hive than bees given none, with all else kept the same.', 'Bees are important pollinators.', 'The pesticide is widely used.', 'Bee numbers have fallen in many countries.'], 0,
      'A controlled experiment links the chemical directly to bees failing to return. Bee numbers falling is the nearest rival, but many causes could explain that.',
      [null, 'importance is not evidence', 'use is not evidence of harm', 'many causes could explain this']),
    WR('On an island, every person either always tells the truth or always lies. Ari says, “Bo is a liar.” Bo says, “Ari and I are both truth-tellers.”\nElla: “Ari is a liar.”\nGil: “Ari and Bo are both liars.”',
      'Ella', 'Gil', false, false,
      'Neither is right. If Bo told the truth, Ari would be truthful too, but then Ari’s statement that Bo is a liar would be false — impossible. So Bo is a liar, which makes Ari’s statement true: Ari is a truth-teller.'),
    TS('flaw', 'A critic writes: “This novel won a major prize, so it must be better than every novel that did not win.”',
      'Which one of the following best describes the flaw in the critic’s reasoning?',
      ['A prize is judged only among the books entered that year, by particular judges, so it cannot rank the novel above every other novel.', 'Prizes are popular.', 'The novel might be long.', 'Some people dislike prize-winning novels.'], 0,
      'The prize compares the novel only with a limited set of entries, judged by a few people. Some people disliking prize-winners is the nearest rival, but it does not identify the flawed step.',
      [null, 'popularity is irrelevant', 'length is irrelevant', 'this does not identify the flawed step']),
  ],

  writing: {
    title: 'The last page', genre: 'narrative',
    stimulus: ['Your story must take place in under one hour.', 'It must include an object that belonged to someone else.', 'Its final sentence must be exactly six words long.'],
    prompt: 'Write a story that meets all three conditions.',
    guidance: ['Use the time limit to create tension or focus.', 'Make the object matter to the story, not just appear in it.', 'Plan your final six-word sentence early so the whole story leads to it.'],
    rubricNotes: 'A strong response meets every condition naturally, uses the constraints to shape the story, and shows sophisticated control of structure, character and language.',
  },
});
