/* Hard Exam 4 — original content written for this site. Pitched well above the real test. */
'use strict';
defExam('H04', {
  reading: [
    readS1({ id: 'H04-s1', headnote: 'Two essayists write about curiosity.',
      glossary: [['indiscriminate', 'not choosing carefully; random'], ['sated', 'fully satisfied']],
      extracts: [
        { label: 'Extract A', paras: [
          'We praise curiosity as though it were simply good, like honesty or courage. But curiosity is an appetite, and appetites can be well or badly fed. A child who asks why the sky is blue is curious; so is a neighbour who reads your post. The first wants to understand the world; the second wants to possess a piece of yours.',
          'What distinguishes good curiosity is not its intensity but its object, and its patience. The idle mind skips from headline to headline, sated by the feeling of knowing without the labour of understanding. The disciplined mind stays with a question long after it has become uncomfortable, because it suspects that the discomfort is where the answer lives.',
        ] },
        { label: 'Extract B', paras: [
          'I distrust the fashionable idea that curiosity must be “disciplined”. Some of the most important discoveries were made by people who were, by any sensible standard, wasting their time — following an odd result because it was odd, reading outside their field for no reason they could explain.',
          'Curiosity is valuable precisely because it is indiscriminate. It does not know in advance what will matter. To demand that it justify itself, or stay politely within its subject, is to ask it to stop being curiosity and become something more like planning. Planning has its place. But nobody ever planned their way to a surprise.',
        ] },
      ],
      questions: [
        Q('In Extract A, what is the purpose of the contrast between the child and the neighbour?', ['To show that curiosity can be directed at good or bad ends.', 'To show that children are more curious than adults.', 'To show that reading other people’s post is common.', 'To show that curiosity always leads to understanding.'], 0,
          'Both are curious, but one wants understanding and the other wants to intrude: curiosity is “an appetite” that can be well or badly fed. Children being more curious is the nearest rival, but both people are equally curious; only their aims differ.',
          [null, 'both are curious; only their aims differ', 'the example is not about frequency', 'the neighbour’s curiosity does not lead to understanding']),
        Q('What does the writer of Extract A mean by “the feeling of knowing without the labour of understanding”?', ['The satisfaction of having encountered information without genuinely thinking it through.', 'The tiredness that comes from reading too much.', 'The pleasure of finally solving a difficult problem.', 'The fear of not knowing something.'], 0,
          'Skimming headlines gives a sense of being informed without real understanding. The pleasure of solving a problem is the nearest rival, but that would involve exactly the “labour” the idle mind avoids.',
          [null, 'the point is satisfaction, not tiredness', 'solving involves the labour the idle mind avoids', 'fear is not mentioned']),
        Q('According to Extract A, why does the disciplined mind stay with an uncomfortable question?', ['It suspects that working through the discomfort will lead to the answer.', 'It enjoys feeling uncomfortable.', 'It has been told to by a teacher.', 'It cannot think of another question.'], 0,
          '“The discomfort is where the answer lives.” Enjoying discomfort is the nearest rival, but the mind stays because of where the answer is, not for pleasure.',
          [null, 'it stays for the answer, not for pleasure', 'no teacher is mentioned', 'nothing suggests this']),
        Q('In Extract B, how does the writer support the claim that curiosity should not be disciplined?', ['By pointing out that important discoveries often came from apparently aimless investigation.', 'By citing a scientific study.', 'By describing personal experience.', 'By arguing that planning is useless.'], 0,
          'Important discoveries came from people “wasting their time”. Arguing planning is useless is the nearest rival, but the writer says “Planning has its place”.',
          [null, 'no study is cited', 'no personal experience is given', '“Planning has its place”']),
        Q('What does the writer of Extract B mean by “nobody ever planned their way to a surprise”?', ['Genuinely unexpected discoveries cannot be reached by following a plan.', 'Planning is always better than curiosity.', 'Surprises are unpleasant.', 'Surprise parties are hard to organise.'], 0,
          'A plan, by definition, aims at something expected; real surprises come from wandering. Planning being always better is the opposite of the writer’s view.',
          [null, 'this is the opposite of the writer’s view', 'surprises are presented as valuable', 'the line is not literal']),
        Q('Which word best describes the tone of the opening of Extract B, “I distrust the fashionable idea…”?', ['Sceptical.', 'Enthusiastic.', 'Sorrowful.', 'Neutral.'], 0,
          'The writer questions a popular view: the tone is sceptical. Neutral is the nearest rival, but “distrust” expresses a clear opinion.',
          [null, 'the writer disagrees', 'there is no sadness', '“distrust” expresses an opinion']),
        Q('On which point would the two writers most clearly disagree?', ['Whether curiosity is most valuable when it is focused and patient.', 'Whether curiosity matters at all.', 'Whether reading is useful.', 'Whether children are curious.'], 0,
          'A praises the disciplined, patient mind; B values curiosity “precisely because it is indiscriminate”. Whether curiosity matters is the nearest rival, but both clearly value it.',
          [null, 'both value curiosity', 'both value reading', 'neither disputes this']),
        Q('Which statement would the writer of Extract A be most likely to make in reply to Extract B?', ['Wandering curiosity can be valuable, but only if it is eventually followed by patient, serious investigation.', 'Curiosity should be banned.', 'Planning is the only route to discovery.', 'Discoveries are mostly made by accident.'], 0,
          'A values patience and staying with a question; this reply grants B’s point while keeping A’s emphasis. Planning being the only route is the nearest rival, but A never mentions planning and values curiosity.',
          [null, 'A values curiosity', 'A never mentions planning', 'this is closer to B’s view']),
      ] }),

    readS2({ id: 'H04-s2', title: 'The great library',
      text: 'In the third century BCE, the rulers of Egypt founded a library in the city of Alexandria that became the most famous in the ancient world. Its aim was nothing less than to …(1)… a copy of every book worth having, in any language. Scholars from across the Mediterranean came to study there, and some of the most important work of ancient mathematics, astronomy and literature was done in or near its halls.\n\nThe library’s methods of acquiring books were sometimes …(2)…. According to one ancient account, ships arriving in Alexandria’s harbour were searched for books, which were copied — and the library kept the originals, returning only the copies to their owners.\n\nThe popular story is that the library was destroyed in a single great fire. The truth appears to be more …(3)…. Part of the collection may have been damaged when Julius Caesar’s forces set fire to ships in the harbour in 48 BCE, but the library seems to have continued for some time afterwards. Over the following centuries, it suffered from reduced funding, political unrest and the …(4)… of scholars, and it slowly declined.\n\nBy the time it finally disappeared, its loss may have attracted little notice. This makes the story less dramatic, but perhaps more …(5)…: great institutions are more often lost through years of neglect than through a single catastrophe.\n\nHistorians …(6)… on how many scrolls the library held. Ancient sources give figures ranging from 40 000 to 700 000, and none can be confirmed. What is not in doubt is that many works known to have existed in the ancient world have not …(7)…; we know of them only through quotations in other books.\n\nThe library has become a symbol, sometimes of the fragility of knowledge, sometimes of human ambition. Its true history is a …(8)… that knowledge must be maintained, not just collected.',
      gaps: [
        [['collect', 'destroy', 'translate', 'sell'], 0, 'The aim was to “collect a copy of every book worth having”. Translate is the nearest rival, but the goal was gathering copies, “in any language”.', [null, 'the library preserved books', 'the aim was gathering copies', 'the library kept books']],
        [['ruthless', 'generous', 'random', 'illegal'], 0, 'Keeping originals and returning copies was “ruthless”. Illegal is the nearest rival, but the passage describes how harsh the method was, not its legal status.', [null, 'keeping the originals is not generous', 'the methods were deliberate', 'the passage does not discuss legality']],
        [['complicated', 'exciting', 'certain', 'recent'], 0, 'Damage, continuation and slow decline make the truth “more complicated”. Certain is the nearest rival, but the passage uses “may” and “seems” throughout.', [null, 'the truth is less dramatic', 'the passage stresses uncertainty', 'the events are ancient']],
        [['departure', 'arrival', 'training', 'election'], 0, 'The library declined with the “departure” of scholars. Arrival is the opposite.', [null, 'arrival would help it', 'training would help it', 'elections are irrelevant']],
        [['instructive', 'exciting', 'tragic', 'famous'], 0, 'A slow decline is “more instructive”: it teaches that neglect destroys institutions. Tragic is the nearest rival, but the sentence goes on to draw a lesson.', [null, 'the story is less dramatic', 'the sentence draws a lesson', 'the story is already famous']],
        [['disagree', 'agree', 'insist', 'rely'], 0, 'With figures from 40 000 to 700 000, historians “disagree”. Agree is the opposite.', [null, 'the figures vary widely', '“insist on how many” does not fit uncertainty', '“rely on how many” makes no sense']],
        [['survived', 'existed', 'been written', 'been quoted'], 0, 'Many works “have not survived” — we know them only through quotations. Been quoted is the opposite: we know them because they were quoted.', [null, 'they did exist', 'they were written', 'they were quoted']],
        [['reminder', 'proof', 'legend', 'warning sign'], 0, 'Its history is “a reminder that knowledge must be maintained”. Proof is the nearest rival, but one story cannot prove a general rule.', [null, 'one story cannot prove a rule', 'the passage contrasts legend with truth', '“a warning sign that” is awkward and too strong']],
      ] }),

    readS3({ id: 'H04-s3', headnote: 'In this poem the speaker reflects on a cliff by the sea.', title: 'Erosion',
      lines: [
        'The sea has never once been in a hurry.',
        'It has the patience of a thing that does not',
        'need to win today, or this year, or',
        'in any lifetime anyone will measure.',
        '',
        'The cliff, meanwhile, keeps up appearances:',
        'a fence, a bench, a sign that says Keep Back,',
        'a car park full of people photographing',
        'the thing that, slowly, is unmaking it.',
        '',
        'My grandmother remembered when the path',
        'ran thirty metres further out. She’d point',
        'at empty air and say, “We picnicked there,”',
        'as if the air had borrowed it, and might return it.',
        '',
        'Nothing returns. But still, each spring, the bench',
        'is moved a little back, and painted green,',
        'and someone sits and watches the sea come in',
        'as if it were a view, and not a verdict.',
      ],
      questions: [
        Q('How is the sea presented in the first stanza?', ['As endlessly patient and certain of eventual victory.', 'As violent and destructive.', 'As calm and harmless.', 'As hurried and impatient.'], 0,
          'It does not “need to win today”; its timescale is beyond any lifetime. Calm and harmless is the nearest rival, but the poem shows it slowly destroying the cliff.',
          [null, 'its power is slow and patient, not violent', 'it is slowly destroying the cliff', '“never once been in a hurry”']),
        Q('What is ironic about the people in the car park (lines 8–9)?', ['They admire the very sea that is gradually destroying the ground they stand on.', 'They are not allowed to take photographs.', 'They cannot see the sea.', 'They are ignoring the sign.'], 0,
          'They photograph “the thing that, slowly, is unmaking” the cliff. Ignoring the sign is the nearest rival, but the poem does not say they ignore it.',
          [null, 'nothing forbids photographs', 'they are photographing it', 'the poem does not say so']),
        Q('What does “keeps up appearances” (line 5) suggest about the cliff?', ['People maintain the cliff-top as if nothing were changing, despite the erosion.', 'The cliff is beautiful.', 'The cliff is newly built.', 'The cliff is hidden.'], 0,
          'Fences, benches and signs give an impression of permanence, hiding the slow loss. The cliff being beautiful is the nearest rival, but “keeps up appearances” suggests pretending.',
          [null, '“keeps up appearances” suggests pretending', 'it is ancient', 'it is in plain view']),
        Q('What does the grandmother’s pointing at “empty air” reveal?', ['The land where she once picnicked has been lost to the sea.', 'She has poor eyesight.', 'She is pointing at a bird.', 'She is imagining a future picnic.'], 0,
          'The path once ran thirty metres further out; that land has now fallen away. Imagining a future picnic is the nearest rival, but she says “We picnicked there” — the past.',
          [null, 'the land is gone, not unseen', 'no bird is mentioned', '“picnicked” is past tense']),
        Q('What is the effect of “as if the air had borrowed it, and might return it” (line 14)?', ['It conveys the grandmother’s wistful, impossible hope that the land might come back.', 'It shows the land will be returned.', 'It shows the grandmother is joking.', 'It shows the air is dangerous.'], 0,
          'The comparison conveys longing; the next line answers it: “Nothing returns.” The land being returned is directly contradicted.',
          [null, '“Nothing returns.”', 'the tone is wistful, not comic', 'the air is not threatening']),
        Q('What does the contrast between “a view” and “a verdict” in the final line suggest?', ['People look at the sea as scenery, but it is actually a judgement that will eventually destroy the cliff.', 'The sea is not visible.', 'The bench should be moved forward.', 'The view is ugly.'], 0,
          'A view is something to enjoy; a verdict is a final decision. The sea is quietly passing sentence on the land. The bench being moved forward is the opposite: it is moved back.',
          [null, 'the sea is visible', 'it is moved back', 'the view is admired']),
      ] }),

    readS4({ id: 'H04-s4', title: 'Why bridges move',
      paras: [
        'Every bridge moves. Steel and concrete bend slightly under load, expand in the heat and contract in the cold. ...(1)... The danger comes when movements build up rather than die away.',
        'Every structure has natural frequencies: rates at which it tends to vibrate if disturbed, like a plucked guitar string. ...(2)... This effect, called resonance, is why a child on a swing can go higher and higher with small, well-timed pushes.',
        'In 2000, London’s new Millennium Bridge began to sway sideways on its opening day. ...(3)... As the bridge moved, the walkers unconsciously adjusted their steps to keep their balance, falling into time with the sway and making it worse.',
        'The bridge was closed for almost two years while engineers fitted dampers. ...(4)... After they were installed, the bridge reopened and has remained steady ever since.',
        'The most famous bridge failure, that of the Tacoma Narrows Bridge in the United States in 1940, is often blamed on simple resonance. ...(5)... The wind caused the deck to twist, and the twisting changed the way the wind pushed on it, feeding more and more energy into the motion until the deck tore apart.',
        '...(6)... Modern bridges are tested with scale models in wind tunnels, and their decks are shaped to let wind pass smoothly.',
      ],
      sentences: [
        'Engineers design for these movements, which are normally small and harmless.',
        'If something pushes the structure repeatedly at one of these frequencies, each push adds to the last, and the movement can grow very large.',
        'The cause turned out to be the crowd of people walking across it.',
        'These devices, a little like the shock absorbers in a car, soak up the energy of the movement.',
        'Engineers now believe the cause was more complex.',
        'The lessons of Tacoma changed bridge design around the world.',
        'Some bridges are painted continuously from one end to the other.',
      ],
      answers: [0, 1, 2, 3, 4, 5],
      explains: [
        'After listing ordinary movements, the gap says engineers design for them, before “The danger comes when…”.',
        'Natural frequencies are defined, then the gap explains what happens when pushes match them, before “This effect, called resonance”.',
        'The bridge swayed; the gap names the crowd as the cause, which the next sentence explains.',
        '“Dampers” are introduced; the gap explains them as “These devices”, then “After they were installed…”.',
        '“Often blamed on simple resonance” is followed by “more complex”, then the explanation of twisting and wind.',
        'The last paragraph describes modern practice, so it opens with the lessons of Tacoma. The sentence about painting is the extra one.',
      ] }),

    readS5({ id: 'H04-s5', headnote: 'Four writers describe returning to places from their past.',
      extracts: [
        { title: 'Extract A', paras: ['I went back to my primary school last year. Everything was absurdly small — the drinking taps came up to my knees — and yet the corridor outside the principal’s office still made my stomach drop. The body, it seems, keeps its own records, and does not update them.'] },
        { title: 'Extract B', paras: ['Psychologists have found that memories are not stored like files and retrieved unchanged. Each time we recall an event, we partly rebuild it, and in the process it can be altered. The places of our childhood, recalled hundreds of times, may bear only a loose resemblance to what was actually there.'] },
        { title: 'Extract C', paras: ['The house where I grew up has been knocked down, and a block of flats stands in its place. People say this must be painful. Strangely, it is not. Because the house no longer exists, my memory of it cannot be contradicted; it belongs to me entirely.'] },
        { title: 'Extract D', paras: ['We returned to my grandfather’s village in Greece when I was twelve. He walked ahead of us, naming every house — this one was the baker’s, that one the teacher’s — though the people inside were strangers. By the end of the day I understood that he was not showing us the village. He was visiting it.'] },
      ],
      items: [
        ['describes a physical reaction that has not changed over time?', 'A', 'The corridor “still made my stomach drop”. D describes a grandfather’s memories, not a bodily reaction.'],
        ['explains that remembering can change a memory?', 'B', 'Each time we recall an event, “we partly rebuild it”. C says a memory cannot be contradicted, the opposite idea.'],
        ['describes an unexpected lack of sadness?', 'C', 'People expect pain, but “Strangely, it is not.” A describes nerves, not an absence of sadness.'],
        ['describes someone whose memories no longer match the present?', 'D', 'The grandfather names houses whose occupants are now strangers. A notices the school seems small but does not live in the past.'],
        ['contrasts how a place looks now with how it felt in childhood?', 'A', 'The school looks absurdly small, yet the corridor still frightens. C cannot compare, as the house is gone.'],
        ['uses a comparison with how computers store information?', 'B', 'Memories are “not stored like files”. A says the body “keeps its own records”, but that is not about computers.'],
        ['suggests that losing a place can protect a memory of it?', 'C', 'The memory “cannot be contradicted”. D describes a village that still exists.'],
        ['describes a realisation the writer came to at the end of a day?', 'D', '“By the end of the day I understood…” A describes a realisation, but not at the end of a day.'],
        ['suggests that the body remembers independently of the mind?', 'A', '“The body … keeps its own records, and does not update them.” B describes how the mind rebuilds memories.'],
        ['suggests that our memories of childhood places may be inaccurate?', 'B', 'They may bear “only a loose resemblance” to reality. C says the memory belongs to the writer, but not that it is inaccurate.'],
      ] }),
  ],

  thinking: [
    TS('strengthen', 'A marine biologist argues that a coral reef’s decline is caused by rising water temperature rather than by pollution from a nearby river.',
      'Which one of these statements, if true, most strengthens the biologist’s argument?',
      ['Parts of the reef far from the river mouth, which receive no river pollution, have declined just as much as parts close to it.', 'The river carries pollution from farms.', 'Coral is sensitive to many changes.', 'Water temperatures have risen in many oceans.'], 0,
      'If unpolluted parts declined just as much, pollution cannot explain the decline, leaving temperature as the likely cause. Water temperatures rising in many oceans is the nearest rival, but it does not separate the two explanations on this reef.',
      [null, 'this supports the rival explanation', 'this fits either explanation', 'this does not separate the explanations here']),
    TS('weaken', 'A nutritionist claims: “Children who eat dinner with their families every night do better at school, so families should eat dinner together to improve children’s results.”',
      'Which one of these statements, if true, most weakens the nutritionist’s argument?',
      ['Families who eat together every night tend to have parents with more time and resources, which are themselves linked to better school results.', 'Family dinners are enjoyable.', 'Some families eat late.', 'Children should eat healthy food.'], 0,
      'If something else — parents’ time and resources — explains both, eating together may not cause better results. Some families eating late is the nearest rival, but it does not affect the causal claim.',
      [null, 'enjoyment does not affect the claim', 'this does not affect the causal claim', 'this is a separate point']),
    WR('In a non-leap year, 1 March is a Tuesday.\nKim: “31 March is a Wednesday.”\nLev: “1 April is a Friday.”',
      'Kim', 'Lev', false, true,
      'Lev is right: 1 April is 31 days after 1 March, and 31 = 4 weeks + 3 days, so it is three days after Tuesday — a Friday. Kim is wrong: 31 March is 30 days after 1 March, which is 4 weeks + 2 days, so it is a Thursday.'),
    TS('flaw', 'An editorial argues: “If we allow students to redo one test, soon they will want to redo every test, and before long there will be no deadlines at all.”',
      'Which one of the following best describes the flaw in the editorial?',
      ['It assumes without evidence that one small change will inevitably lead to a chain of extreme consequences.', 'It ignores that some students like tests.', 'It is about tests rather than homework.', 'It does not say which test.'], 0,
      'This is a “slippery slope”: each step is assumed, not shown. Ignoring students who like tests is the nearest rival, but it does not identify the faulty reasoning.',
      [null, 'this does not identify the faulty reasoning', 'the topic is not the flaw', 'this detail is not the flaw']),
    TS('assumption', 'A museum director argues: “Making entry free will increase the number of visitors, because cost is what keeps people away.”',
      'Which one of the following is an assumption the director has made?',
      ['There are enough people who would visit if cost were removed, rather than staying away for other reasons such as lack of interest.', 'The museum has interesting exhibits.', 'Free entry will cost the museum money.', 'Other museums are free.'], 0,
      'The director assumes cost is the main barrier for enough people. The museum having interesting exhibits is the nearest rival, but the argument does not depend on it.',
      [null, 'the argument does not depend on this', 'this is a consequence, not an assumption', 'other museums are irrelevant']),
    TS('weaken', 'A tech company claims: “Our new app improves concentration. Users who downloaded it reported better concentration after a month.”',
      'Which one of these statements, if true, most weakens the company’s claim?',
      ['People who downloaded the app were already trying to improve their concentration in many other ways, and expected the app to work.', 'The app is free.', 'The app has thousands of users.', 'The app sends daily reminders.'], 0,
      'Users who were trying other methods and expected improvement might report better concentration regardless. The app having thousands of users is the nearest rival, but popularity is not evidence either way.',
      [null, 'price is irrelevant', 'popularity is not evidence', 'this describes the app']),
    WR('Jen has only 20-cent and 50-cent coins. She has 6 coins worth $2.10 in total.\nMo: “Jen has more 20-cent coins than 50-cent coins.”\nNia: “Jen has three 50-cent coins.”',
      'Mo', 'Nia', false, true,
      'If Jen has x 20-cent coins, she has 6 − x 50-cent coins, so 20x + 50(6 − x) = 210, giving 300 − 30x = 210 and x = 3. She has three of each, so Nia is right and Mo is wrong.'),
    TS('strengthen', 'An education researcher argues that small class sizes improve students’ results in the early years of school.',
      'Which one of these statements, if true, most strengthens the argument?',
      ['In a large study, students randomly assigned to small classes in the early years outperformed those randomly assigned to regular classes, and the gap persisted for years.', 'Teachers prefer small classes.', 'Small classes cost more.', 'Private schools often have smaller classes.'], 0,
      'Random assignment rules out other differences between the groups. Private schools having smaller classes is the nearest rival, but private-school students differ in many other ways.',
      [null, 'preference is not evidence', 'cost is irrelevant', 'private-school students differ in other ways']),
    TS('conclusion', 'No reptiles at the zoo are kept in the north building. All the animals in the north building are fed twice a day. Some animals that are fed twice a day are reptiles.',
      'Which one of the following must be true?',
      ['Some animals fed twice a day are not in the north building.', 'All reptiles are fed twice a day.', 'Every animal fed twice a day is in the north building.', 'No reptile is fed twice a day.'], 0,
      'Some animals fed twice a day are reptiles, and no reptile is in the north building, so those animals are outside it. All reptiles being fed twice a day is the nearest rival, but only “some” are.',
      [null, 'only “some” are', 'the reptiles fed twice a day are not there', 'some reptiles are']),
    TS('flaw', 'A coach argues: “Every player I have dropped from the team this year has later said they were glad to have more free time. So being dropped is good for players.”',
      'Which one of the following best describes the flaw in the coach’s reasoning?',
      ['Players may say they are glad to save face, so their comments are not reliable evidence of how they really feel.', 'Free time is important.', 'Some players are never dropped.', 'The coach might be unfair.'], 0,
      'The evidence comes from people with a reason to hide disappointment. The coach being unfair is the nearest rival, but it does not identify the problem with the evidence.',
      [null, 'this is a value', 'this is irrelevant', 'this does not identify the problem with the evidence']),
    WR('Mia is twice as old as Ned. In 6 years’ time, Mia will be one and a half times as old as Ned.\nOli: “Ned is 6 years old now.”\nPip: “In 12 years’ time, Mia’s age will be four-thirds of Ned’s age.”',
      'Oli', 'Pip', true, true,
      'Both are right. If Ned is n, then 2n + 6 = 1.5(n + 6), so 0.5n = 3 and n = 6; Mia is 12. In 12 years they will be 24 and 18, and 24 ÷ 18 = 4/3.'),
    TS('weaken', 'A council argues: “We should close the local library, because the number of books borrowed has fallen by 40 per cent in five years, so the community no longer needs it.”',
      'Which one of these statements, if true, most weakens the council’s argument?',
      ['Over the same period, the number of people visiting the library to use computers, attend classes and study has doubled.', 'Libraries are expensive to run.', 'Many people now buy e-books.', 'The library building is old.'], 0,
      'If visits for other purposes have doubled, the community clearly still needs it. Many people buying e-books is the nearest rival, but it explains falling loans without showing the library is still needed.',
      [null, 'this supports closing it', 'this does not show the library is still needed', 'this supports closing it']),
    TS('strengthen', 'A historian claims that a letter said to have been written in 1820 is a forgery made much later.',
      'Which one of these statements, if true, most strengthens the historian’s claim?',
      ['The letter is written on paper made by a process that was not invented until the 1870s.', 'The letter’s handwriting is untidy.', 'The letter mentions the weather.', 'The letter was found in an attic.'], 0,
      'Paper that could not exist in 1820 shows the letter was made later. Untidy handwriting is the nearest rival, but it says nothing about the date.',
      [null, 'handwriting says nothing about the date', 'this is irrelevant', 'where it was found is not decisive']),
    WR('A bag holds red, blue and green marbles, with at least one of each colour and 20 marbles in total. There are twice as many red marbles as blue marbles, and more green marbles than red marbles.\nQuin: “There are exactly 3 blue marbles.”\nRia: “There could be 8 red marbles.”',
      'Quin', 'Ria', false, false,
      'Neither is right. With b blue marbles there are 2b red and 20 − 3b green, and green must be more than red, so 20 − 3b > 2b, giving b < 4. So b could be 1, 2 or 3, and Quin is wrong to say exactly 3. Eight red would need 4 blue and 8 green, but green must be more than red, so Ria is wrong.'),
    TS('assumption', 'A manager says: “Staff who work from home are less productive, because I can’t see them working.”',
      'Which one of the following is an assumption the manager has made?',
      ['Being able to see someone working is a reliable measure of how productive they are.', 'Working from home saves travel time.', 'Some staff prefer the office.', 'The office has good equipment.'], 0,
      'The manager treats visibility as evidence of productivity. Some staff preferring the office is the nearest rival, but it does not relate to productivity.',
      [null, 'this is a benefit, not an assumption', 'preference does not relate to productivity', 'equipment is irrelevant']),
    TS('flaw', 'A student argues: “This website must be reliable, because it says on its home page that all its information is accurate.”',
      'Which one of the following best describes the flaw in the student’s reasoning?',
      ['It relies on the website’s own claim about itself, which cannot show that it is reliable.', 'Websites can be updated.', 'The website might be popular.', 'The student did not read the whole site.'], 0,
      'Using a source’s claim about itself to prove its reliability is circular. The student not reading the whole site is the nearest rival, but that would not fix the flaw.',
      [null, 'this is irrelevant', 'popularity is irrelevant', 'reading more would not fix the circular reasoning']),
  ],

  writing: {
    title: 'Specialist or all-rounder?', genre: 'discursive',
    stimulus: ['“It is better to be excellent at one thing than good at many.”'],
    prompt: 'Write a discussion of this statement, exploring different points of view, and reach your own conclusion.',
    guidance: ['Consider examples from different areas — sport, music, science, work or everyday life.', 'Explore the strongest arguments on both sides, not only the obvious ones.', 'Your conclusion may be qualified, but it must be clear and reasoned.'],
    rubricNotes: 'A strong response engages with the complexity of the question, uses well-chosen examples, weighs both sides with nuance and reaches a thoughtful, clearly argued conclusion.',
  },
});
