/* Medium Exam 1 — original content written for this site. */
'use strict';
defExam('M01', {
  reading: [
    readS1({ id: 'M01-s1', headnote: 'Two writers describe a journey by sea, one in the nineteenth century and one in the present day.',
      glossary: [['steerage', 'the cheapest part of a ship, below deck'], ['berth', 'a narrow bed on a ship']],
      extracts: [
        { label: 'Extract A', paras: [
          'We had been eleven weeks at sea when my mother, who had not complained once since Plymouth, sat down upon her trunk and wept. It was not the food, though the biscuit had long since grown a fur of its own, nor the cold, nor the motion that had kept half of steerage groaning in their berths since the Bay of Biscay. It was, she said afterwards, the sight of my father’s good boots, which he had polished every evening as though he were still a man with an office to go to, and which that morning he had let lie unpolished beside the ladder.',
          'I did not understand then what she had seen. I understand it better now. A man may lose his country and his trade and still hold himself together, so long as there is one small thing he insists upon; and when he gives that up, the people who love him know before he does that something has broken.',
          'He polished them again the next evening. I think she made him.',
        ] },
        { label: 'Extract B', paras: [
          'The ferry to the island takes forty minutes, and I have made the crossing perhaps three hundred times. I could tell you where the swell will catch the bow and which seat stays dry when the wind is from the south. Familiarity, they say, breeds contempt; in my experience it breeds something closer to affection, the kind you feel for a slightly difficult relative.',
          'On this crossing, though, there was a family I had not seen before: a father, two small girls, and a grandmother in a coat far too heavy for the season, who held a plastic bag of documents on her lap as though it might be snatched away. The girls ran to the rail and shrieked at every wave. The grandmother did not look at the sea at all. She looked at the island, growing slowly larger, with an expression I have since tried and failed to describe.',
          'When we docked she was the first to stand. She did not wait for the ramp to settle. I suppose that when you have waited long enough for something, another thirty seconds can seem unbearable.',
        ] },
      ],
      questions: [
        Q('In Extract A, why does the writer mention the food, the cold and the motion of the ship?', ['To show that the voyage was more comfortable than expected.', 'To rule them out as the reason for the mother’s tears.', 'To explain why the father stopped polishing his boots.', 'To show how many passengers were ill.'], 1,
          'Each is listed and dismissed — “It was not the food … nor the cold, nor the motion” — so that the real reason, the boots, stands out. Showing how many were ill is the nearest rival, but the sickness is mentioned only to be set aside.',
          ['the details show discomfort, not comfort', null, 'the boots are explained separately', 'the sickness is mentioned only to be set aside']),
        Q('What does the father’s habit of polishing his boots suggest about him?', ['He wanted to impress the other passengers.', 'He was clinging to his dignity and his old way of life.', 'He was worried the boots would be stolen.', 'He was planning to sell the boots on arrival.'], 1,
          'He polished them “as though he were still a man with an office to go to”: the habit kept up his sense of who he was. Impressing others is the nearest rival, but the habit is described as private and for himself.',
          ['the habit is private, not a show for others', null, 'theft is not mentioned', 'nothing suggests selling']),
        Q('The mother weeps because she', ['realises her husband is losing heart.', 'is tired of the long voyage.', 'has lost her trunk.', 'is afraid of the sea.'], 0,
          'The unpolished boots tell her “something has broken” in her husband. Tiredness of the voyage is the nearest rival, but the writer specifically says it was not the hardships of the voyage.',
          [null, 'the writer rules out the hardships of the voyage', 'she is sitting on her trunk', 'the sea itself is ruled out']),
        Q('What does the final line of Extract A, “I think she made him”, suggest?', ['The mother was unkind to the father.', 'The mother helped the father recover his self-respect.', 'The father enjoyed polishing boots.', 'The writer is unsure what happened to the boots.'], 1,
          'By making him polish the boots again, the mother restores the small habit that held him together. The writer being unsure is the nearest rival, because of “I think”, but the uncertainty is about how it happened, not what happened.',
          ['her act is caring, not unkind', null, 'enjoyment is not the point', 'the boots were polished; the doubt is only about why']),
        Q('In Extract B, what does the writer mean by comparing familiarity to “a slightly difficult relative”?', ['The writer dislikes the ferry.', 'The writer is fond of the crossing despite its discomforts.', 'The writer travels with relatives.', 'The ferry is often late.'], 1,
          'Knowing the crossing well has bred “affection”, like love for a relative who is sometimes difficult. Disliking the ferry is the nearest rival, because the writer mentions the swell and wet seats, but the writer says familiarity breeds affection, not contempt.',
          ['the writer says familiarity breeds affection, not contempt', null, 'the writer travels alone', 'lateness is not mentioned']),
        Q('Which detail in Extract B best suggests the grandmother is anxious about the journey’s purpose?', ['Her coat is too heavy for the season.', 'She holds her documents as though they might be snatched away.', 'She does not look at the sea.', 'She is the first to stand.'], 1,
          'Clutching the documents “as though it might be snatched away” shows how much depends on them. Not looking at the sea is the nearest rival, but that shows where her attention is, not anxiety about her papers.',
          ['the coat suggests she has come from somewhere colder', null, 'this shows where her attention is fixed', 'this shows impatience on arrival']),
        Q('How are the girls’ reactions to the crossing different from the grandmother’s?', ['The girls are frightened, while the grandmother is calm.', 'The girls enjoy the sea itself, while the grandmother is focused only on reaching the island.', 'The girls are bored, while the grandmother is excited by the waves.', 'The girls look at the island, while the grandmother looks at the sea.'], 1,
          'The girls “shrieked at every wave” while the grandmother “did not look at the sea at all” but watched the island. The girls being frightened is the nearest rival, but shrieking at the rail shows excitement here.',
          ['their shrieking at the rail shows excitement', null, 'the grandmother ignores the waves', 'it is the other way round']),
        Q('Which of these ideas is found in both extracts?', ['A journey to a new place can carry great hope and strain for a family.', 'Sea travel was more dangerous in the past.', 'Children are braver than adults.', 'Ferries are more comfortable than sailing ships.'], 0,
          'In A a family emigrates under great strain; in B a family arrives at an island the grandmother has waited a long time to reach. Sea travel being more dangerous in the past is the nearest rival, but neither extract compares danger.',
          [null, 'neither extract compares the danger of sea travel', 'neither extract compares bravery', 'neither compares comfort']),
      ] }),

    readS2({ id: 'M01-s2', title: 'Krill',
      text: 'Antarctic krill are small, shrimp-like animals, rarely longer than six centimetres, yet together they may weigh more than any other single species of wild animal on Earth. Their numbers are so vast that swarms can …(1)… the sea red or brown for kilometres.\n\nKrill feed on microscopic algae, much of which grows on the underside of sea ice. In turn, they are the main food of an …(2)… range of animals: penguins, seals, fish, seabirds and the great baleen whales, which filter tonnes of krill from the water each day. Remove krill from the Southern Ocean, and much of the food web would …(3)….\n\nThis makes scientists uneasy about two trends. The first is the …(4)… of sea ice in some parts of Antarctica, which reduces the food available to young krill. The second is fishing. Krill are caught in large quantities and turned into fish food and dietary supplements. The amount taken is small compared with the total population, but fishing is often …(5)… in the same places where penguins and seals feed.\n\nAn international body sets catch limits, and its rules are among the most …(6)… of any fishery in the world. Even so, some researchers argue that the limits should be based on what local predators need, not just on the total size of the population. Krill are easy to …(7)…, being small and far away, but the health of the whole Southern Ocean may …(8)… on them.',
      gaps: [
        [['colour', 'cover', 'fill', 'paint'], 0, 'Swarms are dense enough to “colour the sea red or brown”. Paint is the nearest rival, but painting is something done deliberately with a brush; colour is the natural verb.', [null, 'cover does not explain the red or brown', 'fill does not go with a colour', 'paint suggests a deliberate act']],
        [['enormous', 'unusual', 'unknown', 'eager'], 0, 'Penguins, seals, fish, birds and whales make an “enormous range”. Unusual is the nearest rival, but the point is how many animals depend on krill.', [null, 'the point is how many, not how strange', 'the animals are listed, so they are known', 'eager does not describe a range']],
        [['collapse', 'expand', 'improve', 'appear'], 0, 'Without krill, much of the food web would “collapse”. Expand is the opposite of what losing the main food would do.', [null, 'losing food would not expand the web', 'losing food would not improve it', 'the food web already exists']],
        [['loss', 'growth', 'colour', 'cost'], 0, 'Less sea ice means less food for young krill: the “loss of sea ice”. Growth is the opposite of what would worry scientists.', [null, 'growth would help krill', 'colour is irrelevant', 'cost does not fit sea ice']],
        [['concentrated', 'forbidden', 'scattered', 'finished'], 0, 'Fishing is “concentrated in the same places” where predators feed, which is why a small total catch can still matter. Scattered is the opposite: spread out, the catch would matter less.', [null, 'the passage says fishing happens', 'scattered fishing would not hurt particular feeding areas', 'fishing is ongoing']],
        [['careful', 'careless', 'popular', 'recent'], 0, '“Even so” shows the rules are already good: among the most “careful” in the world. Careless contradicts “even so”, which introduces a criticism of good rules.', [null, '“even so” shows the rules are good', 'popularity is not the point', 'age is not the point']],
        [['overlook', 'catch', 'study', 'protect'], 0, 'Being small and far away, krill are easy to “overlook” — to fail to notice. Catch is the nearest rival, but the sentence contrasts how little attention they get with their importance.', [null, 'the contrast is about attention, not catching', 'being far away makes them hard to study', 'the contrast is that they get too little attention']],
        [['depend', 'rest', 'decide', 'turn'], 0, 'The ocean’s health may “depend on” krill. Rest on is close in meaning, but depend is the precise word for relying on something to survive.', [null, '“rest on” is weaker than the meaning needed', 'the ocean does not decide', '“turn on” means to attack']],
      ] }),

    readS3({ id: 'M01-s3', headnote: 'In this poem, the speaker describes visiting a famous painting in a gallery.', title: 'Room Twelve',
      lines: [
        'They put a rope in front of it, of course,',
        'and a guard who looks at us instead of it,',
        'and a card that tells us, in four languages,',
        'the year, the paint, the name of who it was',
        'that sat for it, and what she might have thought.',
        '',
        'We stand in rows. We lift our phones. We take',
        'the picture of the picture of the girl',
        'who turned her head four hundred years ago',
        'because, perhaps, somebody said her name.',
        '',
        'A man beside me reads the card aloud,',
        'then nods, as if the painting had agreed.',
        'Behind me someone asks about the café.',
        'The girl keeps looking at a door we can’t see,',
        'the light still falling on her as it fell',
        '',
        'before the rope, the guard, the four languages,',
        'before the crowd that came to look at her',
        'and, looking, mostly looked at one another.',
        'I wait until the room is nearly empty.',
        'She has not moved. I think she has been waiting.',
      ],
      questions: [
        Q('What does the speaker suggest by saying the guard “looks at us instead of it” (line 2)?', ['The guard is not interested in art.', 'The painting is being protected from the visitors.', 'The guard is lost.', 'The visitors are behaving badly.'], 1,
          'The guard watches the visitors because they, not the painting, are the risk. That the guard is not interested in art is the nearest rival, but the line is about the guard’s job, not taste.',
          ['the line is about the guard’s job, not taste', null, 'nothing suggests confusion', 'the guard watches in case, not because anyone has misbehaved']),
        Q('What is the effect of the phrase “the picture of the picture of the girl” (line 8)?', ['It shows how much the visitors love the painting.', 'It suggests the visitors are seeing the painting at second hand, through their phones.', 'It explains that the painting is a copy.', 'It shows the girl has had her picture taken many times.'], 1,
          'Photographing a picture puts a screen between viewer and painting: they look at their copy, not the work. That the painting is a copy is the nearest rival, but the phrase is about the phones, not the original.',
          ['the line is critical rather than admiring', null, 'the phrase is about the phones, not a copy on the wall', 'the girl was painted, not photographed']),
        Q('Why does the man “nod, as if the painting had agreed” (lines 11–12)?', ['The painting has spoken to him.', 'He is satisfied that the card has told him all he needs to know.', 'He is greeting a friend.', 'He disagrees with the card.'], 1,
          'Having read the facts aloud, he treats the matter as settled — as though the painting had confirmed them. That he disagrees with the card is the opposite of his nod.',
          ['the comparison is only “as if”', null, 'no friend is mentioned', 'a nod shows agreement']),
        Q('Which lines most clearly show the crowd’s lack of attention to the painting?', ['lines 1–2', 'lines 6–7', 'lines 13 and 18', 'lines 19–20'], 2,
          'Line 13 has someone asking about the café, and line 18 says the crowd “mostly looked at one another”. Lines 6–7 are the nearest rival, as the phones distract, but lines 13 and 18 show attention leaving the painting entirely.',
          ['these describe the gallery’s arrangements', 'the phones point at the painting, at least', null, 'these lines show the speaker’s own attention'], { keepOrder: true }),
        Q('In the last stanza, how is the speaker different from the rest of the visitors?', ['The speaker leaves early.', 'The speaker stays and gives the painting real attention.', 'The speaker takes the most photographs.', 'The speaker talks to the guard.'], 1,
          'The speaker waits until the room is nearly empty and looks properly. Leaving early is the opposite of what happens.',
          ['the speaker stays until the room empties', null, 'no photograph by the speaker is described', 'the speaker does not talk to anyone']),
        Q('What does the final line, “I think she has been waiting”, suggest?', ['The girl in the painting is impatient.', 'The painting seems to wait for someone who will truly look at it.', 'The speaker is waiting for a friend.', 'The gallery is about to close.'], 1,
          'After all the distracted visitors, the painting seems to have been waiting for genuine attention, which the speaker now gives. The girl being impatient is the nearest rival, but “waiting” here is patient, not impatient.',
          ['the waiting is patient, not impatient', null, 'no friend is mentioned', 'closing time is not mentioned']),
      ] }),

    readS4({ id: 'M01-s4', title: 'A short history of the umbrella',
      paras: [
        'Long before anyone thought of keeping off rain, people used shades to keep off the sun. In ancient Egypt, China and Assyria, a canopy held over an important person was a sign of rank. ...(1)...',
        'The idea of a waterproof covering seems to have developed in China, where paper canopies were coated with wax or oil. ...(2)... Still, for centuries they remained luxury goods.',
        'In Europe, umbrellas were slow to catch on. For a long time they were thought of as a fashion item for women, and a man who carried one risked being laughed at. ...(3)... He is said to have carried one for thirty years and endured constant mockery before Londoners finally followed his example.',
        '...(4)... Early European umbrellas had frames of whalebone or cane and could weigh several kilograms. In 1852 a manufacturer introduced a frame made of steel ribs, which was lighter, stronger and cheaper to produce.',
        'The design has changed surprisingly little since. ...(5)... Inventors have proposed umbrellas with fans, with clear domes and with handles that clip to a backpack, but none has replaced the basic form.',
        'Perhaps the umbrella’s success lies in its simplicity. ...(6)... Few everyday objects have done the same job, in almost the same way, for so long.',
      ],
      sentences: [
        'Only the most powerful were entitled to walk beneath one.',
        'This made them useful in rain, but they were fragile and expensive.',
        'The change in Britain is often credited to a traveller named Jonas Hanway.',
        'Weight was another problem.',
        'Folding pocket umbrellas and automatic opening buttons are refinements rather than revolutions.',
        'It is cheap to make, easy to carry and needs no instructions.',
        'Umbrellas are now made in factories all over the world.',
      ],
      answers: [0, 1, 2, 3, 4, 5],
      explains: [
        'The paragraph says a canopy was a sign of rank; the gap continues the idea: only the powerful could walk beneath one.',
        'Waxed paper made canopies waterproof (“useful in rain”), and “Still … they remained luxury goods” follows the mention of expense.',
        '“He is said to have carried one for thirty years” needs a named man before it: Jonas Hanway.',
        'The paragraph describes heavy early frames and a lighter steel design; it opens by naming the problem of weight.',
        '“The design has changed surprisingly little” is followed by a sentence calling later changes refinements; the next sentence describes inventions that failed to replace it.',
        '“Its simplicity” is explained by cheapness, portability and needing no instructions. The sentence about factories is the extra one.',
      ] }),

    readS5({ id: 'M01-s5', headnote: 'Four writers discuss maps.',
      extracts: [
        { title: 'Extract A', paras: ['Every flat map of the world distorts it, because it is impossible to flatten the surface of a sphere without stretching or tearing it. The familiar Mercator map keeps the shapes of small areas accurate, which made it valuable for navigation, but it greatly enlarges regions near the poles. Greenland appears about the size of Africa, though Africa is roughly fourteen times larger.'] },
        { title: 'Extract B', paras: ['My grandfather would never use a phone for directions. He kept a road atlas in the glovebox, its pages soft as cloth, with our family’s trips marked in pencil and dated. When he died we found routes in it I had never heard of, to towns none of us knew he had visited. We are still trying to work out why he went.'] },
        { title: 'Extract C', paras: ['We are raising a generation that cannot read a map. Satellite navigation tells us when to turn but never where we are, and people who follow it blindly have driven into rivers and up closed mountain roads. Schools should teach map-reading again, not as nostalgia but as a basic skill for understanding the world.'] },
        { title: 'Extract D', paras: ['The best maps do not try to show everything. The famous map of the London Underground ignores real distances altogether and straightens every line, because a passenger needs to know the order of stations and where to change, not how far apart they are. Its designer understood that what a map leaves out matters as much as what it includes.'] },
      ],
      items: [
        ['explains why every flat map must be inaccurate in some way?', 'A', 'A says a sphere cannot be flattened without stretching or tearing. D says maps leave things out, but by choice, not because they must.'],
        ['describes a map that contains a mystery?', 'B', 'The grandfather’s atlas records trips to towns nobody knew he visited. A mentions a surprising fact about Greenland, but not a mystery.'],
        ['argues that a skill should be taught again?', 'C', 'C says schools should teach map-reading again. D praises a designer but argues for nothing to be taught.'],
        ['praises a map for leaving out accurate information?', 'D', 'D praises the Underground map for ignoring real distances. A describes distortion as a drawback, not a strength.'],
        ['gives an example of a region shown much larger than it really is?', 'A', 'A says Greenland looks about the size of Africa though Africa is far larger. D says distances are ignored, but gives no region shown too large.'],
        ['describes someone who preferred an older way of finding the way?', 'B', 'The grandfather refused to use a phone and kept a road atlas. C argues for older skills, but does not describe a particular person.'],
        ['mentions people being harmed by relying on technology?', 'C', 'C mentions drivers ending up in rivers and on closed roads by following satellite navigation. B mentions phones, but no harm.'],
        ['suggests that a map should be designed around what its user needs?', 'D', 'D says passengers need the order of stations, not distances. A notes Mercator was valuable for navigation, but does not argue design should suit the user.'],
        ['compares the real sizes of two regions?', 'A', 'A says Africa is roughly fourteen times larger than Greenland. D mentions distances, but compares no regions.'],
        ['includes a family record kept on a map?', 'B', 'The atlas has the family’s trips marked in pencil and dated. No other extract mentions a family record.'],
      ] }),
  ],

  thinking: [
    TS('strengthen', 'A council officer argues: “Installing more rubbish bins along the beach path will reduce the amount of litter on the beach.”',
      'Which one of these statements, if true, most strengthens the officer’s argument?',
      ['Surveys show that most litter on the beach is dropped by people who say they could not find a bin nearby.', 'The beach is busiest in summer.', 'New bins are cheap to install.', 'Some people pick up litter on the beach voluntarily.'], 0,
      'If most litter comes from people who could not find a bin, more bins addresses the actual cause. Cheap bins is the nearest rival: it makes the plan easier, but it does not show it would reduce litter.',
      [null, 'busy times do not show bins would help', 'cost does not show bins would reduce litter', 'volunteers do not show bins would help']),
    TS('weaken', 'Researchers found that students who sit at the front of the classroom get higher marks than those who sit at the back. They concluded: “Sitting at the front helps students learn.”',
      'Which one of these statements, if true, most weakens this conclusion?',
      ['In these classes, students chose their own seats, and the most motivated students tended to choose the front.', 'Front seats are closer to the board.', 'Some students prefer to sit near their friends.', 'The research was carried out in several schools.'], 0,
      'If the keenest students chose the front, their motivation, not the seat, may explain their higher marks. Being closer to the board is the nearest rival, but it suggests a way the front might help, which supports the conclusion.',
      [null, 'this supports the conclusion', 'this does not explain the difference in marks', 'more schools makes the finding stronger']),
    WR('In a club election, a candidate wins if they get more than half of the votes. If no candidate gets more than half, a second vote is held between the top two candidates. 40 members vote, and each votes for one candidate.\nAnnika: “If Ben got 20 votes in the first vote, there must be a second vote.”\nDylan: “If there is a second vote, nobody got more than 20 votes in the first vote.”',
      'Annika', 'Dylan', true, true,
      'Both are right. If Ben got 20 votes, only 20 votes are left for everyone else, so nobody can have more than half (21 or more), and a second vote must be held. And a second vote means nobody reached 21, so nobody got more than 20.'),
    TS('flaw', 'Carmen says: “Countries with more hospitals have more sick people. So building hospitals must make people sick.”',
      'Which one of the following shows the mistake Carmen has made?',
      ['Countries with more people tend to have both more hospitals and more sick people.', 'Hospitals are expensive to build.', 'Some hospitals are very small.', 'Doctors work in hospitals.'], 0,
      'Both numbers rise with population size, so the link does not show that hospitals cause illness. Some hospitals being small is the nearest rival, but it does not touch the reasoning about cause.',
      [null, 'cost does not explain the link', 'this does not touch the reasoning about cause', 'this does not explain the link']),
    TS('assumption', 'The coach says: “Ella scored the most goals in training this week, so she should play centre forward in Saturday’s match.”',
      'Which one of the following is an assumption the coach has made?',
      ['Scoring goals in training shows how well a player will score in a real match.', 'Ella wants to play centre forward.', 'The team will win on Saturday.', 'Ella trained every day this week.'], 0,
      'The coach’s reasoning moves from training goals to match play, which only works if training performance predicts match performance. Ella wanting to play there is the nearest rival, but the coach’s reasoning does not depend on her wishes.',
      [null, 'the coach’s reasoning does not depend on her wishes', 'winning is not part of the reasoning', 'how often she trained is not part of the reasoning']),
    TS('weaken', 'A company claims: “Our new app helps people sleep better. Users who tried it for a month reported sleeping an extra half hour each night.”',
      'Which one of these statements, if true, most weakens the company’s claim?',
      ['The month of the trial was during the school holidays, when most users did not have to get up early.', 'The app costs ten dollars a month.', 'Many people have trouble sleeping.', 'The app plays relaxing sounds.'], 0,
      'If users could sleep in during the holidays anyway, the extra half hour may have nothing to do with the app. Relaxing sounds is the nearest rival, but it suggests how the app might work, which supports the claim.',
      [null, 'cost does not affect whether it works', 'this does not affect the evidence', 'this suggests how it might work']),
    WR('At a music camp, every student learns at least one instrument. Students who learn the piano must also learn to read music. Some students who learn the drums do not read music.\nHenry: “Some students who learn the drums do not learn the piano.”\nMila: “Every student who reads music learns the piano.”',
      'Henry', 'Mila', true, false,
      'Henry is right: a drum student who does not read music cannot be learning the piano. Mila is wrong: the rule says piano students must read music, not that everyone who reads music learns the piano.'),
    TS('strengthen', 'Hugo argues that the town library should open on Sunday afternoons, because many families are too busy on weekdays and Saturdays to visit.',
      'Which one of these statements, if true, most strengthens Hugo’s argument?',
      ['In a nearby town, Sunday opening led to a large rise in the number of families using the library.', 'The library has a large children’s section.', 'Most families have a car.', 'The library is closed on public holidays.'], 0,
      'Evidence from a nearby town that Sunday opening brought in more families supports the step from “busy on other days” to “would come on Sundays”. A large children’s section is the nearest rival, but it does not show families would come on Sundays.',
      [null, 'this does not show families would come on Sundays', 'car ownership is irrelevant', 'holidays are irrelevant']),
    TS('flaw', 'Jamal says: “Every time the school holds a fundraising fair, it rains. We should stop holding fairs so that we get less rain.”',
      'Which one of the following shows the mistake Jamal has made?',
      ['The fairs cannot cause rain; the link is a coincidence or due to the fairs being held in the rainy season.', 'The fairs raise a lot of money.', 'Some people enjoy rain.', 'The fairs could be held indoors.'], 0,
      'A fair cannot cause the weather; the pattern may be chance or the fair being scheduled in a wet month. Holding fairs indoors is the nearest rival, but it is a solution, not the mistake in the reasoning.',
      [null, 'money raised does not explain the mistake', 'enjoying rain is irrelevant', 'this is a solution, not the mistake in the reasoning']),
    TS('conclusion', 'In a survey of a Year 6 class, 18 students said they like reading and 14 said they like drawing. There are 26 students in the class, and every student likes at least one of the two activities.',
      'Which one of the following must be true?',
      ['At least 6 students like both reading and drawing.', 'At most 6 students like only drawing.', 'More students like drawing than reading.', 'At least 13 students like only reading.'], 0,
      'Adding 18 and 14 gives 32, which is 6 more than the 26 students, so 6 students must have been counted twice: they like both. That leaves 14 − 6 = 8 who like only drawing and 18 − 6 = 12 who like only reading, so the other statements are false.',
      [null, '8 students like only drawing', 'more students like reading (18) than drawing (14)', 'only 12 students like only reading']),
    WR('A bus stops at Elm Street only on weekdays. On weekdays it also stops at the station, unless the station is closed for repairs.\nGeorgia: “The bus stopped at Elm Street, so it must be a weekday.”\nEli: “The bus did not stop at the station, so it must be the weekend.”',
      'Georgia', 'Eli', true, false,
      'Georgia is right: the bus stops at Elm Street only on weekdays. Eli is wrong: on a weekday the bus might have missed the station because it was closed for repairs.'),
    TS('weaken', 'Zoe says: “Our class should go to the science museum rather than the zoo for our excursion, because we will learn more there.”',
      'Which one of these statements, if true, most weakens Zoe’s argument?',
      ['The zoo runs a special program on animal adaptations that matches exactly what the class is studying this term.', 'The science museum has a café.', 'The zoo is further away.', 'Some students have already been to the science museum.'], 0,
      'If the zoo’s program matches the class’s current topic, the class may learn more at the zoo. Some students having already been to the museum is the nearest rival: it weakens her case a little, but far less than a perfectly matched program at the zoo.',
      [null, 'a café is irrelevant to learning', 'this is a reason against the zoo', 'this weakens it only a little']),
    TS('assumption', 'Finn says: “If I practise my speech every night, I will win the public speaking competition.”',
      'Which one of the following is an assumption Finn has made?',
      ['Practice alone will make his speech better than everyone else’s.', 'He will have time to practise every night.', 'He has already written his speech.', 'The judges like long speeches.'], 0,
      'Finn assumes that his practice will be enough to beat all the other speakers, who may also practise. Having time to practise is the nearest rival, but the “if” in his statement already covers that.',
      [null, 'the “if” already covers this', 'this is not needed for his reasoning', 'nothing suggests length matters']),
    TS('strengthen', 'A principal believes that the new reading program has improved students’ spelling.',
      'Which one of these statements, if true, most strengthens the principal’s belief?',
      ['Spelling results improved in the classes using the program but not in the classes that had not yet started it.', 'Students enjoy the stories in the program.', 'The program was expensive.', 'Spelling is tested once a term.'], 0,
      'Improvement only where the program was used points to the program as the cause. Students enjoying the stories is the nearest rival, but enjoyment does not show spelling improved.',
      [null, 'enjoyment does not show spelling improved', 'cost is irrelevant', 'how often it is tested is irrelevant']),
    WR('Tickets for the school play cost $5 for students and $10 for adults. Every family that buys four or more tickets gets one free program.\nLuca: “The Nguyen family paid $30 for their tickets, so they must have bought at least four tickets.”\nAisha: “The Smith family got a free program, so they must have paid at least $20.”',
      'Luca', 'Aisha', false, true,
      'Aisha is right: four tickets at the cheapest price cost at least 4 × $5 = $20. Luca is wrong: $30 could be three adult tickets, which is fewer than four.'),
    TS('flaw', 'Lena says: “My older brother got into a selective school, and he always ate fish on the night before tests. So eating fish before tests helps you get into a selective school.”',
      'Which one of the following shows the mistake Lena has made?',
      ['Her brother’s success may have come from other things, such as how hard he studied, and one example cannot prove the cause.', 'Not everyone likes fish.', 'Lena’s brother might not have eaten fish every time.', 'Some schools are not selective.'], 0,
      'Lena treats one person’s habit as the cause of his success, ignoring other likely causes. Her brother not having eaten fish every time is the nearest rival, but it questions her facts rather than her reasoning.',
      [null, 'taste does not affect the reasoning', 'this questions her facts, not her reasoning', 'this is irrelevant']),
  ],

  writing: {
    title: 'The last day', genre: 'narrative',
    stimulus: ['It was the last day before everything changed.', 'Nobody else seemed to have noticed.'],
    prompt: 'Write a story about a character on the last day before a big change in their life.',
    guidance: ['Decide what the change is, but think about whether to tell the reader straight away or let them discover it.', 'Show your character’s feelings through what they notice and do, not only through what they say.', 'Make the final scene feel like an ending, not just the point where you ran out of time.'],
    rubricNotes: 'A strong response focuses on one character and a short span of time, uses carefully chosen details to reveal feeling, and controls when the reader learns what is changing.',
  },
});
