/* Medium Exam 2 — original content written for this site. */
'use strict';
defExam('M02', {
  reading: [
    readS1({ id: 'M02-s1', headnote: 'In this extract from a novel, twelve-year-old Rosa helps at her uncle’s fruit stall at a city market.',
      extracts: [{ paras: [
        'By six o’clock the market had the look of a stage before the audience arrives: lights on, everything in its place, and nobody yet to see it. Uncle Teo had built the pyramid of oranges himself, turning each fruit so that its best side faced the aisle, and he stood back from it with his hands on his hips, the way a painter stands back from a canvas.',
        '“Never put a bruised one on top,” he told Rosa, as if she had been about to. “People buy with their eyes first. Their mouths come later.”',
        'Rosa had been told this, or something like it, every Saturday since she was nine. She had stopped minding. Her uncle’s rules were less like instructions than like weather: they arrived, they passed, and you learned to dress for them.',
        'The first customers were always the same: the café owners, who bought in boxes and did not haggle, and old Mrs Ferreira, who bought one lemon and haggled for ten minutes on principle. Uncle Teo enjoyed Mrs Ferreira more than all the café owners put together. He would pretend to be outraged at her offers, clutch his chest, call on the saints, and at the end of it give her the lemon for whatever she had first suggested, which was always slightly more than the price on the sign.',
        '“She doesn’t want a bargain,” he explained once, when Rosa asked. “She wants an argument. Nobody argues with her any more. Her children are too polite.”',
        'Rosa thought about that for a long time. She had assumed that what people came to the market for was written on the signs: oranges, two dollars a kilo; lemons, fifty cents each. She was beginning to suspect that the signs told only half the story.',
      ] }],
      questions: [
        Q('What does the comparison of the market to “a stage before the audience arrives” suggest?', ['The market is a noisy and crowded place.', 'Everything is prepared and waiting for the people who will make it come alive.', 'The stallholders are actors pretending to sell fruit.', 'The market is closing for the night.'], 1,
          'Lights on, everything in place, nobody yet there: the market is ready and waiting. Stallholders being actors is the nearest rival, but the comparison is about the moment before customers arrive, not about pretending.',
          ['nobody has arrived yet', null, 'the comparison is about readiness, not pretending', 'it is six in the morning, before opening']),
        Q('Uncle Teo standing back from the oranges “the way a painter stands back from a canvas” shows that he', ['is tired after building the pyramid.', 'takes pride and care in how his stall looks.', 'would rather be a painter.', 'is checking whether any fruit has fallen.'], 1,
          'Like a painter judging his work, he admires and checks the arrangement, showing pride. Checking for fallen fruit is the nearest rival, but the comparison is about admiring the result.',
          ['nothing suggests tiredness', null, 'the comparison is about attitude, not ambition', 'the comparison is about admiring, not checking for problems']),
        Q('What does Uncle Teo mean by “People buy with their eyes first”?', ['Customers decide what to buy based on how it looks.', 'Customers should look carefully for bruises.', 'People with poor eyesight buy less fruit.', 'Customers prefer fruit that tastes good.'], 0,
          'The look of the fruit makes the sale; taste comes later. Customers preferring fruit that tastes good is the nearest rival, but he says their “mouths come later”.',
          [null, 'he is talking about how fruit attracts buyers', 'eyesight is not the point', 'he says taste comes later']),
        Q('What does the narrator suggest by describing her uncle’s rules as “like weather”?', ['They are always changing and confusing.', 'They are a familiar part of life that she has learned to accept.', 'They are often wrong.', 'They are mostly about the weather at the market.'], 1,
          'They “arrived, they passed, and you learned to dress for them”: she has learned to live with them. Always changing is the nearest rival, but the point is that she is used to them.',
          ['the point is that she is used to them', null, 'she does not say they are wrong', 'the rules are about the stall, not the weather']),
        Q('Why does Uncle Teo pretend to be outraged at Mrs Ferreira’s offers?', ['He really thinks her offers are too low.', 'He is giving her the lively argument she enjoys.', 'He wants the café owners to see him bargaining.', 'He is trying to get her to buy more lemons.'], 1,
          'He says she “wants an argument”, so he plays along. That he really thinks her offers too low is the nearest rival, but he ends up accepting her first offer, which was above the sign price.',
          ['he accepts her first offer, which is above the sign price', null, 'the café owners have already been served', 'she buys only one lemon']),
        Q('What is surprising about the price Mrs Ferreira finally pays?', ['It is less than the price on the sign.', 'It is slightly more than the price on the sign.', 'She pays nothing.', 'She pays for the café owners’ boxes.'], 1,
          'She pays “whatever she had first suggested, which was always slightly more than the price on the sign”. Less than the sign price is what a bargain-hunter would want, but she is not hunting a bargain.',
          ['she pays more, not less', null, 'she pays her first offer', 'nothing like this is said']),
        Q('Why do Mrs Ferreira’s children no longer argue with her, according to Uncle Teo?', ['They live too far away.', 'They are too polite.', 'They are afraid of her.', 'They agree with everything she says.'], 1,
          'He says, “Her children are too polite.” Being afraid is the nearest rival, but politeness is the reason he gives.',
          ['distance is not mentioned', null, 'politeness, not fear, is the reason given', 'agreement is not mentioned']),
        Q('What does Rosa begin to realise at the end of the extract?', ['That her uncle’s prices are too high.', 'That people come to the market for more than just the goods on sale.', 'That the signs at the market are often wrong.', 'That she would like her own stall one day.'], 1,
          'She suspects the signs “told only half the story”: people come for company and conversation as well as fruit. That the signs are wrong is the nearest rival, but she means they leave things out, not that they are inaccurate.',
          ['she does not question the prices', null, 'she means the signs leave things out, not that they are wrong', 'her future plans are not mentioned']),
      ] }),

    readS2({ id: 'M02-s2', title: 'Lightning',
      text: 'A single bolt of lightning can heat the air around it to about 30 000 degrees Celsius, roughly five times hotter than the surface of the Sun. The air …(1)… so quickly that it creates a shock wave, which we hear as thunder.\n\nLightning begins inside storm clouds, where rising and falling ice particles collide and become electrically charged. Lighter particles, carrying a positive charge, are swept to the top of the cloud, while heavier, negatively charged particles …(2)… lower down. When the difference in charge grows large enough, the air can no longer act as a barrier, and a huge spark jumps across the …(3)….\n\nMost lightning never reaches the ground; it flashes within a cloud or between clouds. When it does strike the ground, it tends to hit tall, …(4)… objects such as trees, towers and isolated buildings. The popular saying that lightning never strikes the same place twice is simply …(5)…: tall structures can be struck many times in a single year.\n\nBecause light travels much faster than sound, we see a flash before we hear its thunder. Counting the seconds between the two gives a rough …(6)… of how far away the storm is: about three seconds for every kilometre. If the gap is shrinking, the storm is …(7)….\n\nWeather services advise that if you can hear thunder, you are close enough to be struck. The safest place is inside a building or a hard-topped car, …(8)… from windows and plumbing until the storm has passed.',
      gaps: [
        [['expands', 'shrinks', 'freezes', 'settles'], 0, 'Heated suddenly, the air “expands” so fast that it makes a shock wave. Shrinks is the opposite of what heating does.', [null, 'heating makes air expand, not shrink', 'the air is heated, not frozen', 'settling is too gentle to make a shock wave']],
        [['gather', 'escape', 'melt', 'scatter'], 0, 'The heavier particles “gather” lower down, separating the charges. Scatter is the opposite: separation needs them to collect in one region.', [null, 'they stay in the cloud', 'melting does not explain the charge', 'scattering would not separate the charges']],
        [['gap', 'sky', 'cloud', 'storm'], 0, 'The spark jumps across the “gap” between the charged regions. Cloud is the nearest rival, but the spark crosses the space between charges, not the whole cloud.', [null, 'too general', 'the spark crosses the space between charges', 'too general']],
        [['exposed', 'hidden', 'heavy', 'colourful'], 0, 'Tall, “exposed” objects stand out in the open. Heavy is the nearest rival, but weight does not attract lightning; height and openness do.', [null, 'hidden objects are less likely to be hit', 'weight does not attract lightning', 'colour is irrelevant']],
        [['untrue', 'unclear', 'unkind', 'unlucky'], 0, 'Tall structures can be struck many times, so the saying is “untrue”. Unclear is the nearest rival, but the saying is clear; it is just wrong.', [null, 'the saying is clear, just wrong', 'kindness is irrelevant', 'luck is not the point']],
        [['estimate', 'answer', 'record', 'reason'], 0, 'Counting gives a rough “estimate” of distance. Answer is the nearest rival, but “rough” goes with estimate.', [null, '“rough” goes with estimate', 'a record is something kept, not worked out', 'counting does not give a reason']],
        [['approaching', 'ending', 'turning', 'freezing'], 0, 'A shrinking gap means the storm is getting closer: “approaching”. Ending is the nearest rival, but a closer storm is not necessarily ending.', [null, 'getting closer is not ending', 'turning does not follow from a shrinking gap', 'temperature is irrelevant']],
        [['away', 'apart', 'aside', 'across'], 0, '“Away from windows and plumbing” means keeping a distance from them. Apart is the nearest rival, but “apart from windows” means “except for windows”.', [null, '“apart from” means “except for”', '“aside from” means “except for”', '“across from” means opposite']],
      ] }),

    readS3({ id: 'M02-s3', headnote: 'This poem is spoken by the daughter of a lighthouse keeper.', title: 'The Keeper’s Daughter',
      lines: [
        'My father knew the weather by its first word.',
        'He’d stand outside at dusk and taste the air',
        'the way you’d taste a soup to check the salt,',
        'then climb the hundred steps and light the glass.',
        '',
        'He told me ships were people who had trusted',
        'a stranger’s promise that the rocks were here.',
        'Our light, he said, was not to show the way.',
        'It was to show the way was not this way.',
        '',
        'I learned to sleep through gales. I learned the clock',
        'of turning light across my bedroom ceiling,',
        'eleven seconds dark, and then the sweep,',
        'like someone checking that I hadn’t moved.',
        '',
        'They run it from the mainland now. A box',
        'that clicks and hums does all that he once did.',
        'It never tastes the air. It never climbs.',
        'And no one sleeps beneath it any more.',
      ],
      questions: [
        Q('What does “knew the weather by its first word” (line 1) suggest about the father?', ['He could predict the weather from the earliest signs.', 'He spoke to the weather.', 'He wrote weather reports.', 'He disliked bad weather.'], 0,
          'Like someone who recognises a voice from one word, he read the weather from its earliest signs. Speaking to the weather is the nearest rival, but the image is about recognising, not talking.',
          [null, 'the image is about recognising, not talking', 'no reports are mentioned', 'no dislike is shown']),
        Q('The comparison in lines 2–3 suggests that the father', ['was a skilled cook.', 'judged the weather with care and experience.', 'was often hungry at work.', 'found the sea air unpleasant.'], 1,
          'Tasting the air like checking soup for salt shows a practised, careful judgement. Being a skilled cook is the nearest rival, but the comparison describes how he judged the air.',
          ['the comparison describes how he judged the air', null, 'hunger is not suggested', 'nothing suggests he disliked it']),
        Q('What does the father mean in lines 7–8?', ['The light guided ships into harbour.', 'The light warned ships away from danger rather than guiding them.', 'The light was too weak to be useful.', 'The light was only for the keeper’s family.'], 1,
          'The light shows “the way was not this way”: it marks where the rocks are so ships keep clear. Guiding ships into harbour is the very idea he corrects.',
          ['this is the idea he corrects', null, 'nothing suggests weakness', 'it was for ships']),
        Q('How does the speaker feel about the turning light in the third stanza?', ['Frightened by it.', 'Comforted, as though it were watching over her.', 'Annoyed that it kept her awake.', 'Confused by its timing.'], 1,
          'She compares the sweep to “someone checking that I hadn’t moved” — a protective presence. Annoyed is the nearest rival, but she says she learned to sleep through gales and treats the light as a gentle routine.',
          ['nothing suggests fear', null, 'she learned to sleep with it', 'she knows its timing exactly']),
        Q('What contrast is made in the final stanza?', ['Between the old light and a new, brighter one.', 'Between the father’s care and a machine that only does the job.', 'Between the mainland and the island.', 'Between day and night.'], 1,
          'The box “does all that he once did” but “never tastes the air … never climbs”: it lacks his care and presence. The mainland and the island is the nearest rival, but those places are only where the control is, not the contrast that matters.',
          ['brightness is not compared', null, 'these are only where the control is', 'day and night are not contrasted here']),
        Q('Which word best describes the tone of the last line?', ['triumphant', 'regretful', 'angry', 'amused'], 1,
          '“No one sleeps beneath it any more” mourns a lost way of life. Angry is the nearest rival, but the line is quiet and sad rather than bitter.',
          ['nothing is celebrated', null, 'the line is quiet rather than bitter', 'nothing is funny']),
      ] }),

    readS4({ id: 'M02-s4', title: 'Money that is not money',
      paras: [
        'For most of history, money was something valuable in itself. Coins were made of gold, silver or copper, and a coin was worth roughly the value of its metal. ...(1)...',
        'Paper money began in China more than a thousand years ago. Merchants who carried heavy strings of coins began leaving them with trusted dealers in exchange for written receipts. ...(2)... Eventually the government took over the printing of these notes.',
        'In Europe, paper money spread much later. ...(3)... A goldsmith’s note was simply a promise that the bearer could collect a certain amount of gold on demand.',
        'Over time, people stopped bothering to collect the gold. ...(4)... By the twentieth century, most countries had cut the link between their money and gold altogether.',
        'Today, a banknote is worth something only because people agree that it is. ...(5)... If people lose that trust, as has happened during some financial crises, money can lose its value very quickly.',
        '...(6)... Much of the money people use now never appears as notes at all, but moves as numbers between bank accounts. The coins and paper in our pockets are only a small fraction of the whole.',
      ],
      sentences: [
        'This made it easy to trust, but awkward to carry in large amounts.',
        'The receipts were lighter, and soon people were using them to pay for things directly.',
        'It grew out of the receipts that goldsmiths gave to customers who stored gold with them.',
        'As long as they trusted the note could be exchanged, the note itself was good enough.',
        'Shops, workers and governments all accept it, so it can be spent.',
        'In fact, even paper money is becoming less common.',
        'Gold was first discovered in Australia in the 1850s.',
      ],
      answers: [0, 1, 2, 3, 4, 5],
      explains: [
        'After explaining that coins held their own value, the gap gives the advantage (easy to trust) and the problem (awkward to carry) that leads into paper money.',
        'Merchants exchanged coins for receipts; the gap explains that the lighter receipts came to be used as payment, which led to government notes.',
        'The next sentence explains a goldsmith’s note, so the gap must first say that European paper money grew out of goldsmiths’ receipts.',
        '“People stopped bothering to collect the gold” is explained by trust: the note was good enough as long as it could be exchanged.',
        'A note is worth something because people agree it is; the gap shows what that agreement looks like in practice.',
        'The final paragraph is about money that never appears as notes, so it opens by saying paper money itself is becoming less common. The sentence about Australian gold is the extra one.',
      ] }),

    readS5({ id: 'M02-s5', headnote: 'Four writers describe mountains.',
      extracts: [
        { title: 'Extract A', paras: ['Mountains form mainly where the plates that make up the Earth’s crust push against each other. When two plates collide, the rock between them crumples and is forced upwards, much as a rug wrinkles when it is pushed against a wall. The Himalayas are still rising by a few millimetres a year as the Indian plate continues to push into Asia.'] },
        { title: 'Extract B', paras: ['We reached the summit an hour after dawn, and I had expected to feel triumphant. Instead I felt small. The cloud lay below us like a second sea, with other peaks standing out of it as islands, and the silence was so complete that I could hear my own heartbeat. My brother, who had complained the whole way up, said nothing at all, which was the most remarkable thing that happened that day.'] },
        { title: 'Extract C', paras: ['Climbing permits for the world’s highest peaks should be strictly limited. Every season, hundreds of climbers queue on the same narrow ridges, leaving behind tonnes of rubbish and putting guides and rescuers at risk. A mountain is not a theme park, and treating it like one is dangerous for everyone on it.'] },
        { title: 'Extract D', paras: ['In many cultures mountains have been treated as sacred. Some peaks have never been climbed, not because they are too difficult but because the people who live beneath them ask that they be left alone. For these communities, the question is not whether a summit can be reached but whether it should be.'] },
      ],
      items: [
        ['compares the formation of mountains to something in a home?', 'A', 'A compares crumpling rock to a rug wrinkling against a wall. B compares cloud to a sea, which is not in a home.'],
        ['describes a feeling the writer did not expect?', 'B', 'The writer expected to feel triumphant but felt small. D describes a point of view, but no unexpected feeling.'],
        ['argues that the number of climbers should be controlled?', 'C', 'C says climbing permits should be strictly limited. D describes peaks left unclimbed, but argues for no limit on permits.'],
        ['mentions mountains that are left unclimbed out of respect?', 'D', 'D says some peaks are left alone at the request of the people who live beneath them. C argues for limits, but because of danger and rubbish, not respect.'],
        ['says that some mountains are still growing?', 'A', 'A says the Himalayas are still rising by a few millimetres a year. No other extract mentions mountains growing.'],
        ['describes a person whose silence surprised the writer?', 'B', 'The complaining brother fell silent at the top, “the most remarkable thing that happened”. D mentions people asking for peaks to be left alone, not silence.'],
        ['mentions the danger to people who help climbers?', 'C', 'C says crowded climbs put guides and rescuers at risk. B describes a climb but no danger to helpers.'],
        ['suggests a question about whether something ought to be done?', 'D', 'D says the question is whether a summit “should” be reached, not whether it can. C argues firmly rather than raising a question.'],
        ['uses a comparison to describe the view from the top?', 'B', 'B describes the cloud as “a second sea” with peaks as islands. A uses a comparison, but to explain how mountains form.'],
        ['describes the harm caused by crowds?', 'C', 'C mentions queues, tonnes of rubbish and risk to rescuers. D mentions communities, but not crowds.'],
      ] }),
  ],

  thinking: [
    TS('strengthen', 'A town council says: “Lowering the speed limit near the shopping centre to 40 km/h will reduce accidents there.”',
      'Which one of these statements, if true, most strengthens the council’s claim?',
      ['In other towns where the limit near shops was lowered to 40 km/h, accidents fell, while in similar towns that kept the old limit they did not.', 'Most drivers obey speed limits.', 'The shopping centre is busiest on Saturdays.', 'Some drivers find low speed limits frustrating.'], 0,
      'A comparison with similar towns that kept the old limit shows the lower limit made the difference. Most drivers obeying limits is the nearest rival: it helps, but it does not show that slower speeds reduce accidents.',
      [null, 'obeying the limit does not show it reduces accidents', 'busy days do not support the claim', 'frustration does not support the claim']),
    TS('weaken', 'Hana argues: “Students should not be given homework in primary school. A study found that primary students who did more homework did not get better test results.”',
      'Which one of these statements, if true, most weakens Hana’s argument?',
      ['The same study found that students who did homework developed better study habits that helped them in high school.', 'Some parents help with homework.', 'Many students dislike homework.', 'The study was carried out in Australia.'], 0,
      'If homework builds habits that pay off later, it may be worth giving even without better test results now. Students disliking homework is the nearest rival in topic, but it supports Hana.',
      [null, 'this does not show homework is worthwhile', 'this supports Hana', 'where it was done does not affect the argument']),
    WR('In a school quiz, teams score 3 points for a correct answer. If a team answers a question wrongly, the other team may try it for 1 point. No other points are given.\nEva: “Team Blue scored 7 points, so they must have answered at least one question that another team got wrong.”\nTom: “Team Red scored 9 points, so they did not answer any questions that another team got wrong.”',
      'Eva', 'Tom', true, false,
      'Eva is right: 7 cannot be made from 3s alone, so Blue must have earned at least one 1-point answer. Tom is wrong: 9 could be 3 + 3 + 1 + 1 + 1, so Red may have picked up some 1-point answers.'),
    TS('flaw', 'A newspaper says: “Nine out of ten people who use Shinee toothpaste have healthy teeth. So Shinee toothpaste gives you healthy teeth.”',
      'Which one of the following shows the mistake in this reasoning?',
      ['People who care for their teeth in other ways might also be the ones who choose Shinee, and nothing is said about people using other toothpastes.', 'Some people do not like the taste of Shinee.', 'Healthy teeth are important.', 'Shinee toothpaste might be expensive.'], 0,
      'Without knowing how many users of other toothpastes have healthy teeth, and whether Shinee users brush more carefully, the figure proves nothing. Taste is the nearest rival in topic, but it does not touch the reasoning.',
      [null, 'taste does not touch the reasoning', 'this does not show the mistake', 'price does not show the mistake']),
    TS('assumption', 'Jae says: “Our team should practise on the school oval instead of the park, because the oval is closer, so we will have more time to practise.”',
      'Which one of the following is an assumption Jae has made?',
      ['The oval will be free for the team to use at practice times.', 'The park is too far away to walk.', 'The team wants to practise more.', 'The oval has better grass.'], 0,
      'Being closer only gives more practice time if the team can actually use the oval when it practises. The park being too far to walk is the nearest rival, but Jae only says the oval is closer.',
      [null, 'Jae only says the oval is closer', 'Jae’s reasoning does not depend on this', 'grass quality is not part of the reasoning']),
    TS('weaken', 'The manager of a cinema says: “Our new reclining seats have made customers happier. Since they were installed, ticket sales have risen by twenty per cent.”',
      'Which one of these statements, if true, most weakens the manager’s argument?',
      ['The seats were installed in the same month that the only other cinema in town closed down.', 'Reclining seats are more expensive than ordinary seats.', 'Some customers fall asleep in reclining seats.', 'The cinema also sells popcorn.'], 0,
      'If the town’s other cinema closed at the same time, the rise in sales may simply be its customers coming here. Customers falling asleep is the nearest rival, but it does not explain the rise in sales.',
      [null, 'cost does not explain the rise', 'this does not explain the rise in sales', 'popcorn does not explain the rise']),
    WR('In a game, a card can be played only if it matches the colour or the number of the card on top of the pile. The top card is a red 7.\nKai: “I am holding a green 7, so I can play it.”\nSara: “I cannot play my card, so it must be neither red nor a 7.”',
      'Kai', 'Sara', true, true,
      'Both are right. A green 7 matches the number, so it can be played. And a card that cannot be played matches neither the colour nor the number, so it is neither red nor a 7.'),
    TS('strengthen', 'Leila believes that the new pedestrian crossing outside her school has made it safer for students to cross the road.',
      'Which one of these statements, if true, most strengthens Leila’s belief?',
      ['Since the crossing was built, there have been no near misses involving students, compared with several each term before.', 'The crossing is painted with bright stripes.', 'Some students still cross away from the crossing.', 'The road is busy in the mornings.'], 0,
      'A fall in near misses after the crossing was built is direct evidence of greater safety. Bright stripes is the nearest rival: it suggests the crossing is visible, but not that it has made crossing safer.',
      [null, 'visibility does not show it is safer in practice', 'this counts against her belief', 'traffic levels do not show the crossing helped']),
    TS('flaw', 'Ian says: “I asked ten people at the skate park whether the council should build a new skate ramp, and all ten said yes. So most people in our town want a new skate ramp.”',
      'Which one of the following shows the mistake Ian has made?',
      ['People at a skate park are likely to want a skate ramp, so they do not represent the whole town.', 'Ten people is quite a lot.', 'Skate ramps can be dangerous.', 'Ian might have asked the same person twice.'], 0,
      'Ian only asked people who already use the skate park, so their views do not represent the town. Asking the same person twice is the nearest rival, but it questions his method of counting, not the choice of people.',
      [null, 'this does not show the mistake', 'danger does not affect the reasoning', 'this questions his counting, not the choice of people']),
    TS('conclusion', 'Every student in Room 5 owns a bike or a scooter, but nobody owns both. 14 students own a bike. There are 23 students in Room 5.',
      'Which one of the following must be true?',
      ['Exactly 9 students in Room 5 own a scooter.', 'More students own scooters than bikes.', 'At least 14 students own a scooter.', 'Some students in Room 5 own both a bike and a scooter.'], 0,
      'Everyone owns exactly one of the two, so 23 − 14 = 9 own a scooter. That more students own scooters is false, because 9 is fewer than 14.',
      [null, '9 is fewer than 14', 'only 9 own a scooter', 'nobody owns both']),
    WR('All the members of the debating team are in Year 6. Some members of the debating team are also in the school choir. Nobody in the choir plays in the school band.\nRahul: “Some Year 6 students are not in the band.”\nTessa: “No member of the debating team plays in the band.”',
      'Rahul', 'Tessa', true, false,
      'Rahul is right: the debaters who sing in the choir are in Year 6 and cannot be in the band. Tessa is wrong: only some debaters are in the choir; the others might play in the band.'),
    TS('weaken', 'Matilda argues: “Our school should replace all its library books with e-books. E-books take up no space, and students prefer reading on screens.”',
      'Which one of these statements, if true, most weakens Matilda’s argument?',
      ['A survey of the school’s students found that most of them prefer printed books for reading for pleasure.', 'E-books can be read at night.', 'Some printed books are very old.', 'The library is quite small.'], 0,
      'Her argument rests partly on students preferring screens; a survey of these very students showing the opposite undercuts it. The library being small is the nearest rival, but it supports her point about space.',
      [null, 'this supports e-books', 'old books do not weaken her argument', 'this supports her point about space']),
    TS('assumption', 'Oliver says: “I will save money by buying the large bottle of juice, because it costs less per litre than the small bottles.”',
      'Which one of the following is an assumption Oliver has made?',
      ['He will drink all of the juice before it goes off.', 'The large bottle is easier to carry.', 'He likes the flavour of the juice.', 'The small bottles are made of plastic.'], 0,
      'A lower price per litre only saves money if none of the juice is wasted. Liking the flavour is the nearest rival, but it does not affect whether he saves money.',
      [null, 'carrying is irrelevant to saving money', 'flavour does not affect the saving', 'the material is irrelevant']),
    TS('strengthen', 'A scientist claims that a particular kind of bird has learned to avoid a new road by flying higher when crossing it.',
      'Which one of these statements, if true, most strengthens the scientist’s claim?',
      ['Birds of this kind now fly much higher over the road than they did when it first opened, while their flight height elsewhere has not changed.', 'The road is very busy.', 'Birds of this kind are common in the area.', 'Many birds are killed on roads each year.'], 0,
      'A change in flight height only over the road, not elsewhere, suggests the birds have responded to the road itself. Many birds being killed on roads is the nearest rival, but it does not show this kind has learned anything.',
      [null, 'traffic levels do not show learning', 'being common does not show learning', 'this does not show these birds have learned']),
    WR('A theatre allows children under 8 in only if they are with an adult. Nobody is allowed in after the show has started.\nAmara: “Lily is 6 and is inside watching the show, so she must have come in with an adult before the show started.”\nJosh: “Mia came in with an adult, so she must be under 8.”',
      'Amara', 'Josh', true, false,
      'Amara is right: a 6-year-old can only come in with an adult, and nobody comes in after the start. Josh is wrong: children aged 8 or over may also come with an adult.'),
    TS('flaw', 'Priya says: “Our school canteen sells more pies on cold days. So if the canteen sells more pies, the weather will turn cold.”',
      'Which one of the following shows the mistake Priya has made?',
      ['She has reversed the cause: cold weather leads to pie sales, not the other way round.', 'Pies are unhealthy.', 'The canteen might run out of pies.', 'Some students bring their lunch from home.'], 0,
      'Cold weather makes students buy pies; selling pies cannot change the weather. The canteen running out is the nearest rival, but it does not describe the mistake.',
      [null, 'health is irrelevant', 'this does not describe the mistake', 'this does not describe the mistake']),
  ],

  writing: {
    title: 'A letter to the council', genre: 'persuasive',
    stimulus: ['Your local council is deciding whether to turn an empty block of land near your school into a car park or a community garden.'],
    prompt: 'Write a letter to your local council persuading them to choose one of these options.',
    guidance: ['Set out your letter as a letter, with a greeting and a sign-off.', 'Choose one option and give reasons a council would care about: cost, safety, the community.', 'Acknowledge the strongest reason for the other option and explain why yours is still better.'],
    rubricNotes: 'A strong response uses the conventions of a formal letter, chooses reasons that would matter to the council, deals with the opposing option fairly, and keeps a respectful but confident tone.',
  },
});
