/* Medium Exam 3 — original content written for this site. */
'use strict';
defExam('M03', {
  reading: [
    readS1({ id: 'M03-s1', headnote: 'Two writers describe a grandparent who came to Australia from another country.',
      extracts: [
        { label: 'Extract A', paras: [
          'My grandfather arrived in Melbourne in 1958 with one suitcase and the address of a cousin who, it turned out, had moved to Adelaide. He spent his first night in a church hall. He liked to tell this part of the story as if it were the funny beginning of a film, and perhaps by then it was; but my grandmother told me once, when he was out of the room, that he had not laughed about it for a long time.',
          'He found work building roads in the Snowy Mountains, where the men in his camp spoke nine languages and agreed on almost nothing except that the food was terrible. He learned English from the foreman’s shouting and from a children’s dictionary he bought for a shilling. Years later, when he had a house and a garden and grandchildren, he still kept the dictionary on the shelf by his bed. Its cover had come off. He never replaced it.',
        ] },
        { label: 'Extract B', paras: [
          'Nonna never learned much English and never seemed to think she needed to. She communicated with the neighbourhood through food. A new family in the street would find a dish of something wrapped in a tea towel on their step; a widower would find soup; children who threw a ball over her fence would get it back with a biscuit balanced on top.',
          'I used to be embarrassed by her. My friends’ grandmothers wore jeans and drove cars. Mine wore black and walked everywhere with a string bag. It took me until I was nearly grown to understand that everyone in our street knew her, and that most of them, if they were in trouble, would have knocked on her door before they knocked on ours.',
        ] },
      ],
      questions: [
        Q('Why does the grandmother in Extract A tell the narrator that the grandfather “had not laughed about it for a long time”?', ['To show that he had a poor sense of humour.', 'To show that the story had been painful before it became funny.', 'To correct a mistake in the story.', 'To suggest that the story was not true.'], 1,
          'Her remark shows that his first night alone was hard at the time and only became a funny story much later. That the story was not true is the nearest rival, but she does not doubt what happened, only how he felt about it.',
          ['he does laugh about it now', null, 'no fact in the story is corrected', 'she does not doubt what happened']),
        Q('What does the narrator suggest by describing the camp as a place where the men “agreed on almost nothing except that the food was terrible”?', ['The men often fought with each other.', 'The men came from very different backgrounds but shared some common ground.', 'The camp cook was new.', 'The men were planning to leave.'], 1,
          'Speaking nine languages, they disagreed about most things, but a shared complaint united them — said with humour. Fighting is the nearest rival, but the tone is light, and disagreeing is not fighting.',
          ['disagreeing is not the same as fighting', null, 'nothing is said about the cook', 'nobody plans to leave']),
        Q('Why does the grandfather keep the children’s dictionary by his bed?', ['He still needs it to understand English.', 'It reminds him of how far he has come.', 'He plans to give it to his grandchildren.', 'It is valuable to collectors.'], 1,
          'Kept for years after he had a house, garden and grandchildren, the worn dictionary is a reminder of his hard beginning. Still needing it is the nearest rival, but by then he had lived in Australia for many years.',
          ['he has lived in Australia for many years', null, 'no gift is mentioned', 'its cover is missing, so it is not valuable']),
        Q('What does “He never replaced it” (the final sentence of Extract A) suggest?', ['He could not afford a new dictionary.', 'The worn dictionary mattered to him as it was.', 'He no longer read books.', 'The dictionary was out of print.'], 1,
          'He kept it even without a cover because it held meaning for him. Not being able to afford one is the nearest rival, but by then he had a house and garden.',
          ['by then he had a house and garden', null, 'the passage says nothing about his reading', 'nothing suggests this']),
        Q('In Extract B, how does Nonna communicate with her neighbours?', ['Through her grandchild, who translates.', 'Through gifts of food.', 'By writing notes.', 'By visiting their homes to talk.'], 1,
          'She “communicated with the neighbourhood through food”: dishes, soup and biscuits. Visiting their homes is the nearest rival, but she leaves food on doorsteps rather than going in to talk.',
          ['no translation is described', null, 'no notes are mentioned', 'she leaves food on doorsteps rather than visiting']),
        Q('What does the detail about the ball coming back “with a biscuit balanced on top” show about Nonna?', ['She was annoyed by the children.', 'She was kind and generous even to children who caused her trouble.', 'She wanted the children to stay away.', 'She was a good cook.'], 1,
          'Instead of complaining about the ball, she returns it with a treat. Being a good cook is the nearest rival, but the detail is about kindness rather than cooking skill.',
          ['returning the ball with a treat is not annoyance', null, 'a treat would encourage them, not keep them away', 'the detail is about kindness, not cooking skill']),
        Q('How does the narrator’s view of Nonna change in Extract B?', ['From pride to embarrassment.', 'From embarrassment to understanding how valued she was.', 'From fear to affection.', 'From respect to pity.'], 1,
          'The narrator was embarrassed by her black clothes and string bag, then realised the whole street knew and trusted her. Pride to embarrassment is the change in the wrong direction.',
          ['the change goes the other way', null, 'the narrator was never afraid', 'the narrator never pities her']),
        Q('Which statement is true of both grandparents?', ['They both learned English quickly.', 'They both found their own way of belonging in a new country.', 'They both lived in the Snowy Mountains.', 'They both embarrassed their grandchildren.'], 1,
          'The grandfather worked and learned English; Nonna belonged through food and kindness. Embarrassing their grandchildren is the nearest rival, but only Nonna’s grandchild says this.',
          ['Nonna never learned much English', null, 'only the grandfather worked there', 'only Nonna’s grandchild was embarrassed']),
      ] }),

    readS2({ id: 'M03-s2', title: 'The lyrebird',
      text: 'The superb lyrebird, found in the forests of south-eastern Australia, is famous as one of the finest mimics in the animal world. A male may spend much of the winter on a cleared mound of earth, …(1)… the calls of a dozen or more other species in a single performance.\n\nHis repertoire is not random. Each bird learns its songs from older lyrebirds and from the forest around it, so birds in different areas have …(2)… different collections of sounds. Recordings made decades apart show that some sequences have been passed down through many generations, a kind of …(3)… tradition.\n\nStories of lyrebirds copying chainsaws, car alarms and camera shutters are widely shared, and a few are genuine. Most such recordings, however, come from birds raised in captivity or kept near busy places. In the wild, lyrebirds overwhelmingly …(4)… other birds.\n\nThe male’s display serves a clear purpose: to …(5)… a female. As he sings, he throws his long, lacy tail feathers forward over his head so that they shimmer like a silver veil. Females seem to prefer males whose imitations are most …(6)…, which may explain why the skill has become so refined.\n\nLyrebirds also …(7)… a quieter role in the forest. As they scratch through the leaf litter for insects, they turn over enormous amounts of soil each year, helping fallen leaves break down and reducing the fuel for bushfires. A bird best known for its voice may be just as important for what it does with its …(8)….',
      gaps: [
        [['imitating', 'ignoring', 'learning', 'answering'], 0, 'On his mound the male performs, “imitating the calls” of other species. Learning is the nearest rival, but in a performance he is showing what he already knows.', [null, 'he copies the calls rather than ignoring them', 'in a performance he shows what he has already learned', 'he is copying, not replying']],
        [['noticeably', 'exactly', 'hardly', 'equally'], 0, 'Birds learn from their own area, so different areas have “noticeably different” collections. Exactly is the nearest rival, but “exactly different” is not natural English.', [null, '“exactly different” is not natural', '“hardly different” contradicts the point', '“equally different” does not make sense here']],
        [['musical', 'secret', 'modern', 'written'], 0, 'Sequences handed down through generations make a “musical tradition”. Secret is the nearest rival, but the songs are sung openly.', [null, 'the songs are sung openly', 'the tradition spans decades, so it is not modern', 'birds do not write']],
        [['copy', 'avoid', 'chase', 'feed'], 0, 'The contrast with chainsaws and alarms shows that wild birds mostly “copy other birds”. Avoid is the nearest rival in form, but the paragraph is about what they imitate.', [null, 'the paragraph is about what they imitate', 'chasing is not the subject', 'feeding is not the subject']],
        [['attract', 'warn', 'feed', 'defeat'], 0, 'The display is aimed at females: to “attract a female”. Defeat is the nearest rival, but it would describe a contest with a rival male.', [null, 'warning is not the purpose', 'feeding is not the purpose', 'defeat suggests fighting a rival male']],
        [['accurate', 'loud', 'short', 'recent'], 0, 'A preference for males whose imitations are most “accurate” would explain why the skill “has become so refined”. Loud is the nearest rival, but loudness would not make the skill more refined.', [null, 'loudness would not make the skill more refined', 'short imitations would not explain the refinement', 'recent is not a quality of an imitation']],
        [['play', 'make', 'hide', 'lose'], 0, 'Animals “play a role”. Make is the nearest rival, but “make a role” is not the usual phrase.', [null, '“make a role” is not the usual phrase', 'the role is described openly', 'nothing is lost']],
        [['feet', 'tail', 'beak', 'wings'], 0, 'Scratching the soil is done with its “feet”, contrasting with its voice. Tail is the nearest rival, since the tail was described earlier, but the tail is for display, not scratching.', [null, 'the tail is for display, not scratching', 'the passage says they scratch, which is done with feet', 'wings are not used for scratching']],
      ] }),

    readS3({ id: 'M03-s3', headnote: 'In this poem the speaker looks out over a city at night from a high window.', title: 'Night Shift',
      lines: [
        'From up here the city is a circuit board',
        'someone forgot to switch off: lines of light',
        'that run along the highways, junctions where',
        'the colours change, and here and there a square',
        'of window, like a chip that’s still awake.',
        '',
        'In one of them a nurse is pulling on',
        'her coat to go to work. In one, a baker',
        'is shaping bread that you will eat tomorrow.',
        'In one, a student who has left it late',
        'is learning, all at once, a term of maths.',
        '',
        'I cannot see them. I invent them all.',
        'But someone made the lights, and someone keeps',
        'them burning while the rest of us are sleeping,',
        'and when I turn away to go to bed',
        'I find I want to thank them, though I can’t.',
      ],
      questions: [
        Q('Why does the speaker compare the city to “a circuit board / someone forgot to switch off”?', ['The city is full of computers.', 'Its lines and points of light look like the patterns on an electronic board.', 'The city has lost its electricity.', 'The speaker works in a factory.'], 1,
          'Highways as lines, junctions and lit windows look like the tracks and chips of a circuit board. A city full of computers is the nearest rival, but the comparison is about appearance from above.',
          ['the comparison is about appearance from above', null, 'the lights are on', 'the speaker’s job is not given']),
        Q('In the first stanza, a lit window is compared to', ['a highway.', 'a chip that is still awake.', 'a junction.', 'a square of colour.'], 1,
          'A window is “like a chip that’s still awake”. A square of colour is the nearest rival, because the window is called a square, but the comparison is to a chip.',
          ['highways are the lines of light', null, 'junctions are where colours change', 'the window is a square, but it is compared to a chip']),
        Q('What do the people described in the second stanza have in common?', ['They all work in hospitals.', 'They are all awake at night while others sleep.', 'They are all students.', 'They all live in the same building.'], 1,
          'The nurse, the baker and the student are all busy at night. All working in hospitals is the nearest rival, but only the nurse does.',
          ['only the nurse works in a hospital', null, 'only one is a student', 'they are in different windows']),
        Q('Why does the speaker mention that the student has “left it late”?', ['To criticise the student’s laziness.', 'To add a touch of humour to the picture of the night.', 'To show the student is a night-shift worker.', 'To explain why the windows are lit.'], 1,
          'Learning “a term of maths” “all at once” is a gently comic picture. Criticising laziness is the nearest rival, but the tone is warm rather than critical.',
          ['the tone is warm rather than critical', null, 'the student is cramming, not working a shift', 'many windows are lit for other reasons']),
        Q('What does “I cannot see them. I invent them all” (line 11) reveal?', ['The speaker can see into every window.', 'The people described are imagined by the speaker.', 'The speaker is a novelist.', 'The city is empty.'], 1,
          'The speaker admits the nurse, baker and student are imagined. Being a novelist is the nearest rival, but inventing these people does not make the speaker a writer by profession.',
          ['the speaker says they cannot see them', null, 'inventing them does not make the speaker a novelist', 'the lights show the city is not empty']),
        Q('What feeling does the speaker express at the end of the poem?', ['Fear of the dark.', 'Gratitude towards people who work while others sleep.', 'Envy of the people who are awake.', 'Boredom with the view.'], 1,
          'The speaker wants “to thank them, though I can’t”. Envy is the nearest rival, but the speaker shows thanks, not a wish to be in their place.',
          ['the dark is not feared', null, 'the speaker shows thanks, not envy', 'the speaker is absorbed in the view']),
      ] }),

    readS4({ id: 'M03-s4', title: 'Turning wind into power',
      paras: [
        'A modern wind turbine is one of the largest machines most people will ever see. Its blades can be longer than a jumbo jet’s wings, and its tower may stand taller than a thirty-storey building. ...(1)...',
        'The basic idea is old. ...(2)... A modern turbine works on the same principle: the wind pushes on the blades, the blades turn a shaft, and the turning shaft drives a generator that produces electricity.',
        'Height matters because wind is stronger and steadier further from the ground. ...(3)... That is why turbines have grown taller over the years, and why many are now built at sea, where there are no hills or trees to slow the air.',
        'Wind power has one obvious weakness. ...(4)... Power companies deal with this by combining wind with other sources, by spreading turbines over large areas so that some are always turning, and increasingly by storing energy in large batteries.',
        'Turbines also have critics. ...(5)... Supporters reply that careful placement, away from migration routes and homes, can reduce these problems, and that the harm caused by burning coal is far greater.',
        '...(6)... For a source of energy that was once seen as a curiosity, it has come a very long way.',
      ],
      sentences: [
        'Yet all this size exists for one simple purpose: to catch moving air.',
        'Windmills have been used to grind grain and pump water for well over a thousand years.',
        'A small increase in wind speed produces a much larger increase in power.',
        'The wind does not always blow.',
        'Some people object to their appearance and noise, and birds and bats can be killed by the blades.',
        'Today wind provides a large and growing share of the world’s electricity.',
        'Solar panels are cheaper to install on houses.',
      ],
      answers: [0, 1, 2, 3, 4, 5],
      explains: [
        'After describing the turbine’s great size, the gap explains what the size is for: catching moving air.',
        '“The basic idea is old” is supported by windmills grinding grain for over a thousand years, before “A modern turbine works on the same principle”.',
        'Stronger wind higher up matters because a small rise in wind speed gives a much bigger rise in power, which explains why turbines have grown taller.',
        '“One obvious weakness” is that the wind does not always blow; the next sentence describes how companies deal with gaps in supply.',
        '“Turbines also have critics” is followed by the criticisms (appearance, noise, birds), which supporters then answer.',
        'The final paragraph’s “it has come a very long way” follows the claim that wind now provides a large share of electricity. The sentence about solar panels is the extra one.',
      ] }),

    readS5({ id: 'M03-s5', headnote: 'Four writers discuss collecting things.',
      extracts: [
        { title: 'Extract A', paras: ['People collect for many reasons, but researchers who study collectors find a few that come up again and again: the pleasure of the search, the satisfaction of completing a set, and the sense of control that comes from arranging things in order. Collecting is especially common in childhood, often beginning between the ages of seven and twelve.'] },
        { title: 'Extract B', paras: ['I have collected bottle tops since I was eight. I now have 2,416, sorted by colour in fishing-tackle boxes under my bed. My sister thinks this is the strangest hobby in the world. I point out that she owns forty-one lip balms, and that at least my collection was free.'] },
        { title: 'Extract C', paras: ['Museums should not keep everything they are given. Storerooms around the world are full of objects that will never be displayed or studied, costing money to protect from damp and insects. A museum is not a warehouse, and it would serve the public better by keeping fewer things and showing more of them.'] },
        { title: 'Extract D', paras: ['When my grandmother died, we found that she had kept every birthday card anyone had ever sent her, in shoeboxes labelled by year. Reading them took us a whole weekend. Half the names we did not recognise. By the end, we knew her better than we had when she was alive, and that was a strange thing to feel.'] },
      ],
      items: [
        ['describes reasons that are common among collectors?', 'A', 'A lists the pleasure of the search, completing a set and a sense of control. B gives one person’s experience, not common reasons.'],
        ['includes a playful argument between family members?', 'B', 'B’s sister calls the hobby strange and the writer points to her lip balms. D describes a family, but no argument.'],
        ['argues that some institutions keep too much?', 'C', 'C says museums should not keep everything they are given. A describes collectors, but makes no argument.'],
        ['describes learning about a person through what they kept?', 'D', 'Reading the cards made the family know the grandmother better. B describes a collection, but no one learns about the collector through it.'],
        ['says when collecting often begins?', 'A', 'A says it often begins between seven and twelve. B mentions starting at eight, but does not say when collecting usually begins.'],
        ['gives an exact number of items in a collection?', 'B', 'B says 2,416 bottle tops. D mentions shoeboxes, but gives no exact number.'],
        ['mentions the cost of protecting objects?', 'C', 'C says storerooms cost money to protect from damp and insects. B mentions that the collection was free, which is a different point.'],
        ['describes a collection organised by year?', 'D', 'The cards were in shoeboxes labelled by year. B’s collection is sorted by colour.'],
        ['suggests that keeping fewer things could be better?', 'C', 'C argues museums would serve the public better by keeping fewer things and showing more. A describes collecting without judging it.'],
        ['mentions that arranging things in order can be satisfying?', 'A', 'A mentions the sense of control from arranging things. B sorts by colour but does not say why.'],
      ] }),
  ],

  thinking: [
    TS('strengthen', 'Some scientists believe that koalas in a particular forest are declining because of a disease, rather than because of habitat loss.',
      'Which one of these statements, if true, most strengthens their view?',
      ['The forest has not shrunk in the past twenty years, but tests show that most koalas there carry the disease.', 'Koalas sleep for up to twenty hours a day.', 'Koalas in other forests are also declining.', 'The forest is a popular place for bushwalkers.'], 0,
      'If the forest has not shrunk, habitat loss is unlikely to explain the decline, and widespread disease points to it as the cause. Koalas declining elsewhere is the nearest rival, but it does not separate disease from habitat loss.',
      [null, 'sleep habits do not explain the decline', 'this does not separate disease from habitat loss', 'bushwalkers do not explain it']),
    TS('weaken', 'Callum says: “Our town should ban plastic bags in shops. In the town next door, a ban led to much less plastic rubbish in the creek.”',
      'Which one of these statements, if true, most weakens Callum’s argument?',
      ['Most of the plastic rubbish in our creek comes from a factory upstream, not from shopping bags.', 'Paper bags can tear easily.', 'Some shoppers already bring their own bags.', 'The town next door is smaller than ours.'], 0,
      'If most of the plastic in this creek comes from a factory, banning bags would make little difference here. Some shoppers already bringing bags is the nearest rival, but it does not show the ban would fail.',
      [null, 'this is a small drawback, not a reason the ban would fail', 'this does not show the ban would fail', 'size alone does not show the ban would fail']),
    WR('In a card game, each player is dealt 5 cards from a deck of 20 cards: 5 red, 5 blue, 5 green and 5 yellow.\nMaria: “If I have no red cards, I must have at least two cards of the same colour.”\nTheo: “If I have two red cards, I must have at least two cards of some other colour too.”',
      'Maria', 'Theo', true, false,
      'Maria is right: with no red cards, her 5 cards come from only 3 colours, so two must share a colour. Theo is wrong: his other 3 cards could be one blue, one green and one yellow.'),
    TS('flaw', 'Zara says: “People who drink more water have clearer skin. My brother drinks hardly any water and his skin is clear. So the link between water and skin must be false.”',
      'Which one of the following shows the mistake Zara has made?',
      ['A general link can still be true even if there are exceptions.', 'Her brother might drink other drinks.', 'Clear skin is hard to measure.', 'Some people do not like water.'], 0,
      'A pattern across many people is not disproved by one exception. Her brother drinking other drinks is the nearest rival: it might explain his case, but it does not describe the mistake of using one exception to reject a general link.',
      [null, 'this explains his case but is not the mistake in her reasoning', 'this does not describe her mistake', 'taste is irrelevant']),
    TS('assumption', 'The school says: “We will stop selling lollies at the canteen. This will mean students eat less sugar.”',
      'Which one of the following is an assumption the school has made?',
      ['Students will not simply bring lollies from home or buy them elsewhere instead.', 'Lollies contain sugar.', 'The canteen sells other foods.', 'Students like lollies.'], 0,
      'Removing lollies from the canteen only reduces sugar if students do not replace them from elsewhere. That lollies contain sugar is the nearest rival, but that is a known fact the argument states rather than an unstated assumption.',
      [null, 'this is a known fact, not a hidden assumption', 'other foods are irrelevant', 'liking lollies is not needed for the argument']),
    TS('weaken', 'A study found that people who own dogs live longer on average than people who do not. The researchers concluded that owning a dog helps people live longer.',
      'Which one of these statements, if true, most weakens the researchers’ conclusion?',
      ['People who are already in poor health are much less likely to get a dog.', 'Dogs need to be walked every day.', 'Some dog owners also own cats.', 'Dogs can live for fifteen years.'], 0,
      'If unhealthy people tend not to get dogs, dog owners may live longer simply because they were healthier to begin with. Dogs needing walks is the nearest rival, but it suggests a way dogs might help, which supports the conclusion.',
      [null, 'this supports the conclusion', 'cat ownership does not affect the argument', 'a dog’s lifespan is irrelevant']),
    WR('A school awards a merit certificate only to students who get an A in at least three subjects. Students take five subjects.\nAnil: “Rosa got As in two subjects and Bs in the other three, so she did not get a merit certificate.”\nGrace: “Will got a merit certificate, so he got As in most of his subjects.”',
      'Anil', 'Grace', true, true,
      'Both are right. Certificates go only to students with at least three As, so Rosa, with two, cannot have one. And Will’s certificate means he has at least three As out of five, which is most of his subjects.'),
    TS('strengthen', 'Ming argues that the new traffic lights at Oak Street have reduced waiting times for drivers.',
      'Which one of these statements, if true, most strengthens Ming’s argument?',
      ['Measurements taken at the same times of day show that the average wait has fallen since the lights were changed, while traffic numbers have stayed the same.', 'The new lights use less electricity.', 'Drivers say the new lights look modern.', 'Oak Street is a busy road.'], 0,
      'Measured waits falling while traffic stayed the same shows the lights, not less traffic, made the difference. Drivers saying the lights look modern is the nearest rival, but appearance says nothing about waiting times.',
      [null, 'electricity use is irrelevant to waiting', 'appearance says nothing about waiting times', 'a busy road does not show waits have fallen']),
    TS('flaw', 'Logan says: “All the best chess players I know started playing before they were six. I started at ten, so I can never be one of the best.”',
      'Which one of the following shows the mistake Logan has made?',
      ['The best players Logan knows may not include every great player, and starting early may not be necessary for everyone.', 'Chess is a difficult game.', 'Logan might not enjoy chess.', 'Chess players need to practise.'], 0,
      'Logan assumes that what is true of the players he knows is true of all the best players. Chess being difficult is the nearest rival, but it does not describe the mistake.',
      [null, 'this does not describe the mistake', 'enjoyment is irrelevant to the reasoning', 'practice is not the issue']),
    TS('conclusion', 'At a sports carnival, every student competed in at least one running race. Students who won a running race also competed in the long jump. Jaden did not compete in the long jump.',
      'Which one of the following must be true?',
      ['Jaden competed in a running race but did not win one.', 'Jaden won a running race.', 'Jaden did not compete in any running race.', 'Jaden won the long jump.'], 0,
      'Every student ran at least one race, so Jaden did. Winners also did the long jump, which Jaden did not, so he did not win. That he did not compete in any race contradicts “every student competed”.',
      [null, 'winners also did the long jump', 'every student competed in a race', 'he did not compete in the long jump']),
    WR('In a library, books with a red sticker cannot be borrowed. Books with a blue sticker can be borrowed for one week only. All other books can be borrowed for three weeks. No book has more than one sticker.\nIvy: “I have borrowed this book for three weeks, so it has no sticker.”\nRyan: “This book can be borrowed, so it must have a blue sticker.”',
      'Ivy', 'Ryan', true, false,
      'Ivy is right: red-sticker books cannot be borrowed and blue ones only for a week, so a three-week loan means no sticker. Ryan is wrong: a book with no sticker can be borrowed too.'),
    TS('weaken', 'A principal says: “Students who take part in sport get better marks. So we should make every student play a sport.”',
      'Which one of these statements, if true, most weakens the principal’s argument?',
      ['The students who choose sport tend to be the ones who already find schoolwork easy and have time to spare.', 'Sport is good for health.', 'The school has a large oval.', 'Some students play more than one sport.'], 0,
      'If students who already do well are the ones who choose sport, sport may not be causing the better marks, and forcing others to play might not help. Sport being good for health is the nearest rival, but it supports making students play.',
      [null, 'this supports the plan', 'facilities do not weaken the argument', 'this does not weaken the argument']),
    TS('assumption', 'Ruby says: “I should take the train rather than the bus to the city, because the train is faster.”',
      'Which one of the following is an assumption Ruby has made?',
      ['Getting there quickly matters more to her than other things, such as cost.', 'The train goes to the city.', 'The bus is often late.', 'Trains are more comfortable than buses.'], 0,
      'Choosing the train because it is faster only follows if speed is what matters most to her. The bus often being late is the nearest rival, but it is an extra reason, not an assumption her argument needs.',
      [null, 'she already says the train is faster to the city', 'this is an extra reason, not a hidden assumption', 'comfort is not part of her reasoning']),
    TS('strengthen', 'A gardener claims that a new organic spray protects roses from aphids.',
      'Which one of these statements, if true, most strengthens the gardener’s claim?',
      ['In a test, half the roses in a garden were sprayed and half were not; only the unsprayed roses were badly damaged by aphids.', 'The spray is made from plants.', 'Aphids are small insects.', 'Many gardeners grow roses.'], 0,
      'A fair test with sprayed and unsprayed roses in the same garden shows the spray made the difference. The spray being made from plants is the nearest rival, but being organic does not show it works.',
      [null, 'being organic does not show it works', 'this is a fact about aphids, not evidence', 'popularity is irrelevant']),
    WR('In a tournament, every team plays every other team exactly once. A team gets 2 points for a win, 1 for a draw and 0 for a loss. There are 5 teams.\nOmar: “There are 8 games in the tournament altogether.”\nLiz: “A team that has 8 points must have won all its games.”',
      'Omar', 'Liz', false, true,
      'Liz is right: each team plays 4 games, and the most it can score is 4 × 2 = 8, so 8 points means 4 wins. Omar is wrong: there are 10 different pairs of teams, so 10 games.'),
    TS('flaw', 'Ben says: “The cafeteria’s new menu has more vegetables, and fewer students are buying lunch there. So students do not like vegetables.”',
      'Which one of the following shows the mistake Ben has made?',
      ['Fewer students might be buying lunch for another reason, such as higher prices on the new menu.', 'Vegetables are healthy.', 'Some students bring their own lunch.', 'The menu might change again.'], 0,
      'The drop in sales might come from something else that changed with the menu, such as price. Some students bringing their own lunch is the nearest rival, but that was true before the change too.',
      [null, 'health does not explain the mistake', 'this was true before the change too', 'future changes do not affect the reasoning']),
  ],

  writing: {
    title: 'Should children have mobile phones?', genre: 'discursive',
    stimulus: ['Many children in Year 5 and Year 6 now have their own mobile phone. Some parents think this is sensible; others think it is far too young.'],
    prompt: 'Write a discussion of whether children under twelve should have their own mobile phones. Consider more than one point of view before reaching your own conclusion.',
    guidance: ['Give each side its strongest arguments.', 'Think about when the answer might be different: for which children, and under what conditions.', 'End with a considered judgement, not just a summary.'],
    rubricNotes: 'A strong response treats both sides fairly, makes thoughtful distinctions rather than listing points, and reaches a conclusion that follows from the discussion.',
  },
});
