/* Medium Exam 4 — original content written for this site. */
'use strict';
defExam('M04', {
  reading: [
    readS1({ id: 'M04-s1', headnote: 'In this extract from a story, Kit is playing a small part in the school play when something goes wrong.',
      extracts: [{ paras: [
        'Kit had one line. It came in the second act, after the storm, when the ship’s cook was supposed to stagger on and announce that the water barrels had split. Kit had said it in the shower, on the bus, and once, by accident, to the lady at the bakery. “Captain! The barrels have burst!” Five words. It was not, as her brother had pointed out, a lot to remember.',
        'What nobody had rehearsed was the storm itself collapsing. Halfway through the second act, the painted sea — three metres of canvas on a wooden frame — tipped slowly forward, as if it had decided to see the audience for itself, and lay down across the front of the stage with a sound like a slammed book.',
        'There was a silence of the particular kind that only happens in school halls. Somebody’s little sister laughed. On stage, the captain froze with his telescope halfway to his eye. In the wings, Mr Delaney mouthed something that was probably not in the script.',
        'Kit had not planned to move. Afterwards she could not explain why she did. She simply found herself walking out from the wings, past the frozen captain, to the edge of the fallen sea, where she stood looking down at it with her hands on her hips.',
        '“Captain,” she said, in a voice that carried to the back row, “the barrels have burst — and so, I’m afraid, has the ocean.”',
        'The laugh started at the front and rolled back through the hall like a wave. The captain, who was Rohan from 6B and not known for quick thinking, lowered his telescope and said, “Then we shall have to walk.” And the whole crew stepped over the canvas and marched off, and the curtain came down to the loudest applause of the night.',
        'Kit’s brother, in the car, said it was still only one line. Kit said nothing. She was smiling too hard.',
      ] }],
      questions: [
        Q('What does the opening paragraph suggest about Kit’s attitude to her one line?', ['She thought it was too easy to bother practising.', 'She took it very seriously despite its being short.', 'She kept forgetting it.', 'She wished she had a bigger part.'], 1,
          'She practised it in the shower, on the bus and even said it at the bakery. Wishing for a bigger part is the nearest rival, but nothing suggests she was unhappy with it.',
          ['she practised it constantly', null, 'she remembers it so well she says it by accident', 'nothing suggests she wanted more']),
        Q('What is the effect of describing the painted sea as if it “had decided to see the audience for itself”?', ['It makes the accident seem slow and almost deliberate, which is comic.', 'It shows the scenery was badly built.', 'It explains who knocked it over.', 'It shows the audience were frightened.'], 0,
          'Giving the canvas a will of its own makes its slow fall seem comic. Being badly built is the nearest rival: it may be true, but the description is about the effect, not the construction.',
          [null, 'the description is about effect, not construction', 'nobody knocked it over', 'the audience laugh rather than show fear']),
        Q('“A silence of the particular kind that only happens in school halls” suggests', ['an awkward, embarrassed hush that everyone recognises.', 'that school halls are usually silent.', 'that the audience had left.', 'that the hall had bad sound.'], 0,
          'The writer expects readers to recognise the awkward hush after something goes wrong in a school performance. That halls are usually silent is the nearest rival, but the point is that this silence is special.',
          [null, 'the point is that this silence is special', 'the audience are still there', 'sound quality is not the point']),
        Q('What does Mr Delaney’s reaction suggest?', ['He found the accident funny.', 'He was upset and perhaps swore under his breath.', 'He was helping Kit with her line.', 'He had planned the accident.'], 1,
          'He “mouthed something that was probably not in the script” — likely a word of dismay. Helping Kit with her line is the nearest rival, but Kit’s line had not yet come.',
          ['nothing suggests amusement', null, 'Kit’s line had not yet come', 'nobody had rehearsed it']),
        Q('Why is Kit’s action surprising?', ['She was not meant to be on stage at that moment.', 'She acted without planning and could not explain it afterwards.', 'She forgot her line.', 'She left the stage.'], 1,
          'She “had not planned to move” and “could not explain why she did”. Not being meant to be on stage is the nearest rival, but her cue was after the storm, so her entrance itself was not unexpected; what she did was.',
          ['her cue was after the storm, so entering was expected', null, 'she says her line and adds to it', 'she walks onto the stage']),
        Q('How does Kit change her line?', ['She forgets it and says something else.', 'She adds a joke that turns the accident into part of the play.', 'She says it to the audience instead of the captain.', 'She whispers it.'], 1,
          'She says the planned words, then adds “and so, I’m afraid, has the ocean”, making the fallen scenery part of the story. Saying it to the audience is the nearest rival, but she addresses the captain.',
          ['she says the line correctly', null, 'she addresses the captain', 'her voice carries to the back row']),
        Q('Why is Rohan’s reply notable?', ['He is not usually quick-thinking, yet he improvises well.', 'He forgets his own lines.', 'He walks off before the others.', 'He refuses to continue.'], 0,
          'He is “not known for quick thinking”, yet he answers with a fitting line. Walking off early is the nearest rival, but the whole crew walks off together.',
          [null, 'he speaks a fitting line', 'the whole crew walks off together', 'he carries on']),
        Q('What does the final paragraph suggest?', ['Kit agrees that her part was small.', 'Kit is too proud and happy to argue with her brother.', 'Kit is upset with her brother.', 'Kit did not hear her brother.'], 1,
          'She “said nothing” because she “was smiling too hard” — she does not need to argue. Agreeing that her part was small is the nearest rival, but her silence comes from happiness, not agreement.',
          ['her silence comes from happiness, not agreement', null, 'she is smiling, not upset', 'she hears him; she just does not argue']),
      ] }),

    readS2({ id: 'M04-s2', title: 'Making glass',
      text: 'Glass is made mostly from sand, yet few materials seem less like sand: one is hard, clear and smooth, the other soft, cloudy and gritty. The …(1)… happens in a furnace. When sand is heated to around 1700 degrees Celsius, it melts into a thick liquid. If it is then cooled quickly, its particles do not have time to line up in neat rows as they would in a crystal, and they are …(2)… in a jumble. The result is glass.\n\nPure sand melts at such a high temperature that glassmakers have long added other ingredients to lower it. Soda ash makes the mixture melt more easily, and lime is added to make the finished glass more …(3)…, so that it does not slowly dissolve in water.\n\nPeople have been making glass for at least four thousand years, but for most of that time it was a …(4)…. The invention of glassblowing, around two thousand years ago, made it possible to shape vessels quickly by blowing air into a blob of molten glass on the end of a tube. Even so, large flat sheets remained difficult to make. Window glass was often thick, wavy and full of bubbles.\n\nIn the 1950s a British engineer found a way to make perfectly flat glass by pouring molten glass onto a bath of molten tin, where it spreads out and …(5)… on the surface like oil on water. This “float glass” is now used for almost all the windows in the world.\n\nGlass has another useful …(6)…: it can be melted down and made again without losing quality. Yet much glass is still thrown away, because broken pieces of different colours and types must be carefully …(7)… before they can be recycled. A material that can last for thousands of years ends up, too often, in the ground after a single …(8)….',
      gaps: [
        [['transformation', 'mistake', 'collection', 'explanation'], 0, 'Sand turning into glass is a “transformation”. Explanation is the nearest rival, but what happens in a furnace is a change, not an explanation.', [null, 'nothing goes wrong', 'nothing is collected', 'a furnace makes a change, not an explanation']],
        [['frozen', 'arranged', 'melted', 'removed'], 0, 'Cooled too fast to line up, the particles are “frozen in a jumble”. Arranged is the nearest rival, but arranging suggests order, the opposite of a jumble.', [null, 'arranging suggests order', 'they are being cooled, not melted', 'nothing is removed']],
        [['durable', 'colourful', 'expensive', 'fragile'], 0, 'Lime makes glass “durable” so it does not dissolve. Fragile is the opposite of the purpose described.', [null, 'colour is not the purpose here', 'cost is not the purpose', 'lime makes it last, not break']],
        [['luxury', 'disaster', 'secret', 'nuisance'], 0, 'Until glassblowing made it easier, glass was rare and valuable: a “luxury”. Secret is the nearest rival, but the passage is about how hard it was to make, not about hiding it.', [null, 'nothing suggests disaster', 'the passage is about difficulty, not secrecy', 'it was valued, not a nuisance']],
        [['floats', 'sinks', 'boils', 'cracks'], 0, 'Glass spreads out on the tin “like oil on water”, so it “floats” — which is why it is called float glass. Sinks is the opposite.', [null, 'oil on water floats', 'boiling would ruin the glass', 'cracking would ruin it']],
        [['property', 'colour', 'history', 'danger'], 0, '“It can be melted down and made again” is a useful “property”. History is the nearest rival, but being recyclable is a characteristic, not a history.', [null, 'recyclability is not a colour', 'this is a characteristic, not its past', 'it is described as useful, not dangerous']],
        [['sorted', 'painted', 'polished', 'hidden'], 0, 'Pieces of different colours and types must be “sorted”. Polished is the nearest rival, but polishing does not separate types.', [null, 'painting would not help recycling', 'polishing does not separate types', 'hiding makes no sense']],
        [['use', 'year', 'break', 'colour'], 0, 'A material that could last thousands of years is thrown away after a single “use”. Year is the nearest rival, but the contrast is with one use, not one year.', [null, 'the contrast is with one use', '“a single break” is not natural', 'colour does not fit']],
      ] }),

    readS3({ id: 'M04-s3', headnote: 'This poem is set on a farm during a long drought.', title: 'The Dam',
      lines: [
        'We used to swim here. Now the dam’s a plate',
        'of cracked brown china, and the yabbies’ holes',
        'are empty mouths that cannot say how late',
        'the rain is, or how many weeks, or souls',
        '',
        'it would take to fill them. Dad comes down at dusk',
        'and stands where water used to reach his knees,',
        'and tells me nothing, which is how I know.',
        'The sheep have learned the shade of the three trees',
        '',
        'and do not leave it. Every afternoon',
        'the sky builds castles out along the west',
        'and lets them fall. My mother says, “It’s soon.”',
        'She’s said it every week since we had rain.',
        '',
        'Tonight I heard a sound and held my breath:',
        'a drumming on the roof — then it was gone.',
        'A possum. Only that. And yet the earth',
        'smelled, for a moment, as if it had won.',
      ],
      questions: [
        Q('In lines 1–2, the dried dam is compared to', ['a broken dinner plate.', 'a swimming pool.', 'a muddy road.', 'a cracked mirror.'], 0,
          'The dam is “a plate / of cracked brown china”. A cracked mirror is the nearest rival, but the poem names china, not glass.',
          [null, 'it used to be for swimming, but it is not compared to a pool', 'no road is mentioned', 'the poem names china, not glass']),
        Q('What does “tells me nothing, which is how I know” (line 7) suggest?', ['The father is angry with the speaker.', 'The father’s silence shows how worried he is.', 'The father does not know about the drought.', 'The speaker is not listening.'], 1,
          'His silence tells the speaker how serious things are. Being angry is the nearest rival, but nothing suggests anger at the speaker.',
          ['nothing suggests anger at the speaker', null, 'he stands in the empty dam, so he knows', 'the speaker understands him perfectly']),
        Q('What do the “castles” in lines 10–11 most likely describe?', ['Clouds that build up but bring no rain.', 'Buildings on a neighbouring farm.', 'Sandcastles the children make.', 'Smoke from a bushfire.'], 0,
          'The sky builds castles in the west “and lets them fall”: towering clouds that come to nothing. Smoke is the nearest rival, but the poem is about waiting for rain.',
          [null, 'the castles are built by the sky', 'no children are building', 'the poem is about waiting for rain']),
        Q('What is suggested by the mother saying “It’s soon” every week?', ['She knows exactly when it will rain.', 'She is trying to keep up hope, even though she has been wrong many times.', 'She wants the family to leave the farm soon.', 'She is talking about a visit from relatives.'], 1,
          'She has “said it every week” without rain coming: she is keeping hope alive. Knowing exactly when is the opposite of what the repeated wrong forecast shows.',
          ['she has been wrong every week', null, 'leaving is not mentioned', 'no visit is mentioned']),
        Q('Why does the speaker hold their breath in line 13?', ['They are frightened of the possum.', 'They hope the sound on the roof is rain.', 'They are trying to sleep.', 'They hear their father coming.'], 1,
          'The “drumming on the roof” sounds like rain, and the speaker hopes. Being frightened of the possum is the nearest rival, but the speaker only learns it is a possum afterwards.',
          ['the speaker only learns afterwards that it is a possum', null, 'holding breath is about hope, not sleep', 'the father is not mentioned here']),
        Q('What is the effect of the final two lines?', ['They show the drought has ended.', 'They show a brief moment of hope, even though it was not rain.', 'They show the possum has damaged the roof.', 'They show the speaker is angry.'], 1,
          'Even after the disappointment, the earth seems for a moment to smell as if rain had come. That the drought has ended is the nearest rival, but the sound was “Only” a possum.',
          ['it was only a possum', null, 'no damage is described', 'the mood is wistful, not angry']),
      ] }),

    readS4({ id: 'M04-s4', title: 'Why the sea has tides',
      paras: [
        'Twice a day, along most of the world’s coasts, the sea rises and falls. ...(1)... The cause lies more than 380 000 kilometres away.',
        'The Moon’s gravity pulls on the whole Earth, but it pulls hardest on the side facing the Moon and least on the side facing away. ...(2)... The water on the near side is pulled towards the Moon, while on the far side the Earth itself is pulled slightly away from the water.',
        'As the Earth spins, each place on the coast passes through both bulges every day. ...(3)... Because the Moon is also moving in its orbit, the tides arrive about fifty minutes later each day.',
        'The Sun has an effect too, though a smaller one. ...(4)... When the Sun, Moon and Earth are lined up, at new moon and full moon, the pulls combine to produce especially high and low tides, called spring tides.',
        'The shape of the coast makes an enormous difference. ...(5)... In parts of north-western Australia the difference can be more than ten metres, while in some enclosed seas it is only a few centimetres.',
        '...(6)... Fishers, sailors and coastal engineers all plan around tide tables that can be calculated years in advance.',
      ],
      sentences: [
        'For thousands of years people have wondered why.',
        'This difference stretches the oceans into two bulges, one on each side of the planet.',
        'That is why most places have two high tides and two low tides each day.',
        'It is much larger than the Moon, but so far away that its pull on the oceans is weaker.',
        'In wide bays and narrow inlets, water can pile up to remarkable heights.',
        'Tides are so regular that they can be predicted with great accuracy.',
        'The highest waves in the world are caused by storms.',
      ],
      answers: [0, 1, 2, 3, 4, 5],
      explains: [
        'The rising and falling sea is introduced, then “The cause lies …” follows, so the gap raises the question of why.',
        'The uneven pull is described, then the two sides are explained: the gap names the result, two bulges.',
        'Passing through both bulges each day explains why most places have two high and two low tides.',
        '“The Sun has an effect too, though a smaller one” is explained by its distance making its pull weaker despite its size.',
        '“The shape of the coast makes an enormous difference” leads to bays where water piles up, before the Australian example.',
        'Tide tables “calculated years in advance” follow from tides being highly predictable. The sentence about storm waves is the extra one.',
      ] }),

    readS5({ id: 'M04-s5', headnote: 'Four writers discuss clocks and time.',
      extracts: [
        { title: 'Extract A', paras: ['Before railways, every town kept its own time, set by the Sun at noon. A clock in Sydney and one in Bathurst might differ by several minutes, and nobody minded. Trains changed that. Timetables were impossible if every station had a different time, so standard time zones were introduced, and towns gave up their local noon for a shared one.'] },
        { title: 'Extract B', paras: ['My grandfather’s clock has not kept good time since 1987. It gains about four minutes a day, and he winds it back every Sunday after lunch. We have offered to buy him a new one. He says the old one tells him something more important than the time, though he has never told us what.'] },
        { title: 'Extract C', paras: ['Schools should stop ringing bells between lessons. Bells train students to stop thinking the instant they hear a signal, however interesting the discussion. Teachers are perfectly capable of watching a clock, and lessons that end naturally would teach students to manage their own time.'] },
        { title: 'Extract D', paras: ['The most accurate clocks in the world measure the vibrations of atoms. The best of them would not gain or lose a second in billions of years. Such precision is not just for scientists: the satellites that tell your phone where you are depend on clocks this accurate, because a tiny timing error becomes a large error in position.'] },
      ],
      items: [
        ['explains how a new form of transport changed the way time was kept?', 'A', 'A says railways led to standard time zones. D mentions satellites, but they did not change how time was kept.'],
        ['describes someone who prefers an inaccurate clock?', 'B', 'The grandfather keeps a clock that gains four minutes a day. D describes accurate clocks, the opposite.'],
        ['argues that a signal stops students from thinking?', 'C', 'C says bells train students to stop thinking. A mentions timetables, but not students.'],
        ['explains how accurate timekeeping affects an everyday device?', 'D', 'D says phone location depends on extremely accurate clocks. A describes railway timetables, not a device.'],
        ['mentions that people once did not mind clocks disagreeing?', 'A', 'A says clocks in different towns differed by minutes “and nobody minded”. B’s family offer a new clock, so they do mind a little.'],
        ['includes a reason that is never explained?', 'B', 'The grandfather says the clock tells him something more important, but never says what. C explains its reasons fully.'],
        ['suggests that people can manage time without being told?', 'C', 'C says lessons ending naturally would teach students to manage their own time. B describes a routine, but does not make this point.'],
        ['describes a clock that would almost never be wrong?', 'D', 'Atomic clocks would not lose a second in billions of years. A describes clocks that disagreed.'],
        ['describes a routine for correcting a clock?', 'B', 'The grandfather winds the clock back every Sunday after lunch. A describes towns changing their time once, not a routine.'],
        ['shows that a small error can grow into a large one?', 'D', 'D says a tiny timing error becomes a large error in position. B’s clock gains a little each day, but no larger error is described.'],
      ] }),
  ],

  thinking: [
    TS('strengthen', 'A swimming coach claims that his new training program has made his swimmers faster.',
      'Which one of these statements, if true, most strengthens the coach’s claim?',
      ['Swimmers who followed the program improved their times far more than swimmers of the same age and level who trained the old way.', 'The swimmers enjoyed the new program.', 'The program includes more stretching.', 'Most swimmers get faster as they grow older.'], 0,
      'A comparison with similar swimmers who kept training the old way shows the program made the difference. Most swimmers getting faster with age is the nearest rival, but it suggests another explanation, which weakens the claim.',
      [null, 'enjoyment does not show they got faster', 'this describes the program, not its effect', 'this suggests another explanation']),
    TS('weaken', 'Sam argues: “Our class should vote on the excursion, because a vote is the fairest way to decide, and the most popular choice will make the most people happy.”',
      'Which one of these statements, if true, most weakens Sam’s argument?',
      ['The most popular choice is a theme park that three students in the class cannot go to because of medical conditions.', 'Some students do not like voting.', 'The teacher usually chooses the excursion.', 'The class has 28 students.'], 0,
      'If the most popular choice would exclude some students entirely, a simple vote may not be the fairest way. The teacher usually choosing is the nearest rival, but it does not show voting is unfair.',
      [null, 'disliking voting does not weaken the argument', 'this does not show voting is unfair', 'class size is irrelevant']),
    WR('In a maths competition, each correct answer scores 4 points and each wrong answer loses 1 point. Questions left blank score 0. There are 10 questions.\nIrene: “Paul scored 20, so he must have answered at least 5 questions correctly.”\nVictor: “Paul scored 20, so he cannot have answered all 10 questions.”',
      'Irene', 'Victor', true, false,
      'Irene is right: fewer than 5 correct answers give at most 16 points. Victor is wrong: Paul could have 6 right and 4 wrong, which is 24 − 4 = 20 with all 10 answered.'),
    TS('flaw', 'Yasmin says: “I saw three people in the park wearing Swiftrunner shoes, and they were all running fast. Swiftrunner shoes must make people run faster.”',
      'Which one of the following shows the mistake Yasmin has made?',
      ['Fast runners may choose Swiftrunner shoes, rather than the shoes making them fast, and three people is far too few to tell.', 'Swiftrunner shoes might be expensive.', 'Yasmin might not like running.', 'Other brands also make running shoes.'], 0,
      'The runners may have been fast already and chosen these shoes, and three people tell us very little. Other brands making shoes is the nearest rival, but it does not describe the mistake.',
      [null, 'price is irrelevant', 'her own interest is irrelevant', 'this does not describe the mistake']),
    TS('assumption', 'The principal says: “We should start a homework club after school. Students who struggle with homework will get help from teachers there.”',
      'Which one of the following is an assumption the principal has made?',
      ['Students who struggle with homework will be able and willing to come to the club after school.', 'Homework is important.', 'Teachers like helping students.', 'The club will meet in the library.'], 0,
      'The plan helps struggling students only if they actually attend; some may have to catch a bus or care for siblings. Teachers liking to help is the nearest rival, but the principal’s plan does not depend on teachers enjoying it.',
      [null, 'the plan does not depend on this', 'the plan does not depend on teachers enjoying it', 'the location is irrelevant']),
    TS('weaken', 'A town claims: “The new skate park has reduced vandalism in the town centre, because young people now have somewhere else to go.”',
      'Which one of these statements, if true, most weakens the town’s claim?',
      ['Security cameras were installed in the town centre in the same month the skate park opened.', 'The skate park is popular on weekends.', 'Some adults also use the skate park.', 'Skate parks can be noisy.'], 0,
      'If cameras went up at the same time, they may explain the drop in vandalism. The skate park being popular on weekends is the nearest rival, but it fits the town’s explanation.',
      [null, 'this fits the town’s explanation', 'adult use is irrelevant', 'noise is irrelevant']),
    WR('All the books in the blue box are about animals. All the books about birds are in the blue box.\nAnya: “Every book about animals is in the blue box.”\nJoel: “Every book about birds is a book about animals.”',
      'Anya', 'Joel', false, true,
      'Joel is right: every bird book is in the blue box, and every book in the blue box is about animals. Anya is wrong: there could be animal books, such as books about dogs, outside the box.'),
    TS('strengthen', 'Laila argues that reading on paper helps people remember more than reading on screens.',
      'Which one of these statements, if true, most strengthens Laila’s argument?',
      ['In a study, two groups read the same text, one on paper and one on screens, and the paper group remembered more in a test.', 'Many people prefer paper books.', 'Screens can cause eye strain.', 'Paper books do not need charging.'], 0,
      'A fair comparison of the same text on paper and screen directly supports her claim. Screens causing eye strain is the nearest rival: it suggests a possible reason, but it is not evidence that memory is better on paper.',
      [null, 'preference does not show better memory', 'this is a possible reason, not evidence', 'charging is irrelevant']),
    TS('flaw', 'Toby says: “If it rains, the school cancels the cross-country. The cross-country was cancelled today, so it must have rained.”',
      'Which one of the following shows the mistake Toby has made?',
      ['The cross-country might have been cancelled for some other reason.', 'It might rain tomorrow.', 'Some students like running in the rain.', 'The cross-country might be held next week.'], 0,
      'Rain causes cancellation, but cancellation could have other causes, such as extreme heat. That it might be held next week is the nearest rival, but it does not describe the mistake.',
      [null, 'tomorrow’s weather is irrelevant', 'preferences are irrelevant', 'this does not describe the mistake']),
    TS('conclusion', 'In a group of friends, everyone who likes soccer also likes basketball. Some of the friends who like basketball do not like tennis. Ava does not like basketball.',
      'Which one of the following must be true?',
      ['Ava does not like soccer.', 'Ava likes tennis.', 'Ava does not like tennis.', 'Everyone who likes basketball likes soccer.'], 0,
      'Anyone who likes soccer likes basketball, and Ava does not like basketball, so she cannot like soccer. Her view of tennis cannot be worked out.',
      [null, 'we cannot tell about tennis', 'we cannot tell about tennis', 'the rule only works the other way']),
    WR('A train leaves Ashton at 8:00 am and arrives in Belford at 9:30 am. It does not stop anywhere in between. A second train leaves Belford at 8:30 am and arrives in Ashton at 10:00 am on the same track, which has a passing loop where trains can pass each other.\nMai: “The two trains are on the track at the same time for an hour.”\nKyle: “If both trains travel at the same steady speed, they meet halfway, at 9:00 am.”',
      'Mai', 'Kyle', true, false,
      'Mai is right: both trains are on the track between 8:30 am and 9:30 am. Kyle is wrong: at equal speeds they do meet at 9:00 am, but not halfway, because the first train has had a half-hour start and has covered two-thirds of the track by then.'),
    TS('weaken', 'A tourism group argues: “We should advertise our beaches overseas. More tourists would visit, and local businesses would earn more money.”',
      'Which one of these statements, if true, most weakens the argument?',
      ['Local hotels are already full all year and cannot take any more guests.', 'The beaches are very beautiful.', 'Advertising overseas is expensive.', 'Some tourists prefer mountains.'], 0,
      'If there is nowhere for extra tourists to stay, advertising would not bring more visitors or money. Advertising being expensive is the nearest rival: it is a cost, but it does not show the plan would fail.',
      [null, 'this supports the argument', 'a cost does not show the plan would fail', 'some preferring mountains does not weaken it much']),
    TS('assumption', 'Amira says: “I should get a part in the play, because I was the loudest speaker at the audition.”',
      'Which one of the following is an assumption Amira has made?',
      ['Being loud is what the directors are looking for when they choose actors.', 'There were many people at the audition.', 'The play has many parts.', 'Amira enjoys acting.'], 0,
      'Her reasoning only works if loudness is the quality that decides the parts. The play having many parts is the nearest rival: it would help her chances, but her reasoning depends on loudness mattering.',
      [null, 'the number of people is not part of her reasoning', 'this helps her chances but is not what her reasoning depends on', 'enjoyment is not part of her reasoning']),
    TS('strengthen', 'A dentist believes that chewing sugar-free gum after meals helps prevent tooth decay.',
      'Which one of these statements, if true, most strengthens the dentist’s belief?',
      ['Chewing gum increases the flow of saliva, which washes away food and reduces the acids that damage teeth.', 'Sugar-free gum comes in many flavours.', 'Many people chew gum.', 'Gum is cheap.'], 0,
      'Explaining how chewing reduces the acids that cause decay gives a reason to expect the gum to help. Many people chewing gum is the nearest rival, but popularity says nothing about decay.',
      [null, 'flavours are irrelevant', 'popularity says nothing about decay', 'cost is irrelevant']),
    WR('At a fete, each ride ticket costs $2, or you can buy a band for $15 that gives unlimited rides. Nobody buys both.\nPhoebe: “Tess spent $14 on rides, so she must have bought tickets, not a band.”\nDev: “Joe went on 9 rides and spent exactly $15, so he must have bought a band.”',
      'Phoebe', 'Dev', true, true,
      'Both are right. A band costs $15, so spending $14 means Tess bought 7 tickets. And 9 rides on tickets would cost $18, so Joe, who spent $15, must have bought a band.'),
    TS('flaw', 'Hugo says: “The best students in my class all have tutors. So if I get a tutor, I will become one of the best students.”',
      'Which one of the following shows the mistake Hugo has made?',
      ['Having a tutor does not guarantee becoming one of the best; many students with tutors are not the best.', 'Tutors cost money.', 'Hugo might choose the wrong subject.', 'Some of the best students might not need tutors.'], 0,
      'All the best students having tutors does not mean everyone with a tutor becomes one of the best. Some best students not needing tutors is the nearest rival, but it contradicts the facts given rather than identifying the reasoning error.',
      [null, 'cost is not the mistake', 'this does not describe the reasoning error', 'this contradicts the facts given']),
  ],

  writing: {
    title: 'A diary entry', genre: 'recount',
    stimulus: ['Imagine you have spent a day somewhere you have never been before: a farm, a hospital, a newsroom, a ship, a museum after closing time, or somewhere of your own choosing.'],
    prompt: 'Write a diary entry recounting the day, so that a reader can follow what happened and understand how you felt about it.',
    guidance: ['Use the conventions of a diary: a date, a personal voice, events in order.', 'Choose a few moments to describe in detail rather than listing everything.', 'Show how your feelings changed over the day.'],
    rubricNotes: 'A strong response keeps a clear time order, selects the most telling moments, uses a personal but controlled voice, and shows a change in the writer’s feelings across the day.',
  },
});
