/* Medium Exam 5 — original content written for this site. */
'use strict';
defExam('M05', {
  reading: [
    readS1({ id: 'M05-s1', headnote: 'In this extract from a story, a piano tuner visits an elderly woman.',
      extracts: [{ paras: [
        'The piano had not been played in eleven years, Mrs Kovac told him at the door, as if confessing to something. It stood in the front room under a lace cloth and three framed photographs, and when Daniel lifted the lid, a smell of dust and old felt rose to meet him like a held breath let out.',
        'He played a chord. It was not a chord so much as an argument. Mrs Kovac winced and then, he noticed, smiled at herself for wincing.',
        '“My husband played,” she said. “Every evening, the same three pieces, very badly. I used to tell him to stop.” She moved one of the photographs a centimetre to the left and then back again. “After he died, I couldn’t stand the silence, and I couldn’t stand the piano either. So I covered it up.”',
        'Daniel said nothing. In his experience, people did not hire a piano tuner for a piano they never meant to play; they hired one when they had decided something and did not yet want to say it out loud. He took out his tools and began.',
        'It took three hours. String by string, the instrument came back from wherever it had been. Mrs Kovac brought tea he did not ask for and stayed in the doorway, pretending to be on her way somewhere else.',
        'When he had finished, he stood up and held out the piano stool. She looked at it for a long time. Then she sat, put her hands on the keys with great care, as though they might be hot, and played — very badly — the first few bars of something Daniel did not recognise. She stopped, laughed, and wiped her eyes with the back of her wrist.',
        '“That was his,” she said. “I never told him I knew it.”',
      ] }],
      questions: [
        Q('Why does Mrs Kovac tell Daniel about the eleven years “as if confessing to something”?', ['She feels faintly guilty or embarrassed about having neglected the piano.', 'She broke the piano.', 'She is not allowed to own a piano.', 'She wants a discount.'], 0,
          '“Confessing” suggests she feels she has done something wrong by leaving it unplayed. Breaking it is the nearest rival, but it only needs tuning.',
          [null, 'it only needs tuning', 'nothing suggests this', 'money is never mentioned']),
        Q('What is suggested by the chord being “not a chord so much as an argument”?', ['The out-of-tune notes clash harshly with each other.', 'Daniel and Mrs Kovac begin to argue.', 'Daniel plays the piano badly.', 'The piano is too loud.'], 0,
          'The notes fight rather than blend, because the piano is badly out of tune. Daniel and Mrs Kovac arguing is the nearest rival, but the “argument” is a metaphor for the sound.',
          [null, 'the “argument” is a metaphor for the sound', 'the problem is the tuning, not Daniel', 'the issue is harshness, not volume']),
        Q('Why does Mrs Kovac move the photograph a centimetre and then back again?', ['It shows she is nervous and emotional while talking about her husband.', 'She wants it to be straight.', 'She is dusting it.', 'She wants Daniel to look at it.'], 0,
          'The small, pointless movement while speaking about her husband reveals her unease. Wanting it straight is the nearest rival, but she puts it straight back where it was.',
          [null, 'she puts it straight back', 'she does not dust', 'she does not draw attention to it']),
        Q('Why did Mrs Kovac cover the piano?', ['It reminded her painfully of her husband, yet the silence without his playing was also hard to bear.', 'She wanted to protect it from dust.', 'She did not like music.', 'She planned to sell it.'], 0,
          'She “couldn’t stand the silence, and … couldn’t stand the piano either”, so she hid it. Protecting it from dust is the nearest rival, but her reason is emotional.',
          [null, 'her reason is emotional', 'she clearly cares about the music', 'she has just paid to tune it']),
        Q('What does Daniel believe about why people hire a piano tuner for an unused piano?', ['They have privately decided to start playing again but are not ready to admit it.', 'They want to sell it.', 'They are lonely and want company.', 'They want to know what it is worth.'], 0,
          'People hire a tuner “when they had decided something and did not yet want to say it out loud”. Being lonely is the nearest rival, but Daniel’s idea concerns a decision, not company.',
          [null, 'he says the opposite: they mean to play', 'his idea concerns a decision, not company', 'value is not mentioned']),
        Q('What does Mrs Kovac staying “in the doorway, pretending to be on her way somewhere else” reveal?', ['She wants to watch the piano being restored but does not want to seem too eager.', 'She does not trust Daniel.', 'She is about to go out.', 'She is bored.'], 0,
          'She lingers but disguises her interest. Not trusting Daniel is the nearest rival, but her “pretending” suggests hidden interest, not suspicion.',
          [null, 'her pretending hides interest, not suspicion', 'she is only pretending', 'she stays for three hours']),
        Q('Why does she touch the keys “as though they might be hot”?', ['She is cautious and emotional about playing again after so long.', 'The piano has been in the sun.', 'Daniel has warned her.', 'She has burnt her hands.'], 0,
          'The simile shows her hesitation about returning to something painful. The piano being in the sun is the nearest rival, but “as though” makes it a comparison.',
          [null, '“as though” makes it a comparison', 'Daniel says nothing', 'nothing suggests an injury']),
        Q('What is the significance of her final words, “I never told him I knew it”?', ['She secretly loved and learnt her husband’s music, though she told him to stop playing.', 'She had never heard the piece before.', 'Her husband wrote the music for her.', 'She is lying to Daniel.'], 0,
          'She complained about his playing but had learnt his piece, revealing hidden affection. The husband writing it for her is the nearest rival, but “That was his” only means it was the piece he played.',
          [null, 'she knew it well enough to play it', '“That was his” only means it was the piece he played', 'nothing suggests she is lying']),
      ] }),

    readS2({ id: 'M05-s2', title: 'The saltwater crocodile',
      text: 'The saltwater crocodile is the largest living reptile. Males can grow to more than six metres long and weigh over a tonne, and the species is found across northern Australia, South-East Asia and parts of India. Despite its name, it is equally at home in rivers, swamps and estuaries, and it can even …(1)… long distances out at sea, riding ocean currents from one coastline to another.\n\nCrocodiles are ambush hunters. A crocodile may lie almost completely …(2)… for hours, with only its eyes and nostrils above the water, before launching itself at prey with astonishing speed. Its bite is among the most powerful ever measured in any animal.\n\nIn the 1940s to 1960s, hunting for crocodile skins reduced their numbers so …(3)… that they were feared to be heading for extinction in Australia. Protection laws introduced in the early 1970s allowed the population to …(4)…, and today there are estimated to be well over 100 000 in the Northern Territory alone.\n\nThis success has created a new challenge. As numbers have grown, crocodiles have become more common near towns and popular swimming spots, increasing the …(5)… of dangerous encounters. Rangers now remove crocodiles from some areas and run campaigns to make people more …(6)… — the message is that any body of water in the north may contain a crocodile, whether or not one has been seen.\n\nScientists argue that living alongside these animals is possible, but only if people respect them. A crocodile is not …(7)…; it is simply doing what crocodiles have done for millions of years. The …(8)… lies with people to stay out of its way.',
      gaps: [
        [['travel', 'hide', 'hunt', 'breathe'], 0, 'Riding currents from coast to coast means they “travel long distances”. Hunt is the nearest rival, but the sentence is about moving between coastlines.', [null, 'riding currents is not hiding', 'the sentence is about moving between coastlines', '“breathe long distances” makes no sense']],
        [['still', 'awake', 'dry', 'visible'], 0, 'An ambush hunter lies “almost completely still” before striking. Visible is the opposite: only its eyes and nostrils show.', [null, '“almost completely awake” is not the point', 'it is in the water', 'only its eyes and nostrils show']],
        [['sharply', 'slightly', 'happily', 'slowly'], 0, 'Numbers fell so “sharply” that extinction was feared. Slightly is the opposite.', [null, 'a slight fall would not threaten extinction', '“happily” makes no sense', 'the point is the size of the fall']],
        [['recover', 'disappear', 'move', 'shrink'], 0, 'Protection allowed the population to “recover”, now over 100 000. Shrink is the opposite.', [null, 'the population grew', '“move” does not fit the growth', 'the population grew']],
        [['risk', 'fun', 'cost', 'size'], 0, 'More crocodiles near people increases the “risk” of dangerous encounters. Cost is the nearest rival, but the danger is to people’s safety.', [null, 'dangerous encounters are not fun', 'the danger is to safety, not money', '“size of encounters” makes no sense']],
        [['careful', 'curious', 'relaxed', 'brave'], 0, 'Campaigns aim to make people more “careful”. Brave is the nearest rival, but the message is about caution.', [null, 'curiosity could increase the danger', 'the message is the opposite of relaxing', 'the message is about caution']],
        [['wicked', 'ancient', 'hungry', 'dangerous'], 0, 'The crocodile is not “wicked”; it is simply behaving naturally. Dangerous is the nearest rival, but the passage accepts crocodiles are dangerous — it denies only that they are to blame.', [null, 'the passage says they are ancient', 'the point is about blame, not hunger', 'the passage accepts crocodiles are dangerous']],
        [['responsibility', 'danger', 'blame', 'water'], 0, 'The “responsibility” lies with people to stay away. Blame is the nearest rival, but the sentence is about a duty for the future.', [null, '“the danger lies with people” reverses the idea', 'the sentence is about a duty, not blame', '“the water lies with people” makes no sense']],
      ] }),

    readS3({ id: 'M05-s3', headnote: 'In this poem the speaker describes something passed down in the family.', title: 'Inheritance',
      lines: [
        'From my grandmother: a teapot with a chipped spout',
        'that pours a little sideways, so you have to know it,',
        'and a way of saying “Well!” that means',
        'six different things, depending.',
        '',
        'From my grandfather: nothing you can hold.',
        'A habit of whistling when the news is bad.',
        'The certainty that any broken thing',
        'deserves at least one try with glue.',
        '',
        'From my mother: her hands. I see them',
        'when I reach for a jar, when I fold a letter;',
        'they are older than me and they know things',
        'I haven’t learnt yet.',
        '',
        'What will I leave? I have been thinking.',
        'Not money. Not the house. Something smaller,',
        'like a sideways teapot — something you’d have',
        'to learn, and keep, and pour with care.',
      ],
      questions: [
        Q('What does “so you have to know it” (line 2) suggest about the teapot?', ['Using it properly takes experience and familiarity.', 'It is very valuable.', 'It must be kept secret.', 'It no longer works.'], 0,
          'Because it pours sideways, you must learn its habits. Being valuable is the nearest rival, but the line is about how to use it.',
          [null, 'the line is about how to use it', 'nothing is secret', 'it still pours']),
        Q('What does the speaker suggest about the grandmother’s “Well!”?', ['Its meaning changed with the situation and her tone.', 'She said it rarely.', 'It was always angry.', 'Nobody understood it.'], 0,
          'It “means six different things, depending” — on context and tone. Nobody understanding it is the nearest rival, but the speaker clearly does.',
          [null, 'nothing suggests it was rare', 'it had six meanings, not one', 'the speaker clearly understands it']),
        Q('The grandfather’s inheritance is best described as', ['attitudes and habits rather than objects.', 'a set of tools.', 'money.', 'a broken object.'], 0,
          '“Nothing you can hold” — he left whistling and a belief in mending things. A broken object is the nearest rival, but he left the belief, not the object.',
          [null, 'glue is part of an attitude, not a gift', 'money is never mentioned', 'he left a belief, not an object']),
        Q('What does the speaker mean by saying the mother’s hands “are older than me”?', ['The speaker’s own hands have inherited her mother’s look and skills.', 'The speaker’s hands are wrinkled.', 'The mother has died.', 'The speaker wears her mother’s gloves.'], 0,
          'The speaker sees her mother’s hands in her own, carrying knowledge passed down. The mother having died is the nearest rival, but the poem does not say so.',
          [null, 'the claim is about inheritance, not appearance', 'the poem does not say so', 'gloves are not mentioned']),
        Q('What is the main idea of the final stanza?', ['The speaker wants to pass on something small but meaningful that must be learnt and cherished.', 'The speaker wants to give away the teapot.', 'The speaker is worried about money.', 'The speaker wants to sell the house.'], 0,
          'Not money or the house, but something like the teapot that must be learnt and kept with care. Giving away the teapot is the nearest rival, but the teapot is a comparison: “like a sideways teapot”.',
          [null, 'the teapot is a comparison', '“Not money”', '“Not the house”']),
        Q('How is the poem organised?', ['It lists what each relative left, then turns to what the speaker will leave.', 'It tells a story in order of time.', 'It argues against keeping old things.', 'It describes a single day.'], 0,
          'Three stanzas cover grandmother, grandfather and mother; the fourth looks ahead to the speaker. A story in time order is the nearest rival, but the stanzas are organised by person.',
          [null, 'the stanzas are organised by person', 'it values old things', 'there is no single day']),
      ] }),

    readS4({ id: 'M05-s4', title: 'The stone that spoke three languages',
      paras: [
        'In 1799, soldiers rebuilding a fort near the Egyptian town of Rashid, which Europeans called Rosetta, found a broken slab of dark stone covered in writing. ...(1)...',
        'The stone carried the same official announcement written three times: in Egyptian hieroglyphs, in a later Egyptian script called demotic, and in ancient Greek. ...(2)... If the three texts said the same thing, the Greek could act as a key to the other two.',
        'It was not that simple. ...(3)... Many scholars believed they were a kind of picture-writing, where each sign stood for a whole idea.',
        'The breakthrough came from the French scholar Jean-François Champollion. ...(4)... He realised that hieroglyphs were a mixture: some signs stood for sounds, while others stood for whole words or ideas.',
        '...(5)... These ovals, now called cartouches, contained royal names such as Ptolemy and Cleopatra, which could be matched to the Greek text letter by letter.',
        'Champollion announced his discovery in 1822. ...(6)... Today the Rosetta Stone is one of the most visited objects in the British Museum.',
      ],
      sentences: [
        'They had no idea that it would unlock a language no one had been able to read for over a thousand years.',
        'Ancient Greek, unlike hieroglyphs, was still well understood by scholars.',
        'Hieroglyphs had been misunderstood for centuries.',
        'He had studied many languages, including Coptic, the descendant of ancient Egyptian.',
        'Important clues came from names enclosed in oval rings.',
        'For the first time in many centuries, the writing on temple walls and tombs could be read again.',
        'The stone weighs more than 750 kilograms.',
      ],
      answers: [0, 1, 2, 3, 4, 5],
      explains: [
        'The finders could not know how important the stone would be; this sets up the rest of the story.',
        'Greek being understood explains why it could “act as a key”.',
        '“It was not that simple” is explained by centuries of misunderstanding, then the belief that hieroglyphs were picture-writing.',
        'Champollion is introduced, then his knowledge of Coptic, then his realisation about sounds.',
        '“These ovals” needs the sentence that first mentions names in oval rings.',
        'After the announcement, the gap gives its result: writing on temples could be read again. The weight of the stone is the extra sentence.',
      ] }),

    readS5({ id: 'M05-s5', headnote: 'Four writers discuss handwriting.',
      extracts: [
        { title: 'Extract A', paras: ['Research suggests that students who take notes by hand often remember the material better than those who type. Because writing is slower, they cannot copy every word and must decide what matters, which forces them to think about the ideas as they go.'] },
        { title: 'Extract B', paras: ['I keep every letter my grandmother wrote me. Her capital G looked like a swan, and when she was cross the letters leant forward as if hurrying to make their point. A typed message could never tell me so much about the person who sent it.'] },
        { title: 'Extract C', paras: ['Insisting that children spend hours on neat joined writing is a waste of time. Adults now type far more than they write. The hours would be better spent teaching keyboard skills — or, better still, teaching children to write clearly, in any form, about things that interest them.'] },
        { title: 'Extract D', paras: ['For years my messy writing cost me marks, as teachers could not read my answers. Then a teacher suggested I slow down and print instead of joining. My marks improved immediately — not because I knew any more, but because people could finally see what I knew.'] },
      ],
      items: [
        ['claims that handwriting can help memory?', 'A', 'Students who take notes by hand “remember the material better”. D says marks improved, but because answers became readable.'],
        ['suggests handwriting reveals a person’s mood?', 'B', 'When cross, the grandmother’s letters “leant forward”. D describes messy writing, not mood.'],
        ['argues against a common school practice?', 'C', 'C says hours of joined writing are “a waste of time”. D describes a teacher’s advice, not an argument against a practice.'],
        ['describes a simple change that solved a problem?', 'D', 'Printing instead of joining improved the writer’s marks. A describes a study, not a personal change.'],
        ['explains why slowness can be an advantage?', 'A', 'Writing is slower, so note-takers must decide what matters. D slowed down, but the benefit was readability, not thinking.'],
        ['uses comparisons to describe the shapes of letters?', 'B', 'A capital G “looked like a swan”. C discusses handwriting but describes no letters.'],
        ['points out that adults now rarely need to write by hand?', 'C', 'Adults “type far more than they write”. A compares handwriting and typing, but for students’ notes.'],
        ['suggests that a mark should reflect knowledge rather than neatness?', 'D', 'The writer’s marks improved because people “could finally see what I knew”. C criticises neatness, but not marking.'],
        ['values handwriting for personal rather than practical reasons?', 'B', 'The letters reveal the grandmother herself. A values handwriting for a practical reason: memory.'],
        ['proposes a different use for class time?', 'C', 'C suggests teaching keyboard skills or clear writing instead. D describes advice given to one student, not a use of class time.'],
      ] }),
  ],

  thinking: [
    TS('strengthen', 'Councillor Park says: “Building a skate park will reduce the number of young people skateboarding in the shopping centre car park, where they risk being hit by cars.”',
      'Which one of these statements, if true, most strengthens the councillor’s argument?',
      ['In two nearby suburbs, skateboarding in car parks fell sharply within months of a skate park opening.', 'Skateboarding is becoming more popular.', 'The skate park would cost $400 000.', 'Some shop owners complain about noise from skateboarders.'], 0,
      'Evidence from similar suburbs shows skate parks do draw skaters away from car parks. Skateboarding becoming more popular is the nearest rival, but it does not show the skate park would move them.',
      [null, 'this does not show the skate park would move skaters', 'cost does not support the claim', 'this is a complaint, not evidence the plan works']),
    TS('weaken', 'A toothpaste company claims: “Nine out of ten dentists recommend our toothpaste.”',
      'Which one of these statements, if true, most weakens the company’s claim that most dentists prefer its toothpaste?',
      ['The dentists surveyed were allowed to choose several brands, and most of them also recommended every other major brand.', 'The toothpaste comes in two flavours.', 'Some dentists did not reply.', 'The survey was carried out last year.'], 0,
      'If dentists recommended nearly every brand, the result does not show they prefer this one. Some dentists not replying is the nearest rival, but it does not show the result is misleading in the same direct way.',
      [null, 'flavour is irrelevant', 'this is a weaker objection', 'a year-old survey can still be valid']),
    WR('At a school fete, each stall has either a blue sign or a green sign. All stalls selling food have a green sign. Every stall with a blue sign is run by parents.\nKai: “The cake stall sells food, so it is not run by parents.”\nLeah: “The book stall is run by students, so it has a green sign.”',
      'Kai', 'Leah', false, true,
      'Leah is right: every blue-sign stall is run by parents, so a stall run by students cannot have a blue sign; it must be green. Kai is wrong: the cake stall has a green sign, but nothing says green-sign stalls cannot be run by parents.'),
    TS('flaw', 'Harriet says: “Either we cancel the excursion or students will get sunburnt, so we must cancel it.”',
      'Which one of the following shows the mistake Harriet has made?',
      ['She ignores other choices, such as bringing hats and sunscreen.', 'Excursions are educational.', 'Not all students get sunburnt.', 'The weather might be cloudy.'], 0,
      'Harriet presents only two options when others exist. Cloudy weather is the nearest rival: it is a possibility, but it does not identify the false choice in her reasoning.',
      [null, 'this is a reason to go, not the flaw', 'this does not identify the false choice', 'this does not identify the false choice']),
    TS('assumption', 'Mr Ray says: “Fewer students are borrowing books this year, so they must be reading less.”',
      'Which one of the following is an assumption Mr Ray has made?',
      ['Students are not getting their reading from other places, such as e-books or home libraries.', 'Reading is important.', 'The library has fewer books.', 'Students enjoy reading.'], 0,
      'Fewer loans mean less reading only if students are not reading from other sources. The library having fewer books is the nearest rival, but it is a possible cause, not something his conclusion relies on.',
      [null, 'this is a value, not an assumption', 'this is a possible cause, not an assumption', 'enjoyment is irrelevant']),
    TS('weaken', 'Priya argues: “Our town needs a second supermarket, because the queues at the existing one are always long.”',
      'Which one of these statements, if true, most weakens Priya’s argument?',
      ['The existing supermarket only opens two of its eight checkouts, and plans to open more next month.', 'A second supermarket would create jobs.', 'Many people shop on weekends.', 'The existing supermarket sells fresh bread.'], 0,
      'If the queues are caused by too few checkouts, opening more would solve the problem without a new supermarket. Many people shopping on weekends is the nearest rival, but it explains the queues without weakening the need.',
      [null, 'this supports a second supermarket', 'this does not weaken the need', 'this is irrelevant']),
    WR('At a gym class, members must book in advance. Anyone who books a class but does not turn up three times is banned from booking for a month. Lucy has never been banned.\nMax: “Lucy has turned up to every class she has booked.”\nNell: “Lucy has never booked a class.”',
      'Max', 'Nell', false, false,
      'Neither is right. Max is wrong: Lucy could have missed one or two booked classes without being banned. Nell is wrong: never being banned does not mean she never booked; she may have booked and turned up.'),
    TS('strengthen', 'A researcher claims that playing a musical instrument improves children’s memory.',
      'Which one of these statements, if true, most strengthens the researcher’s claim?',
      ['Children randomly chosen to learn an instrument for a year improved on memory tests more than similar children randomly chosen not to.', 'Many famous scientists played instruments.', 'Children who play instruments often enjoy school.', 'Music lessons are expensive.'], 0,
      'Random selection means the two groups were alike apart from the music, so the improvement is likely caused by it. Famous scientists is the nearest rival, but it does not show cause and effect.',
      [null, 'this does not show cause and effect', 'enjoyment is not memory', 'cost is irrelevant']),
    TS('conclusion', 'All the members of the chess club are also in the maths club. Some members of the maths club are in the debating club. No member of the debating club is in the chess club.',
      'Which one of the following must be true?',
      ['Some members of the maths club are not in the chess club.', 'All maths club members are in the chess club.', 'Some chess club members are in the debating club.', 'No maths club member is in the debating club.'], 0,
      'Some maths club members are debaters, and no debater is in chess club, so those maths members are not in chess club. All maths members in chess club is the nearest rival, but it is contradicted.',
      [null, 'the debaters in maths club are not in chess club', 'no debater is in chess club', 'some maths members are debaters']),
    TS('flaw', 'Hamish says: “Most people in our street voted for the new park, so most people in the whole city must want it.”',
      'Which one of the following shows the mistake Hamish has made?',
      ['One street may not represent the views of the whole city.', 'Parks are popular.', 'Some people did not vote.', 'The park might be expensive.'], 0,
      'His street might be close to the planned park and unusually keen. Some people not voting is the nearest rival, but it is not the main mistake.',
      [null, 'this is not a flaw', 'this is not the main mistake', 'cost is irrelevant']),
    WR('In a tournament, each team plays every other team exactly once. A win gets 3 points, a draw 1 point and a loss 0. There are 4 teams.\nSam: “Each team plays 3 games.”\nTia: “A team with 7 points must have won exactly two games.”',
      'Sam', 'Tia', true, true,
      'Both are right. With 4 teams, each team plays the other 3. From 3 games, 7 points can only be made as 3 + 3 + 1, which is two wins and a draw.'),
    TS('weaken', 'Coach Ito says: “The team trains much harder than last year, so it will win more games this season.”',
      'Which one of these statements, if true, most weakens the coach’s argument?',
      ['The team has moved up to a higher division, where the opposing teams are much stronger.', 'Training sessions are longer.', 'The team has new uniforms.', 'Several players have improved their fitness.'], 0,
      'Stronger opponents could mean fewer wins despite harder training. Several players improving their fitness is the nearest rival, but it supports the coach.',
      [null, 'this supports the coach', 'uniforms are irrelevant', 'this supports the coach']),
    WR('All the students who were chosen for the state team trained at the regional camp. Not everyone at the regional camp was chosen. Ari was at the regional camp.\nBea: “Ari could have been chosen for the state team.”\nCal: “Dom did not train at the regional camp, but Dom could still have been chosen for the state team.”',
      'Bea', 'Cal', true, false,
      'Bea is right: Ari was at the camp, and the people chosen all came from the camp, so Ari could have been one of them. Cal is wrong: everyone chosen trained at the camp, so Dom, who did not, cannot have been chosen.'),
    TS('assumption', 'Ivy says: “The bakery will sell out of croissants by 9 am, because it did yesterday.”',
      'Which one of the following is an assumption Ivy has made?',
      ['The bakery will make about the same number of croissants, and demand will be similar.', 'Croissants are popular.', 'The bakery opens at 7 am.', 'Croissants are expensive.'], 0,
      'Yesterday predicts today only if the supply and demand are similar. Croissants being popular is the nearest rival, but the reasoning depends on today matching yesterday.',
      [null, 'the reasoning depends on today matching yesterday', 'opening time is not needed', 'price is irrelevant']),
    TS('strengthen', 'A school claims its new reading program improved Year 4 reading results.',
      'Which one of these statements, if true, most strengthens the school’s claim?',
      ['Year 4 results rose sharply this year, while results at similar schools without the program stayed the same.', 'The program uses colourful books.', 'Teachers like the program.', 'The program was expensive.'], 0,
      'Comparing with similar schools rules out the possibility that all results rose for another reason. Teachers liking the program is the nearest rival, but liking is not evidence.',
      [null, 'colour is not evidence', 'liking is not evidence', 'cost is irrelevant']),
    TS('flaw', 'Lena says: “Our team lost both games when Jo was away. So Jo is our most important player.”',
      'Which one of the following shows the mistake Lena has made?',
      ['Two games are too few to judge, and the losses may have had other causes, such as strong opponents.', 'Jo might be sick.', 'Teams need more than one player.', 'The team might win next week.'], 0,
      'Lena draws a big conclusion from two games and ignores other explanations. Teams needing more than one player is the nearest rival, but it does not identify her error.',
      [null, 'this is irrelevant', 'this does not identify her error', 'this is irrelevant']),
  ],

  writing: {
    title: 'School uniforms', genre: 'persuasive',
    stimulus: ['“School uniforms should be optional.”'],
    prompt: 'Write a persuasive piece for your school newsletter arguing for or against this statement.',
    guidance: ['State your position clearly in the opening.', 'Support it with two or three strong reasons and specific examples.', 'Answer at least one argument the other side would make.', 'End with a conclusion that leaves a strong impression.'],
    rubricNotes: 'A strong response takes a clear position, supports it with well-developed reasons, anticipates and answers the other side, and uses persuasive language with control.',
  },
});
