/* Medium Exam 6 — original content written for this site. */
'use strict';
defExam('M06', {
  reading: [
    readS1({ id: 'M06-s1', headnote: 'Read the two extracts, in which young people face a test, and answer the questions.',
      extracts: [
        { label: 'Extract A', title: 'The audition', paras: [
          'The rehearsal room was very bright and very empty, apart from three people behind a table and a single chair in the middle of the floor. Marcus had practised this moment so many times in his bedroom that the real thing felt like a poor copy of it.',
          'He sat, settled the cello between his knees and looked at his music. The notes, which he knew as well as his own name, looked suddenly like a language he had studied once and mostly forgotten.',
          'He began. The first phrase was thin and careful, the sound of someone walking across ice. Then, somewhere in the fourth bar, he stopped thinking about the three people at the table and started thinking about the music instead, and the sound opened out and filled the room, and for two minutes he was not auditioning at all; he was just playing.',
          'When he finished, the woman in the middle wrote something down. “Thank you,” she said, which could have meant anything.',
        ] },
        { label: 'Extract B', title: 'The final word', paras: [
          'There were two of us left on the stage: me and a boy from St Anne’s who had spelt “onomatopoeia” as if it were his own surname. The hall had gone so quiet I could hear the clock.',
          '“Your word,” said the pronouncer, “is ‘rhythm’.”',
          'I nearly laughed. It was so short, after all those long ones. Then, of course, I panicked. Was there a second “h”? Where did the “y” go? I asked for the word in a sentence, not because I needed it, but to give my brain time to stop running in circles.',
          'R-H-Y-T-H-M. The judge nodded. The boy from St Anne’s got “parallel”, and put the double “l” in the wrong place. Afterwards he shook my hand and said, “Short words are the worst,” and I decided I liked him very much.',
        ] },
      ],
      questions: [
        Q('In Extract A, why does the real audition feel “like a poor copy” to Marcus?', ['He had imagined it so often that the real event seemed less real than his practice.', 'The room was smaller than he expected.', 'The judges were not paying attention.', 'His cello was damaged.'], 0,
          'His many rehearsals at home made the real thing feel strange and second-best. The room is the nearest rival, but nothing says it disappointed him.',
          [null, 'the room’s size is not mentioned', 'they were watching', 'nothing suggests damage']),
        Q('What does the comparison of the music to “a language he had studied once and mostly forgotten” show?', ['Nerves made familiar notes suddenly seem unfamiliar.', 'He had not learnt the piece.', 'The music was written in another language.', 'He needed glasses.'], 0,
          'He knew the notes “as well as his own name”, but nerves made them look strange. Not having learnt the piece is contradicted by the text.',
          [null, 'he knew it well', 'it is a comparison', 'nothing suggests this']),
        Q('What changes in the fourth bar?', ['Marcus forgets the judges and becomes absorbed in the music.', 'Marcus makes a mistake.', 'The judges stop him.', 'His string breaks.'], 0,
          'He “stopped thinking about the three people at the table”, and the sound “opened out”. Making a mistake is the nearest rival, but the playing improves.',
          [null, 'the playing improves', 'he plays on for two minutes', 'nothing breaks']),
        Q('Why does the narrator say “Thank you” “could have meant anything”?', ['It gave no clue about whether he had succeeded.', 'The woman spoke unclearly.', 'The woman was angry.', 'Marcus did not hear it.'], 0,
          'A polite “Thank you” reveals nothing about the result. The woman being angry is the nearest rival, but nothing suggests anger.',
          [null, 'it was clear but uninformative', 'nothing suggests anger', 'he hears it']),
        Q('In Extract B, what does “as if it were his own surname” suggest about the boy from St Anne’s?', ['He spelt a very hard word with complete ease.', 'His name is Onomatopoeia.', 'He spelt it wrongly.', 'He was showing off.'], 0,
          'Spelling it like his own name means doing it effortlessly. Showing off is the nearest rival, but nothing suggests arrogance — he is later gracious.',
          [null, 'it is a comparison', 'he spelt it correctly', 'he is later gracious']),
        Q('Why does the narrator ask for the word in a sentence?', ['To gain time to calm down and think.', 'Because she did not know the word.', 'Because the rules required it.', 'To distract the other speller.'], 0,
          'She did it “not because I needed it, but to give my brain time”. Not knowing the word is contradicted by the text.',
          [null, 'she says she did not need it', 'it was her choice', 'nothing suggests this']),
        Q('Why does the narrator decide she “liked him very much”?', ['He was gracious in defeat and made a friendly joke.', 'He let her win.', 'He spelt her word for her.', 'He came from her school.'], 0,
          'He shook her hand and joked kindly about short words. Letting her win is the nearest rival, but he simply made a mistake.',
          [null, 'he simply made a mistake', 'nothing suggests this', 'he is from St Anne’s']),
        Q('What do both extracts show?', ['A young person overcoming nerves at an important moment.', 'A young person losing a competition.', 'A young person being unfairly judged.', 'A young person refusing to take part.'], 0,
          'Marcus loses himself in the music and the narrator calms herself before spelling. Losing a competition is the nearest rival, but the speller wins and Marcus’s result is unknown.',
          [null, 'the speller wins and Marcus’s result is unknown', 'nothing is unfair', 'both take part']),
      ] }),

    readS2({ id: 'M06-s2', title: 'The Murray',
      text: 'The Murray River runs about 2500 kilometres from the Australian Alps to the sea in South Australia, making it the longest river in Australia. For tens of thousands of years it has been central to the lives of many Aboriginal nations, who fished its waters, …(1)… its seasonal floods and built canoes from the bark of the red gums along its banks.\n\nIn the nineteenth century, paddle-steamers turned the river into a …(2)…, carrying wool, wheat and passengers between inland towns and the coast. The trade was …(3)… for several decades, until railways offered a faster and more reliable route and the steamers gradually disappeared.\n\nToday the river faces different pressures. A large share of its water is taken for farming, and in times of drought the flow can drop so low that the river mouth has needed to be kept open by dredging. Weirs and dams have also changed the natural …(4)… of flooding that many plants and animals depend on. River red gums, for example, need regular floods to …(5)….\n\nGovernments in several states share responsibility for the river, which has made decisions about water use difficult. Every drop taken for one purpose is a drop that cannot be used for another, and farmers, towns and the environment all have a …(6)… claim.\n\nRecent plans have tried to return more water to the river during critical times. Supporters say this is …(7)… to keep the river system alive; critics argue that it has hurt farming communities. The debate is likely to …(8)… for many years to come.',
      gaps: [
        [['relied on', 'prevented', 'ignored', 'caused'], 0, 'The nations fished, built canoes and “relied on” the seasonal floods. Prevented is the nearest rival, but the floods were a resource.', [null, 'the floods were a resource', 'they were central to life', 'people do not cause floods']],
        [['highway', 'barrier', 'mystery', 'border'], 0, 'Carrying goods and passengers made the river a “highway”. Border is the nearest rival, but the river carried goods along it.', [null, 'it connected, not blocked', 'it was well known', 'the sentence is about transport along it']],
        [['busy', 'banned', 'secret', 'useless'], 0, 'The trade was “busy” for decades before railways replaced it. Useless is the opposite.', [null, 'nothing was banned', 'nothing secret', 'it was valuable for decades']],
        [['pattern', 'colour', 'speed', 'cost'], 0, 'Dams changed the natural “pattern” of flooding. Speed is the nearest rival, but the point is the timing and regularity of floods.', [null, 'flooding has no colour', 'the point is timing and regularity', 'cost is irrelevant']],
        [['survive', 'disappear', 'grow taller than', 'escape'], 0, 'Red gums need floods to “survive”. Grow taller than is the nearest rival, but it leaves the sentence unfinished.', [null, 'floods help them, not harm them', 'the sentence would be unfinished', 'trees cannot escape']],
        [['reasonable', 'secret', 'small', 'foolish'], 0, 'Farmers, towns and the environment all have a “reasonable” claim, which makes decisions hard. Small is the nearest rival, but it does not explain the difficulty.', [null, 'the claims are public', 'small claims would not make it difficult', 'the passage treats all claims fairly']],
        [['essential', 'harmful', 'pointless', 'illegal'], 0, 'Supporters say it is “essential” to keep the river alive. Harmful is the critics’ view, not the supporters’.', [null, 'this is the critics’ view', 'supporters think it matters', 'nothing illegal is mentioned']],
        [['continue', 'end', 'begin', 'disappear'], 0, 'The debate is likely to “continue for many years”. Begin is the nearest rival, but the debate has already started.', [null, '“end for many years” makes no sense', 'it has already begun', 'the passage suggests it will go on']],
      ] }),

    readS3({ id: 'M06-s3', headnote: 'In this poem the speaker describes a journey on a city ferry.', title: 'Ferry',
      lines: [
        'The ferry shoulders out into the harbour',
        'like a big friendly dog off its leash,',
        'and the city lets go of us, wharf by wharf.',
        '',
        'Up on deck the wind is a rumour of the sea,',
        'tugging at scarves, rearranging hair,',
        'reading the newspaper over a man’s shoulder.',
        '',
        'Tourists photograph the bridge. Commuters',
        'have seen it a thousand times and look',
        'at their phones, or at nothing, or at the water',
        '',
        'which is busy with light, cutting it up',
        'into coins and spilling them. For twenty minutes',
        'no one can reach us. We are between things.',
        '',
        'Then the wharf comes up to meet us, ropes are thrown,',
        'and the gangway clangs, and we hurry off',
        'as if we had never been anywhere at all.',
      ],
      questions: [
        Q('What does the comparison of the ferry to “a big friendly dog off its leash” suggest?', ['The ferry moves out eagerly and with a sense of freedom.', 'The ferry is dangerous.', 'The ferry is very small.', 'The ferry is slow and tired.'], 0,
          'A dog off its leash is energetic and free; “friendly” removes any threat. Dangerous is the nearest rival, but “friendly” rules it out.',
          [null, '“friendly” rules it out', '“big” says the opposite', 'an unleashed dog is lively']),
        Q('How does the wind “read the newspaper over a man’s shoulder”?', ['It flutters the pages, as if curious.', 'It tears the paper away.', 'The man reads aloud.', 'The wind is very quiet.'], 0,
          'Personification: the wind lifts and turns the pages as though nosily reading them. Tearing the paper away is the nearest rival, but the image is gentle.',
          [null, 'the image is gentle', 'the man does not read aloud', 'the image is about movement, not sound']),
        Q('What contrast is drawn in lines 8–10?', ['Tourists are excited by the view, while commuters are used to it.', 'Tourists are bored and commuters excited.', 'Everyone is taking photographs.', 'Nobody can see the bridge.'], 0,
          'Tourists photograph the bridge; commuters “have seen it a thousand times”. The second option reverses the contrast.',
          [null, 'this reverses the contrast', 'commuters look at phones', 'tourists photograph it']),
        Q('What does the image of light cut “into coins” (lines 12–13) suggest?', ['The water is sparkling with many small bright reflections.', 'People are throwing money into the water.', 'The ferry ticket is expensive.', 'The water is dark and still.'], 0,
          'Light broken by moving water looks like scattered gold coins. Throwing money is the nearest rival, but it is a metaphor.',
          [null, 'it is a metaphor', 'cost is not mentioned', 'the water is “busy with light”']),
        Q('What does “We are between things” (line 15) mean?', ['The trip is a short pause, free from the demands of normal life.', 'The ferry is stuck.', 'The passengers are lost.', 'The ferry is between two other boats.'], 0,
          '“No one can reach us” — the trip is a gap between one part of life and the next. The ferry being stuck is the nearest rival, but it keeps moving.',
          [null, 'the ferry keeps moving', 'they know where they are going', 'the line is about time and freedom, not position']),
        Q('What is suggested by the final line?', ['The calm of the trip is quickly lost as people rush back into ordinary life.', 'The ferry sank.', 'The passengers enjoyed nothing.', 'The trip was very long.'], 0,
          'Hurrying off “as if we had never been anywhere” shows the moment vanishing. Enjoying nothing is the nearest rival, but the poem shows the trip as precious.',
          [null, 'they arrive safely', 'the trip is precious', 'it lasted twenty minutes']),
      ] }),

    readS4({ id: 'M06-s4', title: 'From bean to bar',
      paras: [
        'Chocolate begins as the seeds of the cacao tree, which grows only in hot, wet regions close to the equator. ...(1)... Each pod contains between twenty and fifty beans surrounded by a sweet white pulp.',
        'After harvesting, the beans are piled up and covered, often with banana leaves, and left to ferment for about a week. ...(2)... Without this stage, the finished chocolate would taste flat and bitter.',
        'The beans are then dried in the sun. ...(3)... Once dry, they are packed into sacks and shipped to factories around the world.',
        'At the factory, the beans are roasted, which deepens their flavour, and their shells are removed. ...(4)... This is ground into a thick paste called cocoa liquor, even though it contains no alcohol.',
        '...(5)... Sugar, extra cocoa butter and, for milk chocolate, milk powder are mixed in, and the mixture is stirred and heated for hours to make it smooth.',
        'Finally, the chocolate is carefully heated and cooled in a process called tempering. ...(6)...',
      ],
      sentences: [
        'The beans grow inside large pods that sprout straight from the trunk and branches.',
        'During this time the pulp breaks down and chemical changes begin to develop the flavour of chocolate.',
        'Farmers turn them regularly so that they dry evenly and do not go mouldy.',
        'What remains are small pieces called nibs.',
        'Next, the cocoa liquor is turned into chocolate.',
        'This gives the finished bar its glossy shine and its satisfying snap.',
        'Some people are allergic to chocolate.',
      ],
      answers: [0, 1, 2, 3, 4, 5],
      explains: [
        'After the tree is introduced, the gap describes the pods, before “Each pod contains…”.',
        '“Left to ferment for about a week” is followed by what happens during fermentation, then why it matters.',
        'Drying in the sun is followed by turning the beans, then shipping once dry.',
        'With shells removed, “What remains” is the nibs, and “This is ground” refers back to them.',
        'The paragraph about adding sugar and milk needs an opening that moves from cocoa liquor to chocolate.',
        'Tempering is named, then its result is given. The sentence about allergies is the extra one.',
      ] }),

    readS5({ id: 'M06-s5', headnote: 'Four writers reflect on courage.',
      extracts: [
        { title: 'Extract A', paras: ['People think courage is the absence of fear. It is not. My father was a firefighter for thirty years, and he told me he was afraid every single time the alarm went. Courage, he said, is what you do while you are frightened.'] },
        { title: 'Extract B', paras: ['The bravest thing I have ever done was to say “I don’t understand” in front of my whole class. Everyone else seemed to understand. Afterwards, three people came up and thanked me, because they had not understood either.'] },
        { title: 'Extract C', paras: ['We praise physical bravery — the rescuer, the soldier, the climber — far more than moral courage, which is often quieter and costs more. It can take more courage to admit you were wrong, or to stand by a friend everyone else has turned against, than to leap from a height.'] },
        { title: 'Extract D', paras: ['Not all risks are brave. Jumping off a high rock into water you cannot see is not courage; it is foolishness with an audience. Real courage involves weighing up the danger and deciding that something matters enough to face it.'] },
      ],
      items: [
        ['argues that fear and courage can exist together?', 'A', '“Courage … is what you do while you are frightened.” D discusses risk, but not being afraid.'],
        ['describes an act of courage that helped others unexpectedly?', 'B', 'Three classmates thanked the writer for asking. A describes a firefighter, but no unexpected effect.'],
        ['claims that one kind of courage receives too little praise?', 'C', 'Moral courage is praised far less than physical bravery. D says some risks are foolish, but not that courage is underpraised.'],
        ['distinguishes courage from recklessness?', 'D', 'Jumping into unseen water is “foolishness with an audience”. C compares two kinds of courage, not courage and recklessness.'],
        ['draws on the experience of a family member?', 'A', 'The writer’s father was a firefighter. B describes the writer’s own experience.'],
        ['describes a small, everyday act of bravery?', 'B', 'Admitting confusion in class. C mentions quiet courage but gives only general examples.'],
        ['suggests that some kinds of courage are more costly than others?', 'C', 'Moral courage “costs more”. D says real courage weighs danger, but not that some kinds cost more.'],
        ['suggests that courage requires careful judgement?', 'D', 'Real courage involves “weighing up the danger”. A says courage is acting while afraid, not judging.'],
        ['corrects a common belief about courage?', 'A', '“People think courage is the absence of fear. It is not.” C says something is underpraised, but does not correct a belief about what courage is.'],
        ['mentions standing up for someone else?', 'C', 'Standing by a friend everyone has turned against. B helped others, but by asking a question, not by defending someone.'],
      ] }),
  ],

  thinking: [
    TS('strengthen', 'Tara argues that the school canteen should sell fruit cups because students would buy them if they were available.',
      'Which one of these statements, if true, most strengthens Tara’s argument?',
      ['When fruit cups were sold for a trial week, they sold out every day.', 'Fruit is healthy.', 'The canteen sells pies.', 'Some students bring fruit from home.'], 0,
      'Selling out in a trial is direct evidence that students would buy them. Fruit being healthy is the nearest rival, but it does not show students would buy them.',
      [null, 'this does not show students would buy them', 'this is irrelevant', 'this suggests less demand']),
    TS('weaken', 'Zane says: “Students in Ms Hill’s class got the best marks in the school test, so Ms Hill is the best teacher in the school.”',
      'Which one of these statements, if true, most weakens Zane’s argument?',
      ['Ms Hill’s class is the school’s top-ability class, which already had the best marks before she taught them.', 'Ms Hill has taught for ten years.', 'The test was in maths.', 'Ms Hill’s students like her.'], 0,
      'If her students were already the strongest, their marks do not show her teaching is best. Her students liking her is the nearest rival, but it does not weaken the reasoning.',
      [null, 'experience does not weaken the reasoning', 'the subject is irrelevant', 'this does not weaken the reasoning']),
    WR('On a farm, every animal is fed in the morning or in the evening, but not both. All the goats are fed in the morning. The farmer feeds the pigs at the same time as the goats.\nEli: “The pigs are not fed in the evening.”\nFay: “Any animal fed in the evening is not a goat.”',
      'Eli', 'Fay', true, true,
      'Both are right. The pigs are fed with the goats in the morning, so not in the evening. Goats are only fed in the morning, so an animal fed in the evening cannot be a goat.'),
    TS('flaw', 'Gemma says: “Nobody has ever proved that ghosts don’t exist, so they must exist.”',
      'Which one of the following shows the mistake Gemma has made?',
      ['A lack of proof that something is false does not prove that it is true.', 'Many people believe in ghosts.', 'Ghost stories are popular.', 'Science cannot explain everything.'], 0,
      'Gemma treats the absence of disproof as proof. Science not explaining everything is the nearest rival, but it does not identify her mistake.',
      [null, 'belief is not proof', 'popularity is irrelevant', 'this does not identify the mistake']),
    TS('conclusion', 'Every student who gets above 80 in the test gets a certificate. Every student with a certificate is invited to the awards night. Rhys was not invited to the awards night.',
      'Which one of the following must be true?',
      ['Rhys did not get above 80 in the test.', 'Rhys got exactly 80.', 'Rhys did not sit the test.', 'Rhys got a certificate.'], 0,
      'Above 80 leads to a certificate, which leads to an invitation. Rhys was not invited, so he did not get above 80. Getting exactly 80 is the nearest rival, but his score could be anything up to 80.',
      [null, 'his score could be anything up to 80', 'he may have sat it', 'a certificate would have meant an invitation']),
    TS('weaken', 'A council says: “The new bike lane is not needed, because hardly anyone rides on this road.”',
      'Which one of these statements, if true, most weakens the council’s argument?',
      ['Many local people say they would cycle on this road if it felt safe, but heavy traffic stops them.', 'Bike lanes are painted green.', 'The road is two kilometres long.', 'Some cyclists ride on the footpath.'], 0,
      'Few cyclists may be a result of the danger the lane would fix. Cyclists riding on the footpath is the nearest rival: it hints at danger, but not as clearly.',
      [null, 'colour is irrelevant', 'length is irrelevant', 'this hints at danger but is weaker']),
    WR('In a class election, every student votes for exactly one of three candidates: Ana, Ben or Cleo. There are 30 students. Ana got 14 votes and Ben got 9.\nGus: “Ana got more votes than Ben and Cleo together.”\nHana: “Cleo got 7 votes.”',
      'Gus', 'Hana', false, true,
      'Hana is right: 30 − 14 − 9 = 7. Gus is wrong: Ben and Cleo together got 9 + 7 = 16, which is more than Ana’s 14.'),
    TS('assumption', 'Ruby says: “I should buy the bigger box of cereal, because it is better value.”',
      'Which one of the following is an assumption Ruby has made?',
      ['The bigger box costs less per gram than the smaller box.', 'Ruby likes cereal.', 'The bigger box fits in the cupboard.', 'The smaller box is on special.'], 0,
      '“Better value” depends on the price per gram being lower. Fitting in the cupboard is the nearest rival, but it is not about value.',
      [null, 'liking is not about value', 'this is not about value', 'this would weaken her claim']),
    TS('strengthen', 'A scientist claims that a certain beetle is helping to control weeds along a river.',
      'Which one of these statements, if true, most strengthens the scientist’s claim?',
      ['Weeds declined along stretches of the river where the beetle was released, but not along similar stretches where it was not.', 'The beetle is small and black.', 'Weeds grow quickly.', 'The beetle was brought from overseas.'], 0,
      'Comparing similar stretches with and without the beetle links the decline to the beetle. Weeds growing quickly is the nearest rival, but it does not support the claim.',
      [null, 'appearance is irrelevant', 'this does not support the claim', 'origin is irrelevant']),
    TS('flaw', 'Kurt says: “If I water the plant, it will grow. The plant grew. So I must have watered it.”',
      'Which one of the following shows the mistake Kurt has made?',
      ['The plant could have grown for another reason, such as rain.', 'Plants need sunlight too.', 'Kurt might forget to water it.', 'The plant might be a cactus.'], 0,
      'Kurt reverses the link: watering leads to growth, but growth does not prove watering. Plants needing sunlight is the nearest rival, but it does not show the reversal.',
      [null, 'this does not show the reversal', 'this is irrelevant', 'this is irrelevant']),
    WR('At a swimming carnival, every swimmer is in exactly one house: Red, Blue or Gold. Every Red swimmer swam in the relay. Nobody who swam in the relay swam in the diving.\nIris: “Jade swam in the diving, so she is not in Red.”\nJon: “Kane is not in Red, so he did not swim in the relay.”',
      'Iris', 'Jon', true, false,
      'Iris is right: Red swimmers all swam in the relay, and relay swimmers did not dive, so a diver cannot be in Red. Jon is wrong: Red swimmers swam in the relay, but swimmers from other houses may have too.'),
    TS('weaken', 'Ms Bose says: “Homework clubs improve results, because students who attend our homework club get better marks than students who do not.”',
      'Which one of these statements, if true, most weakens Ms Bose’s argument?',
      ['Students who attend the club were already getting better marks before they joined.', 'The club meets twice a week.', 'The club has a snack table.', 'Teachers volunteer at the club.'], 0,
      'If attendees were already stronger, the club may not be causing their better marks. Teachers volunteering is the nearest rival, but it does not affect the reasoning.',
      [null, 'frequency is irrelevant', 'snacks are irrelevant', 'this does not affect the reasoning']),
    TS('assumption', 'Lachlan says: “The museum will be quiet on Monday, so it is the best day for our class visit.”',
      'Which one of the following is an assumption Lachlan has made?',
      ['A quiet day is what makes a day best for the visit.', 'The museum is large.', 'The class likes museums.', 'The bus is available every day.'], 0,
      'His conclusion depends on quietness being the deciding factor. The bus being available is the nearest rival, but his argument relies on quietness, not transport.',
      [null, 'size is irrelevant', 'liking is irrelevant', 'his argument relies on quietness, not transport']),
    TS('strengthen', 'Ollie argues that the school should have a later start time because students would be more alert in the first lesson.',
      'Which one of these statements, if true, most strengthens Ollie’s argument?',
      ['At schools that moved their start time later, teachers reported students were noticeably more alert in morning lessons.', 'Many students catch the bus.', 'Some parents start work early.', 'First lesson is usually maths.'], 0,
      'Evidence from schools that tried it supports his claim. Some parents starting work early is the nearest rival, but it is a reason against the change.',
      [null, 'this is irrelevant', 'this is a reason against', 'the subject is irrelevant']),
    WR('A shop sells pens in packs of 3 and packs of 5 only. It does not sell single pens.\nKit: “It is impossible to buy exactly 13 pens.”\nLeo: “It is possible to buy exactly 4 pens.”',
      'Kit', 'Leo', false, false,
      'Neither is right. Kit is wrong: 13 = 3 + 5 + 5. Leo is wrong: the smallest packs hold 3 and 5, and no combination makes 4.'),
    TS('flaw', 'Sienna says: “Our class collected more money for charity than any other class, so our class must care the most about charity.”',
      'Which one of the following shows the mistake Sienna has made?',
      ['The amount collected may depend on other things, such as how many students are in the class or how wealthy the families are.', 'Charity is important.', 'The money went to a good cause.', 'Other classes also collected money.'], 0,
      'The amount raised does not measure how much people care. Other classes also collecting is the nearest rival, but it does not identify her error.',
      [null, 'this is not a flaw', 'this is irrelevant', 'this does not identify her error']),
  ],

  writing: {
    title: 'The stranger at the station', genre: 'narrative',
    stimulus: ['The last train had gone. On the empty platform, someone was waiting — someone who seemed to know my name.'],
    prompt: 'Write a story that begins or includes this moment.',
    guidance: ['Build suspense: what does the reader need to know, and when?', 'Develop your main character so the reader cares what happens.', 'Make your ending satisfying, whether it is surprising, warm or unsettling.'],
    rubricNotes: 'A strong response builds tension and atmosphere, develops at least one character with depth, and controls the pace of the story through to a deliberate ending.',
  },
});
