/* Medium Exam 7 — original content written for this site. */
'use strict';
defExam('M07', {
  reading: [
    readS1({ id: 'M07-s1', headnote: 'In this extract from a novel, Theo tries to repair an old radio.',
      extracts: [{ paras: [
        'The radio had belonged to Theo’s great-uncle, who had apparently listened to the cricket on it every summer for forty years and then, one February, stopped. Nobody knew whether the radio had stopped first or the great-uncle had. It was the sort of question his family preferred not to ask.',
        'Theo found it in the garage, behind the Christmas decorations, a wooden box the size of a loaf of bread with a cloth front and two brown knobs like the eyes of a patient animal. He carried it to his room as though it might wake.',
        'For three weeks he worked on it every afternoon. He borrowed a book from the library with a title so dull that the librarian raised her eyebrows. He learnt the names of things he had never known existed — valves, capacitors, a tuning coil — and discovered that most of what he had thought he knew about electricity was wrong in interesting ways.',
        'His sister, who was fifteen and knew everything, said that he could just listen to the cricket on his phone. This was true, and completely beside the point.',
        'On the twenty-second day, he replaced the last capacitor, plugged the radio in, and turned the left-hand knob. For a moment there was nothing. Then a faint warmth came from the back of the case, and a hum, and then — far away, as if through a long tunnel of years — a man’s voice said, “…and that’s a beautiful shot, through the covers for four.”',
        'Theo sat very still. He had expected to feel triumphant. Instead he felt as if he had opened a door into a room where someone had just been sitting, and the chair was still warm.',
      ] }],
      questions: [
        Q('What does the narrator suggest by saying the family “preferred not to ask” whether the radio or the great-uncle stopped first?', ['The question touches on the great-uncle’s death, which the family finds uncomfortable to discuss.', 'The family did not care about the great-uncle.', 'The radio was stolen.', 'The family did not like cricket.'], 0,
          'The great-uncle “stopped” one February — a gentle way of describing his death — and the family avoids the subject. Not caring is the nearest rival, but avoiding a painful topic suggests the opposite.',
          [null, 'avoiding a painful topic suggests they cared', 'nothing suggests theft', 'cricket is not the point']),
        Q('The knobs are compared to “the eyes of a patient animal”. This suggests the radio', ['seems alive and waiting for someone to bring it back.', 'is dangerous.', 'is brightly coloured.', 'is too heavy to carry.'], 0,
          'The radio seems to be quietly waiting, like an animal — reinforced by Theo carrying it “as though it might wake”. Dangerous is the nearest rival, but “patient” is gentle.',
          [null, '“patient” is gentle', 'the knobs are brown', 'Theo carries it easily']),
        Q('Why did the librarian raise her eyebrows?', ['She was surprised a boy would borrow such a dull-sounding technical book.', 'Theo was being noisy.', 'The book was overdue.', 'She did not recognise Theo.'], 0,
          'The title was “so dull” that it surprised her. The book being overdue is the nearest rival, but he was only borrowing it.',
          [null, 'nothing suggests noise', 'he was only borrowing it', 'nothing suggests this']),
        Q('What does the phrase “wrong in interesting ways” suggest about Theo?', ['He enjoys discovering his mistakes because they teach him something.', 'He is embarrassed by his ignorance.', 'He is bad at science.', 'He thinks the book is wrong.'], 0,
          'Calling his mistakes “interesting” shows curiosity rather than embarrassment. Being embarrassed is the nearest rival, but “interesting” is positive.',
          [null, '“interesting” is positive', 'he learns successfully', 'he trusts the book']),
        Q('How does the narrator present the sister’s comment?', ['As accurate but missing what really matters to Theo.', 'As unkind and hurtful.', 'As the correct solution.', 'As a joke.'], 0,
          'It was “true, and completely beside the point”: Theo’s aim is the radio itself. Being unkind is the nearest rival, but the narrator only says it misses the point.',
          [null, 'the narrator only says it misses the point', 'it is “beside the point”', 'it is not presented as a joke']),
        Q('Why is the voice described as coming “through a long tunnel of years”?', ['The old radio makes it feel like a connection to the past.', 'The broadcast was recorded long ago.', 'The radio is in a tunnel.', 'The volume is too loud.'], 0,
          'The sound feels distant, as if from the great-uncle’s time. A recording is the nearest rival, but the commentary is a live broadcast.',
          [null, 'it is a live broadcast', 'the radio is in his room', 'the voice is faint']),
        Q('How does Theo feel when the radio works?', ['Moved, as though he has come close to his great-uncle’s presence.', 'Triumphant and proud.', 'Disappointed with the sound.', 'Frightened of the radio.'], 0,
          'He “expected to feel triumphant”, but instead feels as if someone had just left a room. Triumphant is the nearest rival, but the text says “instead”.',
          [null, 'the text says “instead”', 'nothing suggests disappointment', 'the feeling is tender, not fearful']),
        Q('Which word best describes Theo in this extract?', ['Determined.', 'Careless.', 'Impatient.', 'Boastful.'], 0,
          'He works every afternoon for three weeks until the radio works. Impatient is the nearest rival, but three weeks of steady work shows the opposite.',
          [null, 'he works carefully', 'three weeks of steady work shows patience', 'he does not boast']),
      ] }),

    readS2({ id: 'M07-s2', title: 'Lights in the forest',
      text: 'On warm, damp nights in the rainforests of Springbrook, in south-east Queensland, the walls of certain gullies glow with thousands of tiny blue-green lights. They look like stars, but they are the larvae of a small fly, commonly …(1)… as glow-worms.\n\nEach larva makes its light through a chemical reaction in its body. The light is not just for show: it is a …(2)…. Every larva hangs down sticky silk threads, like fishing lines, and small insects that fly towards the glow become …(3)… in them. The larva then hauls in its catch and eats it.\n\nHungry glow-worms shine more brightly than ones that have …(4)… eaten, which makes sense: a brighter light attracts more prey.\n\nGlow-worms are extremely sensitive to disturbance. Torchlight can cause them to switch off their lights, and touching the threads can …(5)… them. Insect repellent, carried on visitors’ skin and clothing, can be harmful too. For this reason, visitors are asked to use only red light, to stay on the paths and to keep their voices …(6)….\n\nThey also need constant moisture. In a long dry spell, the colonies can …(7)… sharply, and scientists worry that a warmer, drier climate could threaten them.\n\nSeeing them is an experience few people forget. Standing in the dark, surrounded by glowing points of light, many visitors describe a feeling of being inside the night sky — a …(8)… made possible only by staying quiet and still.',
      gaps: [
        [['known', 'feared', 'sold', 'eaten'], 0, 'They are “commonly known as glow-worms”. Feared is the nearest rival, but the sentence introduces their name.', [null, 'the sentence introduces their name', 'nothing is sold', 'they are not eaten']],
        [['trap', 'warning', 'signal to other larvae', 'mistake'], 0, 'The light attracts insects that are then caught: it is a “trap”. Warning is the nearest rival, but the light draws prey in.', [null, 'the light draws prey in', 'the passage says it attracts prey, not other larvae', 'it is useful']],
        [['tangled', 'hidden', 'lost', 'free'], 0, 'Insects become “tangled” in the sticky threads. Free is the opposite.', [null, 'they are caught, not hidden', 'they are caught, not lost', 'they are caught']],
        [['recently', 'never', 'rarely', 'slowly'], 0, 'Hungry larvae glow more brightly than ones that have “recently eaten”. Never is the nearest rival, but a larva that had never eaten would be hungry.', [null, 'a larva that had never eaten would be hungry', '“rarely eaten” would also mean hungry', '“slowly eaten” is not the contrast']],
        [['damage', 'feed', 'wake', 'brighten'], 0, 'Touching the threads can “damage” them. Brighten is the nearest rival, but the paragraph is about harm.', [null, 'the paragraph is about harm', 'they are already awake at night', 'the paragraph is about harm']],
        [['low', 'cheerful', 'clear', 'loud'], 0, 'Visitors should keep their voices “low” to avoid disturbing them. Loud is the opposite.', [null, 'the point is quietness', 'clarity is not the point', 'loudness disturbs them']],
        [['shrink', 'spread', 'brighten', 'move'], 0, 'In dry spells the colonies “shrink” sharply. Spread is the opposite.', [null, 'dryness harms them', 'dryness harms them', '“move sharply” makes no sense']],
        [['wonder', 'danger', 'secret', 'mistake'], 0, 'The experience is a “wonder”. Secret is the nearest rival, but the colonies are visited by many people.', [null, 'the experience is not dangerous', 'many people visit', 'the experience is positive']],
      ] }),

    readS3({ id: 'M07-s3', headnote: 'In this poem the speaker remembers her mother’s garden.', title: 'My Mother’s Garden',
      lines: [
        'She never planned it. Things just arrived:',
        'a lemon tree from a neighbour’s cutting,',
        'mint that escaped from a pot and went on escaping,',
        'a rose that someone had thrown away.',
        '',
        'She talked to them the way she talked to us —',
        'impatiently, with love, expecting',
        'that they would do their best',
        'and telling them so.',
        '',
        'Now she is too old to kneel.',
        'She sits on the back step and directs me:',
        'not there, there; gently; no, more water;',
        'the mint will take over if you let it.',
        '',
        'And I do as I’m told, as I always have,',
        'and the lemon tree goes on giving,',
        'and the mint goes on escaping,',
        'and the rose, thrown away, goes on.',
      ],
      questions: [
        Q('What does “Things just arrived” (line 1) suggest about the garden?', ['It grew by chance and through gifts rather than by design.', 'Everything was bought from a shop.', 'Plants were delivered by post.', 'The garden was carefully planned.'], 0,
          'She “never planned it” — plants came from cuttings, escapes and rescues. Carefully planned is the opposite.',
          [null, 'the plants were gifts and rescues', 'nothing was posted', 'she “never planned it”']),
        Q('The mint that “went on escaping” is described as', ['spreading uncontrollably.', 'dying.', 'being stolen.', 'growing very slowly.'], 0,
          'Mint spreads quickly; “escaping” makes it seem like it is breaking free. Growing slowly is the opposite.',
          [null, 'it keeps growing', 'nothing is stolen', 'it spreads fast']),
        Q('How did the mother speak to her plants (lines 5–9)?', ['In the same demanding but loving way she spoke to her children.', 'Gently and quietly.', 'She never spoke to them.', 'Angrily.'], 0,
          '“Impatiently, with love”, as she spoke to her children. Angrily is the nearest rival, but “with love” softens it.',
          [null, 'she was impatient, not gentle', 'she spoke to them', '“with love” softens it']),
        Q('What has changed in the third stanza?', ['The mother is now too old to garden herself, so she guides the speaker.', 'The garden has died.', 'The speaker has moved away.', 'The mother has stopped caring about the garden.'], 0,
          'She is “too old to kneel” and directs the speaker from the step. Stopping caring is the nearest rival, but she still gives detailed instructions.',
          [null, 'the plants are still growing', 'the speaker is there', 'she still gives detailed instructions']),
        Q('What does “as I always have” (line 15) suggest?', ['The speaker has always obeyed her mother, with affection.', 'The speaker has always disliked gardening.', 'The speaker never listens.', 'The speaker is younger than the mother thinks.'], 0,
          'The speaker has long followed her mother’s instructions, and the tone is fond. Disliking gardening is the nearest rival, but nothing suggests this.',
          [null, 'nothing suggests dislike', 'the speaker obeys', 'irrelevant']),
        Q('What is suggested by the final line, “and the rose, thrown away, goes on”?', ['Something once rejected has survived and thrived through care, like the mother herself.', 'The rose will soon die.', 'The rose will be thrown away again.', 'The speaker dislikes the rose.'], 0,
          'The rescued rose endures, echoing the mother’s own lasting strength. Dying soon is the opposite of “goes on”.',
          [null, '“goes on” means it survives', 'nothing suggests this', 'the tone is fond']),
      ] }),

    readS4({ id: 'M07-s4', title: 'The machine that spread ideas',
      paras: [
        'Before the 1450s, books in Europe were copied by hand, usually by monks or professional scribes. ...(1)... As a result, books were rare and very expensive, and most people never owned one.',
        'Around 1450, in the German city of Mainz, Johannes Gutenberg developed a printing press using movable metal type. ...(2)... These could be arranged to form a page, inked, and pressed onto paper, then rearranged for the next page.',
        'The press was not entirely new. ...(3)... Gutenberg’s achievement was to combine existing ideas into a system that was fast, reliable and cheap.',
        'Its effects were enormous. ...(4)... By 1500, millions of books had been printed in Europe.',
        '...(5)... Scientists could share their discoveries quickly and check each other’s work, and new ideas spread faster than ever before.',
        'Some people worried about the change. ...(6)... Yet the printing press is now seen as one of the most important inventions in history.',
      ],
      sentences: [
        'Copying a single book could take months.',
        'Each letter was cast as a separate small block of metal.',
        'Printing from carved wooden blocks had been used in China centuries earlier.',
        'Within a few decades, printing workshops had spread to hundreds of European towns.',
        'Cheaper books meant that many more people learnt to read.',
        'They feared that the flood of books would spread errors and dangerous ideas.',
        'Gutenberg had borrowed money to set up his workshop.',
      ],
      answers: [0, 1, 2, 3, 4, 5],
      explains: [
        'Hand-copying taking months explains “As a result, books were rare and very expensive”.',
        '“Movable metal type” is explained by each letter being cast separately; “These” refers to the blocks.',
        '“The press was not entirely new” is supported by Chinese woodblock printing, which Gutenberg built on.',
        '“Its effects were enormous” leads to workshops spreading, then millions of books by 1500.',
        'The paragraph about wider effects opens with more people learning to read.',
        '“Some people worried” is explained by fears of errors and dangerous ideas. The sentence about borrowing money is the extra one.',
      ] }),

    readS5({ id: 'M07-s5', headnote: 'Four writers discuss boredom.',
      extracts: [
        { title: 'Extract A', paras: ['Psychologists have found that people who are bored are often more creative afterwards. In one study, participants who first did a dull task, such as copying numbers from a phone book, came up with more ideas in a creativity test than those who had not. Boredom, it seems, pushes the mind to look for something interesting.'] },
        { title: 'Extract B', paras: ['When I was ten, we had a summer with no television because the set had broken and my parents refused to replace it. I complained for a week. Then I started building a raft. It sank, but I have never had a better summer.'] },
        { title: 'Extract C', paras: ['We have almost eliminated boredom. Any spare moment — a queue, a bus ride, an ad break — can be filled instantly with a screen. I suspect we have lost something important: the empty time in which we used to daydream, reflect, and notice the world around us.'] },
        { title: 'Extract D', paras: ['Not all boredom is useful. Students who are bored in class because the work is far too easy, or far too hard, often switch off entirely. Teachers should treat persistent boredom as a sign that something needs to change, not as a character flaw.'] },
      ],
      items: [
        ['describes research linking boredom with creativity?', 'A', 'A describes a study in which bored participants had more ideas. B links boredom with creativity, but through personal experience, not research.'],
        ['describes a personal experience in which boredom led to an adventure?', 'B', 'The broken television led to building a raft. C discusses boredom generally, not a personal adventure.'],
        ['argues that technology has removed opportunities for reflection?', 'C', 'Screens fill every spare moment, leaving no time to daydream. A describes boredom’s benefits but not technology.'],
        ['suggests that boredom can be a sign of a problem?', 'D', 'Persistent boredom is “a sign that something needs to change”. C sees lost boredom as a problem, not boredom itself.'],
        ['explains the reason boredom may help the mind?', 'A', 'Boredom “pushes the mind to look for something interesting”. C says empty time allows daydreaming, but gives no explanation from research.'],
        ['mentions an attempt that failed but was still valued?', 'B', 'The raft sank, but it was the best summer. D mentions students switching off, but nothing valued.'],
        ['lists everyday situations that are now filled by screens?', 'C', 'A queue, a bus ride and an ad break. D lists reasons for classroom boredom, not everyday situations.'],
        ['warns against blaming people for being bored?', 'D', 'Boredom should not be treated “as a character flaw”. B complains about boredom, but blames no one.'],
        ['describes adults refusing to solve a problem for a child?', 'B', 'The parents refused to replace the broken television. D describes teachers, but they are urged to act, not refusing.'],
        ['mentions a task chosen because it was dull?', 'A', 'Participants copied numbers from a phone book. D mentions work that is too easy, but it was not chosen to be dull.'],
      ] }),
  ],

  thinking: [
    TS('strengthen', 'A principal argues that installing shade sails in the playground will reduce the number of students who get sunburnt at school.',
      'Which one of these statements, if true, most strengthens the principal’s argument?',
      ['Most sunburn at the school happens during lunch play, in the uncovered area where the sails would go.', 'Shade sails come in many colours.', 'Students should wear hats.', 'The school canteen sells ice blocks.'], 0,
      'If most sunburn happens in the exact area to be shaded, the sails should reduce it. Students wearing hats is the nearest rival, but it is a different solution.',
      [null, 'colour is irrelevant', 'this is a different solution', 'this is irrelevant']),
    TS('weaken', 'A newspaper says: “Teenagers today read less than ever, because sales of printed books to teenagers have fallen.”',
      'Which one of these statements, if true, most weakens the newspaper’s argument?',
      ['Teenagers now read many books as e-books and through school library apps, which are not counted in sales of printed books.', 'Printed books are expensive.', 'Some teenagers prefer magazines.', 'Bookshops have closed in some towns.'], 0,
      'If teenagers read in forms not counted in printed sales, falling sales do not show less reading. Printed books being expensive is the nearest rival: it explains lower sales, but does not show teenagers are still reading.',
      [null, 'this does not show they are still reading', 'magazines are a smaller point', 'this explains lower sales, but not reading']),
    WR('In a quiz, teams score 5 points for each correct answer and lose 2 points for each wrong answer. Unanswered questions score 0. Team Blue answered every one of 10 questions.\nMia: “If Team Blue got 6 right, they scored 22.”\nNed: “Team Blue cannot have scored an odd number of points.”',
      'Mia', 'Ned', true, false,
      'Mia is right: 6 right and 4 wrong is 30 − 8 = 22. Ned is wrong: for example, 1 right and 9 wrong is 5 − 18 = −13, and 3 right and 7 wrong is 15 − 14 = 1, which is odd.'),
    TS('flaw', 'Paige says: “Everyone in my family is right-handed. So most people in the world must be right-handed.”',
      'Which one of the following shows the mistake Paige has made?',
      ['Her conclusion might be true, but one family is far too small and similar a group to show it.', 'Some people are left-handed.', 'Handedness can run in families.', 'Paige might be left-handed.'], 0,
      'Even though the conclusion happens to be true, her evidence cannot support it. Handedness running in families is the nearest rival: it is part of why her family is unrepresentative, but it is not the full flaw.',
      [null, 'this does not identify the flaw', 'this is only part of the problem', 'she says everyone in her family is right-handed']),
    TS('conclusion', 'In a group of friends, everyone who likes jazz also likes blues. Nobody who likes blues likes opera. Pat likes opera.',
      'Which one of the following must be true?',
      ['Pat does not like jazz.', 'Pat likes blues.', 'Pat likes jazz but not blues.', 'Everyone who likes blues likes jazz.'], 0,
      'Jazz lovers like blues, and blues lovers do not like opera. Pat likes opera, so Pat does not like blues, and so cannot like jazz. Everyone who likes blues liking jazz is the nearest rival, but it reverses the first rule.',
      [null, 'opera lovers do not like blues', 'jazz lovers like blues', 'this reverses the first rule']),
    TS('weaken', 'Kieran says: “Electric scooters should be banned from footpaths, because they cause most of the accidents involving pedestrians.”',
      'Which one of these statements, if true, most weakens Kieran’s argument?',
      ['Official records show that bicycles, not scooters, are involved in most footpath accidents with pedestrians.', 'Scooters are quiet.', 'Scooters can go fast.', 'Some cities already ban scooters.'], 0,
      'This contradicts Kieran’s main reason. Scooters going fast is the nearest rival, but it supports his view.',
      [null, 'this supports his concern', 'this supports his view', 'this supports his view']),
    WR('At a camp, every student does exactly two of these activities: canoeing, archery and hiking. Nobody who does canoeing does archery.\nNoor: “Everyone who does canoeing also does hiking.”\nOmar: “Everyone does hiking.”',
      'Noor', 'Omar', true, true,
      'Both are right. Canoeists cannot do archery, so their second activity must be hiking. Anyone not doing hiking would have to do canoeing and archery, which is not allowed, so everyone does hiking.'),
    TS('assumption', 'Mr Webb says: “If we move the maths test to Friday, students will have more time to study, so they will do better.”',
      'Which one of the following is an assumption Mr Webb has made?',
      ['Students will use the extra time to study.', 'Maths is important.', 'Friday is the end of the week.', 'The test is hard.'], 0,
      'More time helps only if students actually use it for study. The test being hard is the nearest rival, but his argument does not depend on difficulty.',
      [null, 'this is a value, not an assumption', 'this is a fact, not an assumption', 'his argument does not depend on difficulty']),
    TS('strengthen', 'Doctors claim that a new hand-washing campaign in a hospital reduced infections.',
      'Which one of these statements, if true, most strengthens the doctors’ claim?',
      ['Infections fell in the wards where the campaign ran, but stayed the same in similar wards where it did not.', 'The campaign used bright posters.', 'Hand-washing takes thirty seconds.', 'Nurses liked the campaign.'], 0,
      'The comparison between similar wards links the fall to the campaign. Nurses liking it is the nearest rival, but liking is not evidence.',
      [null, 'posters are not evidence', 'this is irrelevant', 'liking is not evidence']),
    TS('flaw', 'Declan says: “If it snows, school will be closed. It has not snowed. So school will not be closed.”',
      'Which one of the following shows the mistake Declan has made?',
      ['School could be closed for another reason, such as a power failure.', 'It rarely snows.', 'Declan wants school to close.', 'Snow can be dangerous.'], 0,
      'Snow is one reason for closure, not the only one. Declan wanting school to close is the nearest rival, but it does not identify the logical error.',
      [null, 'this is irrelevant', 'this does not identify the logical error', 'this is irrelevant']),
    WR('A code uses only the digits 1, 2 and 3. Each code is three digits long and no digit can be used twice.\nPia: “There are exactly 9 possible codes.”\nQuinn: “Some codes have digits adding to 5.”',
      'Pia', 'Quinn', false, false,
      'Neither is right. Each code uses 1, 2 and 3 once each in some order, so there are 3 × 2 × 1 = 6 codes, not 9. Since every code uses all three digits, each one adds to 1 + 2 + 3 = 6, never 5.'),
    TS('weaken', 'Ms Tan says: “Our new school timetable has made students happier, because complaints to the office have fallen.”',
      'Which one of these statements, if true, most weakens Ms Tan’s argument?',
      ['At the same time the timetable changed, the office stopped accepting complaints in person and only accepts written forms.', 'The timetable has longer lunch breaks.', 'Students like the new timetable.', 'Complaints were mostly about the canteen.'], 0,
      'If making a complaint became harder, fewer complaints may not mean happier students. Complaints being about the canteen is the nearest rival, but it does not explain the fall.',
      [null, 'this supports her view', 'this supports her view', 'this does not explain the fall']),
    TS('conclusion', 'Five children stand in a line. Ella is in the middle. Finn is directly in front of Ella. Gus is at the front.',
      'Which one of the following must be true?',
      ['Gus is directly in front of Finn.', 'Finn is at the back.', 'Ella is directly behind Gus.', 'Gus is in the middle.'], 0,
      'Positions 1–5: Gus is 1, Ella is 3, Finn is 2 (directly in front of Ella). So Gus is directly in front of Finn. Ella directly behind Gus is the nearest rival, but Finn is between them.',
      [null, 'Finn is second', 'Finn is between them', 'Gus is at the front']),
    TS('strengthen', 'Holly argues that the library should stay open until 6 pm because many students would use it after school.',
      'Which one of these statements, if true, most strengthens Holly’s argument?',
      ['A survey found that over half the students would use the library after school if it were open.', 'The library has computers.', 'The librarian works part-time.', 'Some students play sport after school.'], 0,
      'Evidence of demand supports her argument. The library having computers is the nearest rival, but it does not show students would come.',
      [null, 'this does not show students would come', 'this is a difficulty', 'this weakens it slightly']),
    WR('At a party, everyone ate either pizza or pasta, and some ate both. Twelve people ate pizza and nine ate pasta. There were 16 people at the party.\nRay: “Four people ate both.”\nSue: “Seven people ate only pizza.”',
      'Ray', 'Sue', false, true,
      'Sue is right. 12 + 9 = 21, but there were only 16 people, so 21 − 16 = 5 ate both — not 4, so Ray is wrong. Then 12 − 5 = 7 ate only pizza.'),
    TS('flaw', 'Isla says: “Famous athletes eat this cereal, so if I eat it, I will become a famous athlete.”',
      'Which one of the following shows the mistake Isla has made?',
      ['The athletes’ success comes from training and talent, not from the cereal.', 'The cereal might be expensive.', 'Isla might not like the cereal.', 'Not all athletes are famous.'], 0,
      'Isla assumes the cereal causes success because successful people eat it. Not all athletes being famous is the nearest rival, but it does not identify her error.',
      [null, 'cost is irrelevant', 'taste is irrelevant', 'this does not identify her error']),
  ],

  writing: {
    title: 'Should zoos exist?', genre: 'discursive',
    stimulus: ['Some people believe zoos protect endangered animals and teach people to care about nature.', 'Others believe it is wrong to keep wild animals in captivity.'],
    prompt: 'Write a discussion of this issue, presenting more than one side, and reach your own conclusion.',
    guidance: ['Present each viewpoint fairly, with reasons and examples.', 'Use linking words to move between views.', 'Make your own conclusion clear and explain why you reached it.'],
    rubricNotes: 'A strong response explores the issue from more than one perspective, weighs the arguments fairly, and reaches a reasoned conclusion of its own.',
  },
});
