/* Medium Exam 8 — original content written for this site. */
'use strict';
defExam('M08', {
  reading: [
    readS1({ id: 'M08-s1', headnote: 'Read the two extracts, in which young people face a physical challenge, and answer the questions.',
      extracts: [
        { label: 'Extract A', title: 'The fig tree', paras: [
          'The Moreton Bay fig at the end of our street was older than the street itself, older than the houses, older, my grandfather said, than anyone’s great-grandmother. Its roots spread over the ground like the knuckles of an enormous hand.',
          'Every child in the street had tried to climb it, and every child had stopped at the same place: a smooth, bare stretch of trunk, higher than an adult could reach, with no branch to hold. Above it, the branches spread out like a staircase. Below it, everyone gave up.',
          'I spent the whole of one summer studying that stretch of trunk the way other people study for exams. I noticed a knot on the left side, no bigger than a fist. I noticed that if you wedged your foot into the fork of the big root, you could just reach it.',
          'On the last day of the holidays I did it. Foot in the fork, hand on the knot, a scramble that took the skin off both knees — and then I was on the first branch, and the whole street was spread below me like a map. I did not tell anyone. Some victories are better kept.',
        ] },
        { label: 'Extract B', title: 'Without a hand on the seat', paras: [
          'Dad ran beside me with one hand on the back of the seat, puffing, saying, “I’ve got you, I’ve got you.” We had done this every evening for a week. Every evening, the moment he let go, I wobbled and fell.',
          'On the eighth evening, I was concentrating so hard on the pedals that I did not hear his puffing stop. I rode to the end of the path, turned — badly, but I turned — and saw him standing at the gate, twenty metres away, both hands in the air.',
          'The bike fell over at once, of course. It turned out that knowing I was alone was the only thing I could not do. But I had already done it, and nobody can take back something that has already happened.',
        ] },
      ],
      questions: [
        Q('In Extract A, what does the comparison of the roots to “the knuckles of an enormous hand” suggest?', ['The roots are huge, knobbly and seem to grip the ground.', 'The tree is dangerous.', 'The roots are smooth.', 'The tree is dying.'], 0,
          'Knuckles are knobbly and part of a gripping hand; “enormous” stresses size. Smooth is the opposite of knuckles.',
          [null, 'nothing suggests danger', 'knuckles are knobbly', 'nothing suggests it is dying']),
        Q('Why had every child given up at the same place?', ['There was a smooth stretch of trunk with nothing to hold on to.', 'The branches above were broken.', 'Their parents stopped them.', 'The tree was too wide to hug.'], 0,
          'A “smooth, bare stretch” with “no branch to hold” stopped them. Broken branches is the nearest rival, but the branches above were “like a staircase”.',
          [null, 'the branches above were like a staircase', 'parents are not mentioned', 'width is not the problem']),
        Q('What does the narrator’s comparison to studying for exams show?', ['How carefully and seriously the narrator worked out the problem.', 'That the narrator disliked exams.', 'That the narrator failed.', 'That the tree was in a school.'], 0,
          'Studying the trunk “the way other people study for exams” shows careful, patient effort. Disliking exams is the nearest rival, but the comparison is about seriousness.',
          [null, 'the comparison is about seriousness', 'the narrator succeeded', 'the tree is at the end of the street']),
        Q('Why does the narrator not tell anyone about the climb?', ['The achievement feels more special as a private triumph.', 'The narrator was ashamed of the grazed knees.', 'Climbing the tree was forbidden.', 'Nobody would have believed it.'], 0,
          '“Some victories are better kept.” Nobody believing it is the nearest rival, but the narrator gives a reason that is about enjoying the victory privately.',
          [null, 'grazed knees are not a source of shame', 'nothing says it was forbidden', 'the narrator’s reason is about privacy']),
        Q('In Extract B, why had the narrator always fallen before?', ['As soon as Dad let go, the narrator lost balance.', 'The bike was broken.', 'The path was too steep.', 'Dad pushed too hard.'], 0,
          '“The moment he let go, I wobbled and fell.” Dad pushing too hard is the nearest rival, but he held the seat to steady it.',
          [null, 'nothing suggests a fault', 'the path is not described as steep', 'he held the seat to steady it']),
        Q('Why did the narrator not notice Dad had let go?', ['The narrator was concentrating hard on pedalling.', 'Dad crept away quietly on purpose.', 'The narrator had headphones on.', 'It was dark.'], 0,
          'The narrator was “concentrating so hard on the pedals” and did not hear the puffing stop. Dad creeping away on purpose is the nearest rival, but the text does not say it was planned.',
          [null, 'the text does not say it was planned', 'no headphones are mentioned', 'darkness is not mentioned']),
        Q('What does the narrator mean by “knowing I was alone was the only thing I could not do”?', ['The narrator could ride, but losing confidence on realising it caused the fall.', 'The narrator was lonely.', 'The narrator needed Dad to fix the bike.', 'The narrator could not turn.'], 0,
          'The bike fell only once the narrator knew Dad was not holding it; the skill was there but not the confidence. Not being able to turn is contradicted: “but I turned”.',
          [null, 'the line is about confidence, not loneliness', 'the bike is fine', '“but I turned”']),
        Q('What do the two extracts have in common?', ['Both narrators achieve something they had repeatedly failed to do.', 'Both narrators are helped by a parent.', 'Both narrators keep their success secret.', 'Both narrators are injured badly.'], 0,
          'The tree stopped every child before, and the narrator fell every evening before. Being helped by a parent is the nearest rival, but only Extract B has a parent helping.',
          [null, 'only B has a parent helping', 'only A keeps it secret', 'grazed knees are minor and only in A']),
      ] }),

    readS2({ id: 'M08-s2', title: 'Balloons into the sky',
      text: 'Twice a day, at the same times all around the world, weather forecasters release balloons into the sky. Each balloon is filled with helium or hydrogen and carries a small box of instruments, called a radiosonde, which …(1)… temperature, humidity and air pressure as it rises.\n\nThe balloon climbs at about five metres per second. As the air around it gets thinner, the balloon …(2)…, until it is several times its original size. At a height of around 30 kilometres, the rubber can stretch no further and the balloon bursts. A small parachute then brings the radiosonde …(3)… back to Earth.\n\nOn the way up, the radiosonde sends its readings back by radio every second or so. Because the balloon also drifts with the wind, tracking its …(4)… lets forecasters work out wind speed and direction at different heights.\n\nThese measurements are …(5)… for weather forecasting. Computers use them, along with data from satellites, ships and aircraft, to calculate how the atmosphere is likely to change over the coming days. Without balloon data, forecasts would be noticeably less …(6)….\n\nMost radiosondes are never recovered. They land in oceans, forests and deserts; some are found by farmers or hikers, who may find a label …(7)… them to return the box. Scientists are now working on designs that are cheaper and kinder to the environment, since hundreds of thousands are released each year and very few are ever …(8)….',
      gaps: [
        [['measures', 'changes', 'hides', 'ignores'], 0, 'The instruments “measure” temperature, humidity and pressure. Changes is the nearest rival, but instruments record conditions rather than alter them.', [null, 'instruments record, not alter', 'they send readings back', 'they record these things']],
        [['expands', 'shrinks', 'freezes', 'falls'], 0, 'In thinner air, the balloon “expands”, growing several times larger. Shrinks is the opposite.', [null, 'it grows larger', 'the point is size', 'it is still rising']],
        [['gently', 'quickly', 'loudly', 'upwards'], 0, 'A parachute brings it “gently” back to Earth. Quickly is the nearest rival, but parachutes slow a fall.', [null, 'parachutes slow a fall', 'noise is not the point', 'it comes back down']],
        [['position', 'colour', 'temperature', 'weight'], 0, 'Tracking its “position” as it drifts shows wind speed and direction. Temperature is the nearest rival, but it does not show the wind.', [null, 'colour does not show wind', 'temperature does not show wind', 'weight does not show wind']],
        [['vital', 'useless', 'secret', 'optional'], 0, 'Forecasts would be noticeably worse without them, so they are “vital”. Optional is the nearest rival, but losing them would harm forecasts.', [null, 'they are needed', 'they are shared openly', 'losing them would harm forecasts']],
        [['accurate', 'interesting', 'expensive', 'colourful'], 0, 'Without balloon data, forecasts would be less “accurate”. Expensive is the nearest rival, but the data make forecasts better, not cheaper.', [null, 'the point is quality', 'the point is quality, not cost', 'colour is irrelevant']],
        [['asking', 'warning', 'forbidding', 'paying'], 0, 'A label may be “asking them to return the box”. Forbidding is the opposite.', [null, 'a warning would not ask for a return', 'the label requests a return', '“paying them to return” does not fit “find a label”']],
        [['recovered', 'released', 'designed', 'repaired'], 0, 'Very few are “recovered”, which is why environmental designs matter. Released is the nearest rival, but hundreds of thousands are released.', [null, 'hundreds of thousands are released', 'they are designed', 'they are not mostly found to be repaired']],
      ] }),

    readS3({ id: 'M08-s3', headnote: 'In this poem the speaker goes fishing at night with a parent.', title: 'Night Fishing',
      lines: [
        'We go down to the jetty after dark,',
        'Dad with the rods and the bucket, me with the torch',
        'that makes a small brave circle on the boards',
        'and nothing anywhere else.',
        '',
        'The water talks to the pylons under us,',
        'a slap and a gulp, a slap and a gulp.',
        'The lights of the town are a long way off',
        'and getting further, though we haven’t moved.',
        '',
        'We don’t catch anything. We never do.',
        'Dad says the fish are wise to us. I think',
        'the fish are not the point. I think',
        'he likes the dark, the not-talking, me.',
        '',
        'Later, walking home, he takes the torch',
        'and I let him, and we go up the hill',
        'by the light of it, his hand on my shoulder,',
        'as if I might float off into the night.',
      ],
      questions: [
        Q('Why is the torch’s circle of light described as “brave” (line 3)?', ['It is small but holds back the large darkness around it.', 'It is very bright.', 'The speaker is frightened of it.', 'It shines on the fish.'], 0,
          'A small light surrounded by darkness seems courageous. Very bright is the nearest rival, but the circle is “small”, with “nothing anywhere else”.',
          [null, 'the circle is “small”', 'the speaker holds it', 'it shines on the boards']),
        Q('What sound does the water make against the pylons?', ['A slap and a gulp.', 'A roar.', 'A whisper.', 'A splash and a crash.'], 0,
          'Line 6: “a slap and a gulp, a slap and a gulp”. A whisper is the nearest rival, but “talks” is followed by the actual sounds.',
          [null, 'the sound is gentle and rhythmic', 'the sounds are named', 'these words are not used']),
        Q('What does “getting further, though we haven’t moved” (line 9) suggest?', ['As night deepens, the speaker feels increasingly separate from the town.', 'The jetty is drifting out to sea.', 'The town lights are switching off.', 'The speaker is falling asleep.'], 0,
          'They are still, yet the town seems to recede — a feeling of separation. The jetty drifting is the nearest rival, but jetties do not move.',
          [null, 'jetties do not move', 'the lights are still there', 'nothing suggests sleep']),
        Q('What does the speaker believe is the real reason Dad likes night fishing?', ['He enjoys quiet time with his child.', 'He wants to catch a big fish.', 'He likes the town lights.', 'He wants to teach the speaker to fish.'], 0,
          'The speaker thinks “the fish are not the point” — Dad likes “the dark, the not-talking, me”. Catching a fish is the nearest rival, but they never catch anything.',
          [null, 'they never catch anything', 'the lights are far away', 'teaching is not mentioned']),
        Q('What does “and I let him” (line 16) suggest about the speaker?', ['The speaker understands and accepts Dad’s wish to look after them.', 'The speaker is too tired to carry the torch.', 'The speaker is angry with Dad.', 'The speaker has dropped the torch.'], 0,
          'Letting him take the torch is a quiet act of acceptance. Being too tired is the nearest rival, but the poem gives no sign of tiredness.',
          [null, 'the poem gives no sign of tiredness', 'the tone is warm', 'he “takes” it']),
        Q('What does the final image, “as if I might float off into the night”, suggest about Dad?', ['He is protective, wanting to hold on to his child.', 'He thinks the speaker is very light.', 'He is frightened of the dark.', 'He wants to go home quickly.'], 0,
          'His hand on the speaker’s shoulder shows a wish to keep them close. Being frightened of the dark is the nearest rival, but the poem says he “likes the dark”.',
          [null, 'the image is about care, not weight', 'he “likes the dark”', 'nothing suggests hurry']),
      ] }),

    readS4({ id: 'M08-s4', title: 'Papers, please',
      paras: [
        'For most of history, ordinary people could travel between countries without any special document. ...(1)... Some rulers did issue letters asking that the bearer be allowed to pass safely, but these were rare.',
        'This began to change in the nineteenth century, as railways made international travel far more common. ...(2)... In fact, by the 1870s, many European countries had stopped checking documents at their borders altogether.',
        'The First World War changed everything. ...(3)... After the war, many of these controls stayed in place.',
        'In 1920, the League of Nations, an early international organisation, held a conference on passports. ...(4)... It set out a standard size, layout and language for passports, so that officials in any country could understand them.',
        '...(5)... In the 1980s, countries agreed on a machine-readable format, with lines of letters and numbers that a computer could scan.',
        'Today, most passports contain a tiny electronic chip that stores the holder’s photograph and personal details. ...(6)...',
      ],
      sentences: [
        'Borders were often not clearly marked, and few officials checked who was crossing them.',
        'At first, though, governments struggled to check the papers of so many travellers.',
        'Worried about spies, governments began demanding that everyone crossing a border carry a passport with a photograph.',
        'Its aim was to make passports similar all over the world.',
        'The design of the passport has continued to develop since then.',
        'This makes passports much harder to forge.',
        'Some people collect old passports as a hobby.',
      ],
      answers: [0, 1, 2, 3, 4, 5],
      explains: [
        'Unmarked, unchecked borders explain why people travelled without documents, before the “letters” given by some rulers.',
        'Railways increased travel; the gap says governments struggled to check so many people, leading to “In fact … stopped checking”.',
        '“The First World War changed everything” is explained by new passport demands; “these controls” refers back to them.',
        'The conference is introduced, its aim given, and then “It set out a standard size…”.',
        'The paragraph about the 1980s needs an opening that says the design kept changing.',
        'The chip is described, then its effect: harder to forge. The sentence about collecting is the extra one.',
      ] }),

    readS5({ id: 'M08-s5', headnote: 'Four writers discuss kindness.',
      extracts: [
        { title: 'Extract A', paras: ['Studies have found that doing something kind for someone else can make the helper happier, sometimes more than spending the same money on themselves. In one experiment, people given money to spend on others reported feeling better at the end of the day than people told to spend it on themselves.'] },
        { title: 'Extract B', paras: ['On my first day at a new school, I sat alone at lunch. A girl I had never met sat down next to me, offered me half her sandwich and said nothing at all. We have been friends for six years. I still do not know whether she knew how much that silence meant.'] },
        { title: 'Extract C', paras: ['Kindness is not the same as niceness. A nice person tells you your essay is wonderful. A kind person tells you, gently, that the second paragraph does not make sense, because they want your essay to be good. Real kindness sometimes involves saying what people do not want to hear.'] },
        { title: 'Extract D', paras: ['Schools should teach kindness as deliberately as they teach maths. It can be practised, like any skill: noticing when someone is left out, offering help without being asked, thanking people properly. Children who practise these habits are more likely to keep them as adults.'] },
      ],
      items: [
        ['describes research suggesting that kindness benefits the giver?', 'A', 'People who spent money on others felt better. B describes kindness, but from the receiver’s side.'],
        ['describes a kind act that did not involve words?', 'B', 'The girl offered half her sandwich and “said nothing at all”. C contrasts what people say.'],
        ['distinguishes between two qualities that are often confused?', 'C', 'Kindness “is not the same as niceness”. D treats kindness as a skill, not in contrast with something.'],
        ['argues that kindness can be learnt through practice?', 'D', 'Kindness “can be practised, like any skill”. A shows benefits of kindness, not how it is learnt.'],
        ['compares two ways of spending money?', 'A', 'Spending on others versus on oneself. D lists habits, but none about money.'],
        ['describes a lasting result of a small act?', 'B', 'A shared sandwich led to six years of friendship. D says habits last into adulthood, but describes no single act.'],
        ['suggests that honesty can be a form of kindness?', 'C', 'A kind person tells you what is wrong with your essay. B’s kindness is silent, not honest criticism.'],
        ['lists specific kind habits?', 'D', 'Noticing who is left out, helping, thanking people. A describes one experiment, not habits.'],
        ['expresses uncertainty about another person’s intentions?', 'B', 'The writer does not know “whether she knew how much that silence meant”. C is confident about what kind people intend.'],
        ['uses an example from schoolwork to make a point?', 'C', 'C uses the example of an essay. D is about schools, but its examples are social habits, not schoolwork.'],
      ] }),
  ],

  thinking: [
    TS('strengthen', 'Jasmine argues that the school should replace paper newsletters with emails because most families would read them.',
      'Which one of these statements, if true, most strengthens Jasmine’s argument?',
      ['A survey found that almost every family checks email daily, while many paper newsletters are never taken out of school bags.', 'Emails save paper.', 'Some families prefer paper.', 'The newsletter is published weekly.'], 0,
      'Evidence that families read email, and do not receive paper copies, supports her claim about reading. Emails saving paper is the nearest rival, but it is a different reason.',
      [null, 'this is a different reason', 'this weakens it', 'this is irrelevant']),
    TS('weaken', 'A car company claims: “Our cars are the safest, because fewer people are injured in our cars than in any other brand.”',
      'Which one of these statements, if true, most weakens the company’s claim?',
      ['The company sells far fewer cars than other brands, so there are fewer of its cars on the road to be in accidents.', 'The company’s cars are expensive.', 'The cars have airbags.', 'The cars come in many colours.'], 0,
      'With fewer cars on the road, fewer injuries may not mean safer cars. The cars having airbags is the nearest rival, but it supports the claim.',
      [null, 'price is irrelevant', 'this supports the claim', 'colour is irrelevant']),
    WR('In a school, every Year 6 student is in the Green team or the Gold team. Everyone in the Green team has a school laptop. Nobody in the Gold team plays in the band.\nTia: “Rob is in Year 6 and plays in the band, so he has a school laptop.”\nUma: “Vic is in Year 6 and has a school laptop, so she is in the Green team.”',
      'Tia', 'Uma', true, false,
      'Tia is right: Rob plays in the band, so he is not in Gold; every Year 6 student is in Green or Gold, so he is in Green and has a laptop. Uma is wrong: Green team members have laptops, but Gold team members might have them too.'),
    TS('flaw', 'Bryce says: “Our town has more ice-cream shops than ever, and more people are getting sunburnt than ever. So ice-cream shops cause sunburn.”',
      'Which one of the following shows the mistake Bryce has made?',
      ['Both could be caused by something else, such as hotter summers bringing more people outdoors.', 'Ice cream is cold.', 'Sunburn is dangerous.', 'Some ice-cream shops close in winter.'], 0,
      'Two things rising together may share a cause rather than one causing the other. Shops closing in winter is the nearest rival: it hints at seasons but does not identify the flaw.',
      [null, 'this is irrelevant', 'this is irrelevant', 'this does not identify the flaw']),
    TS('conclusion', 'Every bus that goes to the city stops at the station. The 42 does not stop at the station. Some buses that stop at the station go to the beach.',
      'Which one of the following must be true?',
      ['The 42 does not go to the city.', 'The 42 goes to the beach.', 'Every bus that stops at the station goes to the city.', 'No bus goes to both the city and the beach.'], 0,
      'Every city bus stops at the station, so the 42, which does not, cannot go to the city. Every station bus going to the city is the nearest rival, but it reverses the first rule.',
      [null, 'nothing says where the 42 goes', 'this reverses the first rule', 'this cannot be worked out']),
    TS('weaken', 'Felix says: “Our soccer team should practise on the main oval, because it is the biggest field.”',
      'Which one of these statements, if true, most weakens Felix’s argument?',
      ['The main oval is booked by the cricket club at the time the soccer team trains.', 'The main oval has new grass.', 'The oval is close to the change rooms.', 'Soccer needs a large field.'], 0,
      'If the oval is unavailable when they train, its size does not help. Soccer needing a large field is the nearest rival, but it supports Felix.',
      [null, 'this supports Felix', 'this supports Felix', 'this supports Felix']),
    WR('A recipe says: “Each batch of pancakes needs 2 eggs and 1 cup of flour.” Wren has 7 eggs and 5 cups of flour and wants to make as many whole batches as possible.\nXavier: “Wren can make 5 batches.”\nYara: “Wren will have some flour left over.”',
      'Xavier', 'Yara', false, true,
      'Yara is right: 7 eggs make only 3 batches (needing 6 eggs), which uses 3 cups of flour, leaving 2 cups. Xavier is wrong: 5 batches would need 10 eggs.'),
    TS('assumption', 'Mrs Lowe says: “If we plant more trees in the schoolyard, students will be cooler at lunchtime.”',
      'Which one of the following is an assumption Mrs Lowe has made?',
      ['The trees will grow large enough to give shade where students spend lunchtime.', 'Trees are beautiful.', 'The school has enough money for trees.', 'Students like trees.'], 0,
      'Planting only cools students if the trees end up shading where they are. Having enough money is the nearest rival, but her claim is about the effect, not whether it can be paid for.',
      [null, 'beauty is irrelevant', 'her claim is about the effect, not cost', 'liking is irrelevant']),
    TS('strengthen', 'A researcher claims that people who sleep less are more likely to catch colds.',
      'Which one of these statements, if true, most strengthens the claim?',
      ['In a study, volunteers exposed to a cold virus were more likely to get sick if they had slept less than six hours a night in the week before.', 'Colds are common in winter.', 'Sleep is important for health.', 'Some people need more sleep than others.'], 0,
      'A study linking short sleep to getting sick when exposed supports the claim. Sleep being important is the nearest rival, but it is too general.',
      [null, 'this is about season, not sleep', 'this is too general', 'this does not support the link']),
    TS('flaw', 'Ana says: “Either you support the new canteen menu or you don’t care about students’ health.”',
      'Which one of the following shows the mistake Ana has made?',
      ['Someone could care about students’ health and still disagree with this particular menu.', 'The menu might be popular.', 'Health is important.', 'The canteen might lose money.'], 0,
      'Ana offers only two options, ignoring people who care about health but prefer a different menu. The menu being popular is the nearest rival, but it does not identify the false choice.',
      [null, 'this does not identify the false choice', 'this is a value', 'this is irrelevant']),
    WR('In a game, a spinner has 4 equal sections numbered 1, 2, 3 and 4. A player spins twice and adds the numbers.\nZed: “The highest possible total is 8.”\nAmy: “A total of 5 is more likely than a total of 2.”',
      'Zed', 'Amy', true, true,
      'Both are right. The highest total is 4 + 4 = 8. A total of 5 can happen four ways (1+4, 2+3, 3+2, 4+1), but a total of 2 only one way (1+1).'),
    TS('weaken', 'The mayor says: “The new speed cameras have made our roads safer, because there were fewer crashes this year.”',
      'Which one of these statements, if true, most weakens the mayor’s argument?',
      ['Crashes fell by the same amount in nearby towns that did not install cameras.', 'The cameras cost a lot.', 'Many drivers got fines.', 'The cameras are on main roads.'], 0,
      'If crashes fell just as much without cameras, something else probably caused the fall. Many drivers getting fines is the nearest rival, but it does not show the cameras failed.',
      [null, 'cost is irrelevant', 'this does not show the cameras failed', 'location is irrelevant']),
    TS('conclusion', 'Lin is older than Max. Max is older than Ned. Ollie is younger than Ned.',
      'Which one of the following must be true?',
      ['Lin is older than Ollie.', 'Ollie is older than Max.', 'Ned is the youngest.', 'Max is the oldest.'], 0,
      'The order from oldest is Lin, Max, Ned, Ollie, so Lin is older than Ollie. Ned being youngest is the nearest rival, but Ollie is younger than Ned.',
      [null, 'Ollie is younger than Ned, who is younger than Max', 'Ollie is younger than Ned', 'Lin is older than Max']),
    TS('strengthen', 'Ms Gray claims that her class’s spelling improved because they read for twenty minutes every day.',
      'Which one of these statements, if true, most strengthens her claim?',
      ['The class did nothing else differently this year, and students who read the most improved the most.', 'Reading is enjoyable.', 'The class has a reading corner.', 'Spelling tests are every week.'], 0,
      'Ruling out other changes and showing more reading linked to more improvement supports her claim. The class having a reading corner is the nearest rival, but it is not evidence of the link.',
      [null, 'enjoyment is not evidence', 'this is not evidence of the link', 'this is irrelevant']),
    WR('At a sports day, every student enters at least one race. Anyone who enters the sprint must also enter the relay. Bea entered only one race.\nCam: “Bea entered the sprint.”\nDev: “Bea entered the relay.”',
      'Cam', 'Dev', false, false,
      'Neither is right. Cam is wrong: anyone in the sprint must also be in the relay, which would be two races, but Bea entered only one. Dev is wrong: Bea’s one race could have been the relay, but it could also have been another race, such as hurdles; nothing says the relay was the only other race.'),
    TS('flaw', 'Tom says: “I have never broken a bone, so I don’t need to wear a helmet when I ride my bike.”',
      'Which one of the following shows the mistake Tom has made?',
      ['Not having been hurt before does not mean he cannot be hurt in the future.', 'Helmets are uncomfortable.', 'Tom might fall off.', 'Bikes can be fast.'], 0,
      'Tom assumes past safety guarantees future safety. Tom might fall off is the nearest rival: it is true, but it does not describe the flaw in his reasoning.',
      [null, 'this is irrelevant', 'this does not describe the flaw', 'this is irrelevant']),
  ],

  writing: {
    title: 'Front-page news', genre: 'recount',
    stimulus: ['A surprising event has happened at your school or in your town — an animal escaped, a record was broken, a time capsule was found, or something else of your choice.'],
    prompt: 'Write a news report about the event for your local newspaper.',
    guidance: ['Start with a headline and an opening sentence that answers who, what, where and when.', 'Report events in a clear order, with the most important information first.', 'Include quotes from people who were there.', 'Use a factual, objective tone.'],
    rubricNotes: 'A strong response follows the features of a news report, presents events clearly and in a logical order, uses quotation effectively and keeps a consistent, objective tone.',
  },
});
